//! The checked-in `protocol/rust/src/cdp/` is what the generator produces from the checked-in protocol JSON, so a
//! hand edit or a stale generation fails CI (brief 0023). Needs `rustfmt` (the pinned toolchain has it).

use std::collections::BTreeSet;

#[test]
fn checked_in_output_is_current() {
    let scratch = tempfile::tempdir().unwrap();
    let started = std::time::Instant::now();
    let g = eludite_cdp_generator::generate_formatted(
        &eludite_cdp_generator::cdp_dir(),
        scratch.path(),
    )
    .unwrap_or_else(|e| panic!("generation failed: {e}"));
    println!(
        "generated {} files ({} structs, {} enums, {} commands, {} events) in {:.0} ms",
        g.files.len(),
        g.stats.structs,
        g.stats.enums,
        g.stats.commands,
        g.stats.events,
        started.elapsed().as_secs_f64() * 1e3
    );
    let out = eludite_cdp_generator::output_dir();
    let mut stale = Vec::new();
    for (name, text) in &g.files {
        match std::fs::read_to_string(out.join(name)) {
            Ok(current) if current == *text => {}
            Ok(_) => stale.push(format!("{name} differs")),
            Err(e) => stale.push(format!("{name}: {e}")),
        }
    }
    let on_disk: BTreeSet<String> = std::fs::read_dir(&out)
        .unwrap()
        .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
        .collect();
    for extra in on_disk.iter().filter(|n| !g.files.contains_key(*n)) {
        stale.push(format!("{extra} is not generated"));
    }
    assert!(
        stale.is_empty(),
        "protocol/rust/src/cdp/ is not current ({}); run `cargo run -p eludite-cdp-generator`",
        stale.join("; ")
    );
    for (name, text) in &g.files {
        assert!(
            text.starts_with("// Generated by eludite-cdp-generator from devtools-protocol "),
            "{name} lacks the header"
        );
        assert!(text.contains("Do not edit"), "{name}");
    }
}

#[test]
fn the_roots_and_their_references_are_generated() {
    let read = |n: &str| std::fs::read_to_string(eludite_cdp_generator::cdp_dir().join(n)).unwrap();
    let g = eludite_cdp_generator::generate(
        &read("browser_protocol.json"),
        &read("js_protocol.json"),
        "test",
    )
    .unwrap();
    for root in eludite_cdp_generator::ROOTS {
        assert!(g.stats.domains.iter().any(|d| d == root), "{root}");
    }
    // Referenced, not listed: Page and Network use Debugger.SearchMatch, Network uses IO.StreamHandle.
    assert!(g.stats.domains.iter().any(|d| d == "Debugger"));
    assert!(g.stats.domains.iter().any(|d| d == "IO"));
    assert_eq!(g.files.len(), g.stats.domains.len() + 1);
    let page = &g.files["page.rs"];
    assert!(page.contains("pub struct CaptureScreenshotParams"));
    assert!(page.contains("pub const METHOD: &'static str = \"Page.captureScreenshot\";"));
    assert!(page.contains("pub struct FrameNavigatedEvent"));
    // Recursive types are boxed; keywords are renamed.
    assert!(g.files["runtime.rs"].contains("pub parent: Option<Box<StackTrace>>"));
    assert!(g.files["runtime.rs"].contains("#[serde(rename = \"type\")]"));
}
