using System.Globalization;
using System.Security;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml;
using System.Xml.Linq;

namespace Eludite.Host.Resources;

/// <summary>
/// Writes a neutral <c>.resx</c> file's designer code in the shape Visual Studio's <c>ResXFileCodeGenerator</c>
/// (<c>internal</c>) and <c>PublicResXFileCodeGenerator</c> (<c>public</c>) write through
/// <c>StronglyTypedResourceBuilder</c> and CodeDom (proposal 0005, section 2 "Designer files"): the header, the
/// namespace, the class with <c>ResourceManager</c> and <c>Culture</c>, one property per entry sorted by key ignoring
/// case, string entries through <c>GetString</c> with the value in the summary (cut at 512 characters, escaped as
/// <see cref="SecurityElement.Escape"/> does), streams through <c>GetStream</c>, everything else through
/// <c>GetObject</c> with a cast. CRLF line endings, UTF-8 without a byte order mark. <c>corpus/resx</c>'s designer
/// files are the expected bytes.
/// </summary>
public static partial class DesignerGenerator
{
    private const int DocCommentLengthThreshold = 512;

    // StronglyTypedResourceBuilder.CharsToReplace.
    private static readonly char[] CharsToReplace =
    [
        ' ', '\u00A0', '.', ',', ';', '|', '~', '@', '#', '%', '^', '&', '*', '+', '-', '/', '\\', '<', '>', '?', '[', ']', '(', ')', '{', '}', '"', '\'', ':', '!',
    ];

    private static readonly HashSet<string> Keywords = new(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else", "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock", "long", "namespace", "new", "null", "object", "operator", "out", "override", "params", "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual", "void", "volatile", "while",
        "__arglist", "__makeref", "__reftype", "__refvalue",
    };

    // CodeDom's CSharpCodeGenerator writes these runtime types by their keyword.
    private static readonly Dictionary<string, string> PrimitiveNames = new(StringComparer.Ordinal)
    {
        ["System.Int16"] = "short",
        ["System.Int32"] = "int",
        ["System.Int64"] = "long",
        ["System.String"] = "string",
        ["System.Object"] = "object",
        ["System.Boolean"] = "bool",
        ["System.Void"] = "void",
        ["System.Char"] = "char",
        ["System.Byte"] = "byte",
        ["System.UInt16"] = "ushort",
        ["System.UInt32"] = "uint",
        ["System.UInt64"] = "ulong",
        ["System.SByte"] = "sbyte",
        ["System.Single"] = "float",
        ["System.Double"] = "double",
        ["System.Decimal"] = "decimal",
    };

    private enum Kind
    {
        String,
        Stream,
        Object,
    }

    private sealed record Entry(string Key, string Name, Kind Kind, string Value, string TypeName);

    /// <summary>The designer's text for <paramref name="resxPath"/>, CRLF, without a byte order mark.</summary>
    /// <param name="modifier"><c>internal</c> or <c>public</c>: the class's, <c>ResourceManager</c>'s and <c>Culture</c>'s modifier.</param>
    public static string Generate(string resxPath, string @namespace, string className, string manifestName, string modifier)
    {
        ArgumentNullException.ThrowIfNull(resxPath);
        ArgumentNullException.ThrowIfNull(@namespace);
        ArgumentNullException.ThrowIfNull(className);
        ArgumentNullException.ThrowIfNull(manifestName);
        if (modifier is not ("internal" or "public"))
        {
            throw new ArgumentOutOfRangeException(nameof(modifier), modifier, "internal or public");
        }

        var entries = Read(resxPath);
        var sb = new StringBuilder();
        sb.Append("//------------------------------------------------------------------------------\n");
        sb.Append("// <auto-generated>\n");
        sb.Append("//     This code was generated by a tool.\n");
        sb.Append("//     Runtime Version:4.0.30319.42000\n");
        sb.Append("//\n");
        sb.Append("//     Changes to this file may cause incorrect behavior and will be lost if\n");
        sb.Append("//     the code is regenerated.\n");
        sb.Append("// </auto-generated>\n");
        sb.Append("//------------------------------------------------------------------------------\n");
        sb.Append('\n');
        sb.Append("namespace ").Append(@namespace).Append(" {\n");
        sb.Append("    using System;\n");
        sb.Append("    \n");
        sb.Append("    \n");
        sb.Append("    /// <summary>\n");
        sb.Append("    ///   A strongly-typed resource class, for looking up localized strings, etc.\n");
        sb.Append("    /// </summary>\n");
        sb.Append("    // This class was auto-generated by the StronglyTypedResourceBuilder\n");
        sb.Append("    // class via a tool like ResGen or Visual Studio.\n");
        sb.Append("    // To add or remove a member, edit your .ResX file then rerun ResGen\n");
        sb.Append("    // with the /str option, or rebuild your VS project.\n");
        sb.Append("    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"System.Resources.Tools.StronglyTypedResourceBuilder\", \"17.0.0.0\")]\n");
        sb.Append("    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]\n");
        sb.Append("    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]\n");
        sb.Append("    ").Append(modifier).Append(" class ").Append(className).Append(" {\n");
        sb.Append("        \n");
        sb.Append("        private static global::System.Resources.ResourceManager resourceMan;\n");
        sb.Append("        \n");
        sb.Append("        private static global::System.Globalization.CultureInfo resourceCulture;\n");
        sb.Append("        \n");
        sb.Append("        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute(\"Microsoft.Performance\", \"CA1811:AvoidUncalledPrivateCode\")]\n");
        sb.Append("        internal ").Append(className).Append("() {\n");
        sb.Append("        }\n");
        sb.Append("        \n");
        sb.Append("        /// <summary>\n");
        sb.Append("        ///   Returns the cached ResourceManager instance used by this class.\n");
        sb.Append("        /// </summary>\n");
        sb.Append("        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]\n");
        sb.Append("        ").Append(modifier).Append(" static global::System.Resources.ResourceManager ResourceManager {\n");
        sb.Append("            get {\n");
        sb.Append("                if (object.ReferenceEquals(resourceMan, null)) {\n");
        sb.Append("                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(").Append(Quote(manifestName)).Append(", typeof(").Append(className).Append(").Assembly);\n");
        sb.Append("                    resourceMan = temp;\n");
        sb.Append("                }\n");
        sb.Append("                return resourceMan;\n");
        sb.Append("            }\n");
        sb.Append("        }\n");
        sb.Append("        \n");
        sb.Append("        /// <summary>\n");
        sb.Append("        ///   Overrides the current thread's CurrentUICulture property for all\n");
        sb.Append("        ///   resource lookups using this strongly typed resource class.\n");
        sb.Append("        /// </summary>\n");
        sb.Append("        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]\n");
        sb.Append("        ").Append(modifier).Append(" static global::System.Globalization.CultureInfo Culture {\n");
        sb.Append("            get {\n");
        sb.Append("                return resourceCulture;\n");
        sb.Append("            }\n");
        sb.Append("            set {\n");
        sb.Append("                resourceCulture = value;\n");
        sb.Append("            }\n");
        sb.Append("        }\n");

        foreach (var entry in entries)
        {
            sb.Append("        \n");
            sb.Append("        /// <summary>\n");
            sb.Append("        /// ");
            AppendComment(sb, entry.Kind == Kind.String
                ? "  Looks up a localized string similar to " + Escape(Truncate(entry.Value)) + "."
                : "  Looks up a localized resource of type " + entry.TypeName + ".");
            sb.Append('\n');
            sb.Append("        /// </summary>\n");
            switch (entry.Kind)
            {
                case Kind.String:
                    sb.Append("        ").Append(modifier).Append(" static string ").Append(entry.Name).Append(" {\n");
                    sb.Append("            get {\n");
                    sb.Append("                return ResourceManager.GetString(").Append(Quote(entry.Key)).Append(", resourceCulture);\n");
                    sb.Append("            }\n");
                    sb.Append("        }\n");
                    break;
                case Kind.Stream:
                    sb.Append("        ").Append(modifier).Append(" static System.IO.UnmanagedMemoryStream ").Append(entry.Name).Append(" {\n");
                    sb.Append("            get {\n");
                    sb.Append("                return ResourceManager.GetStream(").Append(Quote(entry.Key)).Append(", resourceCulture);\n");
                    sb.Append("            }\n");
                    sb.Append("        }\n");
                    break;
                default:
                    var type = CodeTypeName(entry.TypeName);
                    sb.Append("        ").Append(modifier).Append(" static ").Append(type).Append(' ').Append(entry.Name).Append(" {\n");
                    sb.Append("            get {\n");
                    sb.Append("                object obj = ResourceManager.GetObject(").Append(Quote(entry.Key)).Append(", resourceCulture);\n");
                    sb.Append("                return ((").Append(type).Append(")(obj));\n");
                    sb.Append("            }\n");
                    sb.Append("        }\n");
                    break;
            }
        }

        sb.Append("    }\n");
        sb.Append("}\n");

        // The generator's own line ends are CRLF; a CRLF inside a value keeps its CR and gets one more (CR CR LF), as
        // Visual Studio's designer files have it.
        return sb.ToString().Replace("\n", "\r\n", StringComparison.Ordinal);
    }

    /// <summary>The designer's bytes: UTF-8 without a byte order mark.</summary>
    public static byte[] Bytes(string text) => new UTF8Encoding(false).GetBytes(text);

    /// <summary>
    /// The key as a C# member name, as <c>StronglyTypedResourceBuilder.VerifyResourceName</c> makes it: the characters
    /// it replaces become <c>_</c>, a name that is not an identifier (a leading digit, a keyword) is prefixed with
    /// <c>_</c>; null when no identifier comes of it.
    /// </summary>
    public static string? MakeIdentifier(string key)
    {
        ArgumentNullException.ThrowIfNull(key);
        var name = key;
        foreach (var c in CharsToReplace)
        {
            name = name.Replace(c, '_');
        }

        if (IsValidIdentifier(name))
        {
            return name;
        }

        name = "_" + name;
        return IsValidIdentifier(name) ? name : null;
    }

    /// <summary>The class modifier of an existing designer file (<c>public</c> or <c>internal</c>), else null.</summary>
    public static string? ReadClassModifier(string designerPath)
    {
        ArgumentNullException.ThrowIfNull(designerPath);
        try
        {
            foreach (var line in File.ReadLines(designerPath))
            {
                if (ClassLine().Match(line) is { Success: true } m)
                {
                    return m.Groups["modifier"].Value;
                }
            }
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            return null;
        }

        return null;
    }

    [GeneratedRegex(@"^\s*(?<modifier>public|internal)\s+(?:(?:static|partial|sealed|abstract)\s+)*class\s+")]
    private static partial Regex ClassLine();

    private static bool IsValidIdentifier(string name)
    {
        if (name.Length == 0 || Keywords.Contains(name))
        {
            return false;
        }

        if (!(char.IsLetter(name[0]) || name[0] == '_'))
        {
            return false;
        }

        for (var i = 1; i < name.Length; i++)
        {
            var c = name[i];
            if (!(char.IsLetterOrDigit(c) || c == '_' || CharUnicodeInfo.GetUnicodeCategory(c) is UnicodeCategory.NonSpacingMark or UnicodeCategory.SpacingCombiningMark or UnicodeCategory.ConnectorPunctuation or UnicodeCategory.Format))
            {
                return false;
            }
        }

        return true;
    }

    /// <summary>The entries of the file in the generator's order: sorted by key ignoring case, one member per name.</summary>
    private static List<Entry> Read(string resxPath)
    {
        XDocument document;
        using (var stream = File.OpenRead(resxPath))
        using (var reader = new XmlTextReader(stream) { DtdProcessing = DtdProcessing.Prohibit, Normalization = false, WhitespaceHandling = WhitespaceHandling.None })
        {
            // Normalization off keeps a CRLF inside a value, which the designer's summary carries as Visual Studio's does.
            document = XDocument.Load(reader);
        }

        var directory = Path.GetDirectoryName(Path.GetFullPath(resxPath))!;
        var raw = new List<(string Key, Kind Kind, string Value, string TypeName)>();
        foreach (var data in document.Root?.Elements("data") ?? [])
        {
            var key = (string?)data.Attribute("name");
            if (string.IsNullOrEmpty(key) || key.StartsWith('$') || key.StartsWith(">>", StringComparison.Ordinal))
            {
                continue;
            }

            var type = (string?)data.Attribute("type");
            var mimetype = (string?)data.Attribute("mimetype");
            var value = data.Element("value")?.Value ?? string.Empty;
            var typeName = type is null ? null : type.Split(',')[0].Trim();
            if (typeName == "System.Resources.ResXFileRef")
            {
                var parts = value.Split(';');
                typeName = parts.Length > 1 ? parts[1].Split(',')[0].Trim() : "object";
                if (typeName == "System.String")
                {
                    value = ReadFileRef(directory, parts);
                }
            }

            if ((type is null && mimetype is null) || (typeName is not null && typeName.StartsWith("System.String", StringComparison.Ordinal)))
            {
                raw.Add((key, Kind.String, value, "System.String"));
            }
            else if (typeName is "System.IO.MemoryStream" or "System.IO.UnmanagedMemoryStream")
            {
                raw.Add((key, Kind.Stream, value, "System.IO.UnmanagedMemoryStream"));
            }
            else
            {
                raw.Add((key, Kind.Object, value, typeName ?? "object"));
            }
        }

        raw.Sort((a, b) => StringComparer.InvariantCultureIgnoreCase.Compare(a.Key, b.Key));
        var names = new HashSet<string>(StringComparer.Ordinal);
        var entries = new List<Entry>(raw.Count);
        foreach (var (key, kind, value, typeName) in raw)
        {
            if (MakeIdentifier(key) is { } name && names.Add(name))
            {
                entries.Add(new Entry(key, name, kind, value, typeName));
            }
        }

        return entries;
    }

    /// <summary>A text file's contents, for the summary of a <c>ResXFileRef</c> string entry; empty when unreadable.</summary>
    private static string ReadFileRef(string directory, string[] parts)
    {
        try
        {
            var file = Path.Combine(directory, parts[0].Trim().Replace('\\', Path.DirectorySeparatorChar));
            var encoding = parts.Length > 2 && parts[2].Trim().Length > 0 ? Encoding.GetEncoding(parts[2].Trim()) : null;
            return encoding is null ? File.ReadAllText(file) : File.ReadAllText(file, encoding);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or ArgumentException or NotSupportedException)
        {
            return string.Empty;
        }
    }

    private static string Truncate(string value) =>
        value.Length > DocCommentLengthThreshold ? value[..DocCommentLengthThreshold] + " [rest of string was truncated]\";" : value;

    private static string Escape(string value) => SecurityElement.Escape(value);

    /// <summary>CodeDom's doc comment: each line break continues the comment with the indent and <c>///</c>, no space after.</summary>
    private static void AppendComment(StringBuilder sb, string text)
    {
        for (var i = 0; i < text.Length; i++)
        {
            var c = text[i];
            if (c == '\u0000')
            {
                continue;
            }

            sb.Append(c);
            if (c == '\r')
            {
                if (i < text.Length - 1 && text[i + 1] == '\n')
                {
                    sb.Append('\n');
                    i++;
                }

                sb.Append("        ///");
            }
            else if (c == '\n')
            {
                sb.Append("        ///");
            }
            else if (c is '\u2028' or '\u2029' or '\u0085')
            {
                sb.Append("///");
            }
        }
    }

    /// <summary>A runtime type name as CodeDom writes it: primitives by keyword, arrays with their rank.</summary>
    private static string CodeTypeName(string typeName)
    {
        var bracket = typeName.IndexOf('[', StringComparison.Ordinal);
        var element = bracket < 0 ? typeName : typeName[..bracket];
        var suffix = bracket < 0 ? string.Empty : typeName[bracket..];
        return PrimitiveNames.TryGetValue(element, out var keyword) ? keyword + suffix : typeName;
    }

    /// <summary>A C# string literal.</summary>
    private static string Quote(string value)
    {
        var sb = new StringBuilder(value.Length + 2).Append('"');
        foreach (var c in value)
        {
            switch (c)
            {
                case '\\':
                    sb.Append("\\\\");
                    break;
                case '"':
                    sb.Append("\\\"");
                    break;
                case '\r':
                    sb.Append("\\r");
                    break;
                case '\n':
                    sb.Append("\\n");
                    break;
                case '\t':
                    sb.Append("\\t");
                    break;
                case '\0':
                    sb.Append("\\0");
                    break;
                case '\u2028':
                    sb.Append("\\u2028");
                    break;
                case '\u2029':
                    sb.Append("\\u2029");
                    break;
                default:
                    sb.Append(c);
                    break;
            }
        }

        return sb.Append('"').ToString();
    }
}
