using System.Text;
using System.Text.Json;
using Eludite.Host.Resources;
using Eludite.Host.Rpc;
using Nerdbank.Streams;
using StreamJsonRpc;

namespace Eludite.Host.Tests;

/// <summary>
/// Proposal 0005: <c>eludite/resx/sets</c> and <c>eludite/resx/designer</c> on <c>corpus/resx</c> (copied per test):
/// the sets of the SDK and legacy solutions with their metadata, every designer file regenerated byte for byte, a new
/// key in sorted position, the access modifier edit of the project file, the generation rule and the wire.
/// </summary>
public sealed class ResxTests : IDisposable
{
    private readonly ProjectCorpus _corpus = new("resx");

    private static CancellationToken Ct => TestContext.Current.CancellationToken;

    public void Dispose() => _corpus.Dispose();

    [Fact]
    public async Task Sets_ListsTheSdkSolutionsSetsWithTheirMetadata()
    {
        using var service = Service(_corpus.Path("Corpus.slnx"), out _);
        var result = await service.SetsAsync(new ResxSetsParams(1, null), Ct);
        Assert.Equal(1, result.Generation);
        Assert.Null(result.Skipped);
        Assert.Equal(2, result.Sets.Count);

        var messages = result.Sets[0];
        Assert.Equal(_corpus.Path("Public/Public.csproj"), messages.Project);
        Assert.Equal("Public", messages.ProjectName);
        Assert.Equal("sdk", messages.Kind);
        Assert.Equal(_corpus.Path("Public/Messages.resx"), messages.Path);
        Assert.Equal("Messages", messages.BaseName);
        Assert.Null(messages.NeutralLanguage);
        Assert.Equal("Corpus.Public", messages.RootNamespace);
        Assert.Equal([new ResxCulture("es", _corpus.Path("Public/Messages.es.resx"), true)], messages.Cultures);
        Assert.Equal("PublicResXFileCodeGenerator", messages.Generator);
        Assert.Equal("Corpus.Shared", messages.CustomToolNamespace);
        Assert.Equal("Messages.Designer.cs", messages.LastGenOutput);
        Assert.Equal(_corpus.Path("Public/Messages.Designer.cs"), messages.Designer);
        Assert.Equal("public", messages.AccessModifier);
        Assert.Equal("Corpus.Public.Messages", messages.ManifestName);
        Assert.Equal("Corpus.Shared", messages.Namespace);

        var strings = result.Sets[1];
        Assert.Equal(_corpus.Path("Strings/Strings.csproj"), strings.Project);
        Assert.Equal("Strings", strings.ProjectName);
        Assert.Equal("sdk", strings.Kind);
        Assert.Equal(_corpus.Path("Strings/Properties/Resources.resx"), strings.Path);
        Assert.Equal("Resources", strings.BaseName);
        Assert.Equal("en-US", strings.NeutralLanguage);
        Assert.Equal("Corpus.Strings", strings.RootNamespace);
        Assert.Equal(
            [
                new ResxCulture("de", _corpus.Path("Strings/Properties/Resources.de.resx"), true),
                new ResxCulture("fr-FR", _corpus.Path("Strings/Properties/Resources.fr-FR.resx"), true),
            ],
            strings.Cultures);
        Assert.Equal("ResXFileCodeGenerator", strings.Generator);
        Assert.Null(strings.CustomToolNamespace);
        Assert.Equal("Resources.Designer.cs", strings.LastGenOutput);
        Assert.Equal(_corpus.Path("Strings/Properties/Resources.Designer.cs"), strings.Designer);
        Assert.Equal("internal", strings.AccessModifier);
        Assert.Equal("Corpus.Strings.Properties.Resources", strings.ManifestName);
        Assert.Equal("Corpus.Strings.Properties", strings.Namespace);

        // Cached per generation; a project filter answers its project only.
        Assert.Equal(2, service.Evaluations);
        var one = await service.SetsAsync(new ResxSetsParams(1, [_corpus.Path("Strings/Strings.csproj")]), Ct);
        Assert.Equal([strings], one.Sets);
        Assert.Equal(2, service.Evaluations);
        var bad = await Assert.ThrowsAsync<LocalRpcException>(() => service.SetsAsync(new ResxSetsParams(1, [_corpus.Path("Legacy/Legacy.csproj")]), Ct));
        Assert.Equal(HostErrors.InvalidParams, bad.ErrorCode);
    }

    [Fact]
    public async Task Sets_ListsTheLegacyProjectsExplicitItems()
    {
        using var service = Service(_corpus.Path("Legacy.slnx"), out _);
        var result = await service.SetsAsync(new ResxSetsParams(1, null), Ct);
        Assert.Null(result.Skipped);
        Assert.Equal(
            [_corpus.Path("Legacy/Default.aspx.resx"), _corpus.Path("Legacy/Form1.resx"), _corpus.Path("Legacy/Properties/Resources.resx")],
            result.Sets.Select(s => s.Path));
        Assert.All(result.Sets, s => Assert.Equal(("legacy", "Legacy", "Corpus.Legacy"), (s.Kind, s.ProjectName, s.RootNamespace)));

        var aspx = result.Sets[0];
        Assert.Equal("Default.aspx", aspx.BaseName);
        Assert.Empty(aspx.Cultures);
        Assert.Null(aspx.Generator);
        Assert.Null(aspx.Designer);
        Assert.Equal("none", aspx.AccessModifier);
        Assert.Equal("Corpus.Legacy.Default.aspx", aspx.ManifestName);
        Assert.Equal("Corpus.Legacy", aspx.Namespace);

        var form = result.Sets[1];
        Assert.Equal("Form1", form.BaseName);
        Assert.Null(form.Generator);
        Assert.Equal("none", form.AccessModifier);
        Assert.Equal("Corpus.Legacy.Form1", form.ManifestName);

        var resources = result.Sets[2];
        Assert.Equal([new ResxCulture("de", _corpus.Path("Legacy/Properties/Resources.de.resx"), true)], resources.Cultures);
        Assert.Equal("ResXFileCodeGenerator", resources.Generator);
        Assert.Equal("internal", resources.AccessModifier);
        Assert.Equal(_corpus.Path("Legacy/Properties/Resources.Designer.cs"), resources.Designer);
        Assert.Equal("Corpus.Legacy.Properties.Resources", resources.ManifestName);
        Assert.Equal("Corpus.Legacy.Properties", resources.Namespace);

        // A culture file beside the neutral file that no item lists is reported with item false.
        File.Copy(_corpus.Path("Legacy/Properties/Resources.de.resx"), _corpus.Path("Legacy/Properties/Resources.fr.resx"));
        using var again = Service(_corpus.Path("Legacy.slnx"), out _);
        var beside = (await again.SetsAsync(new ResxSetsParams(1, null), Ct)).Sets[2];
        Assert.Equal([("de", true), ("fr", false)], beside.Cultures.Select(c => (c.Name, c.Item)));
    }

    [Theory]
    [InlineData("Corpus.slnx", "Strings/Properties/Resources.resx", "Strings/Properties/Resources.Designer.cs", "Resources", "Corpus.Strings.Properties", "internal")]
    [InlineData("Corpus.slnx", "Public/Messages.resx", "Public/Messages.Designer.cs", "Messages", "Corpus.Shared", "public")]
    [InlineData("Legacy.slnx", "Legacy/Properties/Resources.resx", "Legacy/Properties/Resources.Designer.cs", "Resources", "Corpus.Legacy.Properties", "internal")]
    public async Task Generate_ReproducesTheCheckedInDesignerBytes(string solution, string resx, string designer, string className, string ns, string modifier)
    {
        var expected = _corpus.Bytes(designer);
        File.Delete(_corpus.Path(designer));
        using var service = Service(_corpus.Path(solution), out _);

        var written = await service.DesignerAsync(new ResxDesignerParams(1, _corpus.Path(resx), "generate"), Ct);
        Assert.Equal(("written", modifier, _corpus.Path(designer), className, ns, 1L), (written.Status, written.Modifier, written.Designer, written.ClassName, written.Namespace, written.Generation));
        Assert.False(written.ProjectWritten);
        var actual = _corpus.Bytes(designer);
        Assert.True(expected.AsSpan().SequenceEqual(actual), Diff(expected, actual));

        var unchanged = await service.DesignerAsync(new ResxDesignerParams(1, _corpus.Path(resx), "generate"), Ct);
        Assert.Equal("unchanged", unchanged.Status);
        Assert.True(expected.AsSpan().SequenceEqual(_corpus.Bytes(designer)));
    }

    [Fact]
    public async Task Generate_AddsANewKeyInSortedPosition()
    {
        var resx = _corpus.Path("Strings/Properties/Resources.resx");
        var text = File.ReadAllText(resx);
        File.WriteAllText(resx, text.Replace("</root>", "  <data name=\"New Key\" xml:space=\"preserve\">\r\n    <value>n</value>\r\n  </data>\r\n</root>", StringComparison.Ordinal), new UTF8Encoding(true));
        using var service = Service(_corpus.Path("Corpus.slnx"), out _);

        var result = await service.DesignerAsync(new ResxDesignerParams(1, resx, "generate"), Ct);
        Assert.Equal("written", result.Status);
        var designer = _corpus.Text("Strings/Properties/Resources.Designer.cs");
        var multi = designer.IndexOf("internal static string Multi {", StringComparison.Ordinal);
        var newKey = designer.IndexOf("internal static string New_Key {", StringComparison.Ordinal);
        var save = designer.IndexOf("internal static string Save {", StringComparison.Ordinal);
        Assert.True(multi > 0 && multi < newKey && newKey < save, $"Multi {multi}, New_Key {newKey}, Save {save}");
        Assert.Contains("        ///   Looks up a localized string similar to n.\r\n        /// </summary>\r\n        internal static string New_Key {\r\n            get {\r\n                return ResourceManager.GetString(\"New Key\", resourceCulture);", designer, StringComparison.Ordinal);
        Assert.DoesNotContain("\n\n", designer, StringComparison.Ordinal);
    }

    [Fact]
    public async Task SetModifier_EditsTheGeneratorMetadataOnly_RegeneratesTheDesigner_AndNoneRemovesBoth()
    {
        var project = _corpus.Path("Strings/Strings.csproj");
        var resx = _corpus.Path("Strings/Properties/Resources.resx");
        var designer = _corpus.Path("Strings/Properties/Resources.Designer.cs");
        var projectBytes = _corpus.Bytes("Strings/Strings.csproj");
        var designerText = _corpus.Text("Strings/Properties/Resources.Designer.cs");
        var reloaded = new List<string>();
        using var service = Service(_corpus.Path("Corpus.slnx"), out var state, reloaded);

        var missing = await Assert.ThrowsAsync<LocalRpcException>(() => service.DesignerAsync(new ResxDesignerParams(1, resx, "setModifier"), Ct));
        Assert.Equal(HostErrors.InvalidParams, missing.ErrorCode);

        var @public = await service.DesignerAsync(new ResxDesignerParams(1, resx, "setModifier") { Modifier = "public" }, Ct);
        Assert.Equal(("written", "public", true, 2L, designer), (@public.Status, @public.Modifier, @public.ProjectWritten, @public.Generation, @public.Designer));
        Assert.Equal([_corpus.Path("Corpus.slnx")], reloaded);
        Assert.Equal(2, state.Generation);
        var expectedProject = Encoding.UTF8.GetString(projectBytes).Replace("<Generator>ResXFileCodeGenerator</Generator>", "<Generator>PublicResXFileCodeGenerator</Generator>", StringComparison.Ordinal);
        Assert.Equal(expectedProject, Encoding.UTF8.GetString(_corpus.Bytes("Strings/Strings.csproj")));
        Assert.Equal(projectBytes.Length + "Public".Length, _corpus.Bytes("Strings/Strings.csproj").Length);
        var expectedDesigner = designerText.Replace("internal class Resources", "public class Resources", StringComparison.Ordinal).Replace("internal static", "public static", StringComparison.Ordinal);
        Assert.Equal(expectedDesigner, _corpus.Text("Strings/Properties/Resources.Designer.cs"));
        Assert.Contains("        internal Resources() {", _corpus.Text("Strings/Properties/Resources.Designer.cs"), StringComparison.Ordinal);

        var sets = await service.SetsAsync(new ResxSetsParams(2, [project]), Ct);
        Assert.Equal(("PublicResXFileCodeGenerator", "public"), (sets.Sets.Single().Generator, sets.Sets.Single().AccessModifier));

        // The same modifier again changes nothing.
        var same = await service.DesignerAsync(new ResxDesignerParams(2, resx, "setModifier") { Modifier = "public" }, Ct);
        Assert.Equal(("unchanged", false, 2L), (same.Status, same.ProjectWritten, same.Generation));
        Assert.Single(reloaded);

        var none = await service.DesignerAsync(new ResxDesignerParams(2, resx, "setModifier") { Modifier = "none" }, Ct);
        Assert.Equal(("deleted", "none", true, 3L), (none.Status, none.Modifier, none.ProjectWritten, none.Generation));
        Assert.False(File.Exists(designer));
        var text = _corpus.Text("Strings/Strings.csproj");
        Assert.DoesNotContain("Generator", text, StringComparison.Ordinal);
        Assert.DoesNotContain("LastGenOutput", text, StringComparison.Ordinal);
        Assert.DoesNotContain("Resources.Designer.cs", text, StringComparison.Ordinal);
        Assert.Contains("    <NeutralLanguage>en-US</NeutralLanguage>\n", text, StringComparison.Ordinal);
        var after = (await service.SetsAsync(new ResxSetsParams(3, [project]), Ct)).Sets.Single();
        Assert.Equal((null, null, "none"), (after.Generator, after.Designer, after.AccessModifier));

        // Without a Generator and a designer, generate takes the modifier asked for; none writes nothing.
        var skipped = await service.DesignerAsync(new ResxDesignerParams(3, resx, "generate") { Modifier = "none" }, Ct);
        Assert.Equal(("none", "none"), (skipped.Status, skipped.Modifier));
        Assert.False(File.Exists(designer));
        var asked = await service.DesignerAsync(new ResxDesignerParams(3, resx, "generate") { Modifier = "public" }, Ct);
        Assert.Equal(("written", "public", 3L), (asked.Status, asked.Modifier, asked.Generation));
        Assert.Equal(expectedDesigner, _corpus.Text("Strings/Properties/Resources.Designer.cs"));
        var deleted = await service.DesignerAsync(new ResxDesignerParams(3, resx, "delete"), Ct);
        Assert.Equal(("deleted", "none"), (deleted.Status, deleted.Modifier));
        Assert.False(File.Exists(designer));
        Assert.Equal("none", (await service.DesignerAsync(new ResxDesignerParams(3, resx, "delete"), Ct)).Status);
    }

    [Fact]
    public async Task SetModifier_AddsTheItemsALegacyProjectLacks()
    {
        var project = _corpus.Path("Legacy/Legacy.csproj");
        var resx = _corpus.Path("Legacy/Default.aspx.resx");
        using var service = Service(_corpus.Path("Legacy.slnx"), out _);
        var result = await service.DesignerAsync(new ResxDesignerParams(1, resx, "setModifier") { Modifier = "internal" }, Ct);
        Assert.Equal(("written", "internal", true, "Default_aspx", "Corpus.Legacy"), (result.Status, result.Modifier, result.ProjectWritten, result.ClassName, result.Namespace));
        Assert.Equal(_corpus.Path("Legacy/Default.aspx.Designer.cs"), result.Designer);
        var text = _corpus.Text("Legacy/Legacy.csproj");
        Assert.Contains("    <EmbeddedResource Include=\"Default.aspx.resx\">\r\n      <DependentUpon>Default.aspx</DependentUpon>\r\n      <Generator>ResXFileCodeGenerator</Generator>\r\n      <LastGenOutput>Default.aspx.Designer.cs</LastGenOutput>\r\n    </EmbeddedResource>", text, StringComparison.Ordinal);
        Assert.Contains("    <Compile Include=\"Default.aspx.Designer.cs\">\r\n      <AutoGen>True</AutoGen>\r\n      <DesignTime>True</DesignTime>\r\n      <DependentUpon>Default.aspx.resx</DependentUpon>\r\n    </Compile>", text, StringComparison.Ordinal);
        var designer = _corpus.Text("Legacy/Default.aspx.Designer.cs");
        Assert.Contains("namespace Corpus.Legacy {", designer, StringComparison.Ordinal);
        Assert.Contains("    internal class Default_aspx {", designer, StringComparison.Ordinal);
        Assert.Contains("new global::System.Resources.ResourceManager(\"Corpus.Legacy.Default.aspx\", typeof(Default_aspx).Assembly)", designer, StringComparison.Ordinal);
    }

    [Fact]
    public async Task Service_RefusesAStaleGeneration_AndAnUnknownFile()
    {
        using var service = Service(_corpus.Path("Corpus.slnx"), out var state);
        state.Generation = 5;
        var resx = _corpus.Path("Strings/Properties/Resources.resx");

        var sets = await Assert.ThrowsAsync<LocalRpcException>(() => service.SetsAsync(new ResxSetsParams(4, null), Ct));
        Assert.Equal(HostErrors.ContentModified, sets.ErrorCode);
        var designer = await Assert.ThrowsAsync<LocalRpcException>(() => service.DesignerAsync(new ResxDesignerParams(4, resx, "generate"), Ct));
        Assert.Equal(HostErrors.ContentModified, designer.ErrorCode);
        var missing = await Assert.ThrowsAsync<LocalRpcException>(() => service.SetsAsync(new ResxSetsParams(null, null), Ct));
        Assert.Equal(HostErrors.InvalidParams, missing.ErrorCode);
        var relative = await Assert.ThrowsAsync<LocalRpcException>(() => service.DesignerAsync(new ResxDesignerParams(5, "Resources.resx", "generate"), Ct));
        Assert.Equal(HostErrors.InvalidParams, relative.ErrorCode);

        // A file no project lists: none.
        var none = await service.DesignerAsync(new ResxDesignerParams(5, _corpus.Path("Legacy/Properties/Resources.resx"), "generate"), Ct);
        Assert.Equal(("none", "none", 5L), (none.Status, none.Modifier, none.Generation));

        // A culture file names its set.
        var byCulture = await service.DesignerAsync(new ResxDesignerParams(5, _corpus.Path("Strings/Properties/Resources.de.resx"), "generate"), Ct);
        Assert.Equal(("unchanged", resx), (byCulture.Status, byCulture.Path));

        // The generation moving on makes a request in flight ContentModified (a cached answer is kept: it is the generation's).
        using var fresh = Service(_corpus.Path("Corpus.slnx"), out var moving);
        await moving.Changed.CancelAsync();
        var moved = await Assert.ThrowsAsync<LocalRpcException>(() => fresh.SetsAsync(new ResxSetsParams(1, null), Ct));
        Assert.Equal(HostErrors.ContentModified, moved.ErrorCode);
    }

    [Fact]
    public async Task Wire_SetsFollowsTheGenerationRule()
    {
        var (clientStream, serverStream) = FullDuplexStream.CreatePair();
        var target = new HostRpcTarget(new FakeSdkDiscoverer(), TextWriter.Null);
        var server = HostServer.RunAsync(serverStream, serverStream, target);
        using var client = TestRpc.Create(clientStream);
        client.StartListening();

        var (code, _) = await TestRpc.ErrorOfAsync(() => client.InvokeWithParameterObjectAsync<JsonElement>("eludite/resx/sets", new { generation = 0 }, Ct));
        Assert.Equal(HostErrors.ServerNotInitialized, code);
        await client.InvokeWithParameterObjectAsync<JsonElement>("eludite/host/initialize", new { clientName = "test", clientVersion = "0" }, Ct);
        var open = await client.InvokeWithParameterObjectAsync<JsonElement>("eludite/solution/open", new { path = _corpus.Path("Corpus.slnx") }, Ct);
        var generation = open.GetProperty("generation").GetInt64();

        (code, var data) = await TestRpc.ErrorOfAsync(() => client.InvokeWithParameterObjectAsync<JsonElement>("eludite/resx/sets", new { generation = generation - 1 }, Ct));
        Assert.Equal(HostErrors.ContentModified, code);
        Assert.Equal(generation, data!.Value.GetProperty("currentGeneration").GetInt64());

        var sets = await client.InvokeWithParameterObjectAsync<JsonElement>("eludite/resx/sets", new { generation }, Ct);
        Assert.Equal(generation, sets.GetProperty("generation").GetInt64());
        Assert.False(sets.TryGetProperty("skipped", out _));
        var strings = sets.GetProperty("sets").EnumerateArray().Single(s => s.GetProperty("baseName").GetString() == "Resources");
        Assert.Equal("en-US", strings.GetProperty("neutralLanguage").GetString());
        Assert.Equal(["de", "fr-FR"], strings.GetProperty("cultures").EnumerateArray().Select(c => c.GetProperty("name").GetString()));
        Assert.True(strings.GetProperty("cultures")[0].GetProperty("item").GetBoolean());
        Assert.Equal("internal", strings.GetProperty("accessModifier").GetString());
        Assert.Equal("Corpus.Strings.Properties.Resources", strings.GetProperty("manifestName").GetString());
        Assert.Equal("Corpus.Strings.Properties", strings.GetProperty("namespace").GetString());
        var messages = sets.GetProperty("sets").EnumerateArray().Single(s => s.GetProperty("baseName").GetString() == "Messages");
        Assert.False(messages.TryGetProperty("neutralLanguage", out _));
        Assert.Equal("Corpus.Shared", messages.GetProperty("customToolNamespace").GetString());

        var designer = await client.InvokeWithParameterObjectAsync<JsonElement>("eludite/resx/designer", new { generation, path = _corpus.Path("Public/Messages.resx"), action = "generate" }, Ct);
        Assert.Equal("unchanged", designer.GetProperty("status").GetString());
        Assert.False(designer.TryGetProperty("projectWritten", out _));
        Assert.Equal("Messages", designer.GetProperty("className").GetString());

        client.Dispose();
        await server.WaitAsync(TimeSpan.FromSeconds(10), Ct);
    }

    private sealed class State
    {
        public long Generation { get; set; } = 1;

        public CancellationTokenSource Changed { get; } = new();
    }

    private static ResxService Service(string solution, out State state, List<string>? reloaded = null)
    {
        var s = new State();
        state = s;
        return new ResxService(
            () => (s.Generation, solution, s.Changed.Token),
            () => s.Generation,
            path =>
            {
                reloaded?.Add(path);
                return ++s.Generation;
            },
            TextWriter.Null);
    }

    private static string Diff(byte[] expected, byte[] actual)
    {
        var i = 0;
        while (i < expected.Length && i < actual.Length && expected[i] == actual[i])
        {
            i++;
        }

        var from = Math.Max(0, i - 60);
        static string Show(byte[] b, int from, int at) => Encoding.UTF8.GetString(b, from, Math.Min(b.Length, at + 60) - from).Replace("\r", "\\r", StringComparison.Ordinal).Replace("\n", "\\n\n", StringComparison.Ordinal);
        return $"differs at byte {i} (expected {expected.Length} bytes, actual {actual.Length}):\n--- expected\n{Show(expected, from, i)}\n--- actual\n{Show(actual, from, i)}";
    }
}
