//! Eludite's `.resx` model (proposal 0005, PLAN.md 4.11): what the `.resx` editor, `eludite.resx.*` and the host's
//! designer generation agree on, with nothing of the shell, the command bus or the host in it.
//!
//! - **A file** ([`ResxFile`]) is parsed with `roxmltree`, keeping each `data` element's byte ranges, into its string
//!   entries (no `type` and no `mimetype`, or a `System.String` type) and its other entries (files through
//!   `ResXFileRef`, binary data, WinForms designer state named `>>...` or `$this...`), which are listed with their
//!   type and never edited. The header (`xsd:schema`, `resheader`, `assembly`), comments and whitespace are opaque
//!   bytes.
//! - **Edits are splices** ([`Splice`]): a changed value or comment replaces exactly that element's text, escaped as
//!   XML needs; a new entry is appended after the last element in the file's indentation and Visual Studio's shape; a
//!   removed entry takes the line it sat on with it; a renamed one changes the `name` attribute. Every untouched byte
//!   survives: [`ResxFile::apply`] gives the new text and the proving test is a byte-for-byte round trip.
//! - **Cultures** ([`cultures::CULTURES`], generated by `tools/resx-cultures/generate.sh`): `Name.<suffix>.resx` is a
//!   culture file only when the suffix is a .NET culture name, so `Default.aspx.resx` is a neutral file.
//! - **A set** ([`ResourceSet`]) is a neutral file with the culture files beside it ([`set_files`] from any of them,
//!   [`discover`] over a folder), and its [`rows`](ResourceSet::rows) are the editor's grid: a key with one
//!   [`Cell`] per culture, the invariant mark (the `{Invariant}` comment marker the ResX Resource Manager extension
//!   stores) and the rule warnings.
//! - **Rules** ([`rules`]): the extension's consistency checks between a translation and its neutral value
//!   (placeholders, punctuation, white space, untranslated), each switchable; a violation is a [`Warning`], never a
//!   refusal.
//!
//! The boundary: paths in and out are as the caller gave them; nothing here reads settings or writes files except
//! [`discover`] and [`set_files`], which only read directories.

pub mod cultures;
mod file;
pub mod rules;
mod set;

pub use file::{
    Encoding, Entry, EntryKind, ParseError, ResxFile, Splice, TEMPLATE, apply, escape_text,
};
pub use rules::{Rule, Rules, Warning};
pub use set::{
    Cell, INVARIANT_MARKER, LoadError, ResourceSet, Row, SetFiles, base_name, canonical_culture,
    discover, has_invariant, is_culture, set_files, with_invariant,
};
