// Generated by eludite-cdp-generator from devtools-protocol 0.0.1709723 (protocol/cdp/PIN). Do not edit:
// change the generator or the pin and run `cargo run -p eludite-cdp-generator`.
//! The CDP domain `Accessibility`.
//!
//! **Experimental.**

#![allow(
    clippy::upper_case_acronyms,
    clippy::doc_lazy_continuation,
    clippy::doc_overindented_list_items,
    clippy::large_enum_variant,
    clippy::empty_docs,
    clippy::struct_excessive_bools,
    rustdoc::bare_urls,
    rustdoc::broken_intra_doc_links,
    rustdoc::invalid_html_tags,
    rustdoc::invalid_rust_codeblocks
)]

use serde::{Deserialize, Serialize};

/// Unique accessibility node identifier.
pub type AXNodeId = String;

/// Enum of possible property types.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum AXValueType {
    /// `boolean`
    Boolean,
    /// `tristate`
    Tristate,
    /// `booleanOrUndefined`
    BooleanOrUndefined,
    /// `idref`
    Idref,
    /// `idrefList`
    IdrefList,
    /// `integer`
    Integer,
    /// `node`
    Node,
    /// `nodeList`
    NodeList,
    /// `number`
    Number,
    /// `string`
    String,
    /// `computedString`
    ComputedString,
    /// `token`
    Token,
    /// `tokenList`
    TokenList,
    /// `domRelation`
    DomRelation,
    /// `role`
    Role,
    /// `internalRole`
    InternalRole,
    /// `valueUndefined`
    ValueUndefined,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    AXValueType {
        Boolean => "boolean",
        Tristate => "tristate",
        BooleanOrUndefined => "booleanOrUndefined",
        Idref => "idref",
        IdrefList => "idrefList",
        Integer => "integer",
        Node => "node",
        NodeList => "nodeList",
        Number => "number",
        String => "string",
        ComputedString => "computedString",
        Token => "token",
        TokenList => "tokenList",
        DomRelation => "domRelation",
        Role => "role",
        InternalRole => "internalRole",
        ValueUndefined => "valueUndefined",
    }
}

/// Enum of possible property sources.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum AXValueSourceType {
    /// `attribute`
    Attribute,
    /// `implicit`
    Implicit,
    /// `style`
    Style,
    /// `contents`
    Contents,
    /// `placeholder`
    Placeholder,
    /// `relatedElement`
    RelatedElement,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    AXValueSourceType {
        Attribute => "attribute",
        Implicit => "implicit",
        Style => "style",
        Contents => "contents",
        Placeholder => "placeholder",
        RelatedElement => "relatedElement",
    }
}

/// Enum of possible native property sources (as a subtype of a particular AXValueSourceType).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum AXValueNativeSourceType {
    /// `description`
    Description,
    /// `figcaption`
    Figcaption,
    /// `label`
    Label,
    /// `labelfor`
    Labelfor,
    /// `labelwrapped`
    Labelwrapped,
    /// `legend`
    Legend,
    /// `rubyannotation`
    Rubyannotation,
    /// `tablecaption`
    Tablecaption,
    /// `title`
    Title,
    /// `other`
    OtherValue,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    AXValueNativeSourceType {
        Description => "description",
        Figcaption => "figcaption",
        Label => "label",
        Labelfor => "labelfor",
        Labelwrapped => "labelwrapped",
        Legend => "legend",
        Rubyannotation => "rubyannotation",
        Tablecaption => "tablecaption",
        Title => "title",
        OtherValue => "other",
    }
}

/// A single source for a computed AX property.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AXValueSource {
    /// What type of source this is.
    #[serde(rename = "type")]
    pub type_: AXValueSourceType,
    /// The value of this property source.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<AXValue>,
    /// The name of the relevant attribute, if any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attribute: Option<String>,
    /// The value of the relevant attribute, if any.
    #[serde(
        rename = "attributeValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub attribute_value: Option<AXValue>,
    /// Whether this source is superseded by a higher priority source.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub superseded: Option<bool>,
    /// The native markup source for this value, e.g. a `<label>` element.
    #[serde(
        rename = "nativeSource",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub native_source: Option<AXValueNativeSourceType>,
    /// The value, such as a node or node list, of the native source.
    #[serde(
        rename = "nativeSourceValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub native_source_value: Option<AXValue>,
    /// Whether the value for this property is invalid.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub invalid: Option<bool>,
    /// Reason for the value being invalid, if it is.
    #[serde(
        rename = "invalidReason",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub invalid_reason: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AXRelatedNode {
    /// The BackendNodeId of the related DOM node.
    #[serde(rename = "backendDOMNodeId")]
    pub backend_dom_node_id: super::dom::BackendNodeId,
    /// The IDRef value provided, if any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub idref: Option<String>,
    /// The text alternative of this node in the current context.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AXProperty {
    /// The name of this property.
    pub name: AXPropertyName,
    /// The value of this property.
    pub value: AXValue,
}

/// A single computed AX property.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AXValue {
    /// The type of this value.
    #[serde(rename = "type")]
    pub type_: AXValueType,
    /// The computed value of this property.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<serde_json::Value>,
    /// One or more related nodes, if applicable.
    #[serde(
        rename = "relatedNodes",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub related_nodes: Option<Vec<AXRelatedNode>>,
    /// The sources which contributed to the computation of this property.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sources: Option<Vec<AXValueSource>>,
}

/// Values of AXProperty name:
/// - from 'busy' to 'roledescription': states which apply to every AX node
/// - from 'live' to 'root': attributes which apply to nodes in live regions
/// - from 'autocomplete' to 'valuetext': attributes which apply to widgets
/// - from 'checked' to 'selected': states which apply to widgets
/// - from 'activedescendant' to 'owns': relationships between elements other than parent/child/sibling
/// - from 'activeFullscreenElement' to 'uninteresting': reasons why this noode is hidden
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum AXPropertyName {
    /// `actions`
    Actions,
    /// `busy`
    Busy,
    /// `disabled`
    Disabled,
    /// `editable`
    Editable,
    /// `focusable`
    Focusable,
    /// `focused`
    Focused,
    /// `hidden`
    Hidden,
    /// `hiddenRoot`
    HiddenRoot,
    /// `invalid`
    Invalid,
    /// `keyshortcuts`
    Keyshortcuts,
    /// `settable`
    Settable,
    /// `roledescription`
    Roledescription,
    /// `live`
    Live,
    /// `atomic`
    Atomic,
    /// `relevant`
    Relevant,
    /// `root`
    Root,
    /// `autocomplete`
    Autocomplete,
    /// `hasPopup`
    HasPopup,
    /// `level`
    Level,
    /// `multiselectable`
    Multiselectable,
    /// `orientation`
    Orientation,
    /// `multiline`
    Multiline,
    /// `readonly`
    Readonly,
    /// `required`
    Required,
    /// `valuemin`
    Valuemin,
    /// `valuemax`
    Valuemax,
    /// `valuetext`
    Valuetext,
    /// `checked`
    Checked,
    /// `expanded`
    Expanded,
    /// `modal`
    Modal,
    /// `pressed`
    Pressed,
    /// `selected`
    Selected,
    /// `activedescendant`
    Activedescendant,
    /// `controls`
    Controls,
    /// `describedby`
    Describedby,
    /// `details`
    Details,
    /// `errormessage`
    Errormessage,
    /// `flowto`
    Flowto,
    /// `labelledby`
    Labelledby,
    /// `owns`
    Owns,
    /// `url`
    Url,
    /// `activeFullscreenElement`
    ActiveFullscreenElement,
    /// `activeModalDialog`
    ActiveModalDialog,
    /// `activeAriaModalDialog`
    ActiveAriaModalDialog,
    /// `ariaHiddenElement`
    AriaHiddenElement,
    /// `ariaHiddenSubtree`
    AriaHiddenSubtree,
    /// `emptyAlt`
    EmptyAlt,
    /// `emptyText`
    EmptyText,
    /// `inertElement`
    InertElement,
    /// `inertSubtree`
    InertSubtree,
    /// `labelContainer`
    LabelContainer,
    /// `labelFor`
    LabelFor,
    /// `notRendered`
    NotRendered,
    /// `notVisible`
    NotVisible,
    /// `presentationalRole`
    PresentationalRole,
    /// `probablyPresentational`
    ProbablyPresentational,
    /// `inactiveCarouselTabContent`
    InactiveCarouselTabContent,
    /// `uninteresting`
    Uninteresting,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    AXPropertyName {
        Actions => "actions",
        Busy => "busy",
        Disabled => "disabled",
        Editable => "editable",
        Focusable => "focusable",
        Focused => "focused",
        Hidden => "hidden",
        HiddenRoot => "hiddenRoot",
        Invalid => "invalid",
        Keyshortcuts => "keyshortcuts",
        Settable => "settable",
        Roledescription => "roledescription",
        Live => "live",
        Atomic => "atomic",
        Relevant => "relevant",
        Root => "root",
        Autocomplete => "autocomplete",
        HasPopup => "hasPopup",
        Level => "level",
        Multiselectable => "multiselectable",
        Orientation => "orientation",
        Multiline => "multiline",
        Readonly => "readonly",
        Required => "required",
        Valuemin => "valuemin",
        Valuemax => "valuemax",
        Valuetext => "valuetext",
        Checked => "checked",
        Expanded => "expanded",
        Modal => "modal",
        Pressed => "pressed",
        Selected => "selected",
        Activedescendant => "activedescendant",
        Controls => "controls",
        Describedby => "describedby",
        Details => "details",
        Errormessage => "errormessage",
        Flowto => "flowto",
        Labelledby => "labelledby",
        Owns => "owns",
        Url => "url",
        ActiveFullscreenElement => "activeFullscreenElement",
        ActiveModalDialog => "activeModalDialog",
        ActiveAriaModalDialog => "activeAriaModalDialog",
        AriaHiddenElement => "ariaHiddenElement",
        AriaHiddenSubtree => "ariaHiddenSubtree",
        EmptyAlt => "emptyAlt",
        EmptyText => "emptyText",
        InertElement => "inertElement",
        InertSubtree => "inertSubtree",
        LabelContainer => "labelContainer",
        LabelFor => "labelFor",
        NotRendered => "notRendered",
        NotVisible => "notVisible",
        PresentationalRole => "presentationalRole",
        ProbablyPresentational => "probablyPresentational",
        InactiveCarouselTabContent => "inactiveCarouselTabContent",
        Uninteresting => "uninteresting",
    }
}

/// A node in the accessibility tree.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AXNode {
    /// Unique identifier for this node.
    #[serde(rename = "nodeId")]
    pub node_id: AXNodeId,
    /// Whether this node is ignored for accessibility
    pub ignored: bool,
    /// Collection of reasons why this node is hidden.
    #[serde(
        rename = "ignoredReasons",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub ignored_reasons: Option<Vec<AXProperty>>,
    /// This `Node`'s role, whether explicit or implicit.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role: Option<AXValue>,
    /// This `Node`'s Chrome raw role.
    #[serde(
        rename = "chromeRole",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub chrome_role: Option<AXValue>,
    /// The accessible name for this `Node`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<AXValue>,
    /// The accessible description for this `Node`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<AXValue>,
    /// The value for this `Node`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<AXValue>,
    /// All other properties
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub properties: Option<Vec<AXProperty>>,
    /// ID for this node's parent.
    #[serde(rename = "parentId", default, skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<AXNodeId>,
    /// IDs for each of this node's child nodes.
    #[serde(rename = "childIds", default, skip_serializing_if = "Option::is_none")]
    pub child_ids: Option<Vec<AXNodeId>>,
    /// The backend ID for the associated DOM node, if any.
    #[serde(
        rename = "backendDOMNodeId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub backend_dom_node_id: Option<super::dom::BackendNodeId>,
    /// The frame ID for the frame associated with this nodes document.
    #[serde(rename = "frameId", default, skip_serializing_if = "Option::is_none")]
    pub frame_id: Option<super::page::FrameId>,
}

/// Parameters of `Accessibility.disable`.
///
/// Disables the accessibility domain.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DisableParams {}

/// The answer to `Accessibility.disable`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DisableReturns {}

impl DisableParams {
    pub const METHOD: &'static str = "Accessibility.disable";
}

impl super::Command for DisableParams {
    const METHOD: &'static str = "Accessibility.disable";
    type Returns = DisableReturns;
}

/// Parameters of `Accessibility.enable`.
///
/// Enables the accessibility domain which causes `AXNodeId`s to remain consistent between method calls.
/// This turns on accessibility for the page, which can impact performance until accessibility is disabled.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EnableParams {}

/// The answer to `Accessibility.enable`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EnableReturns {}

impl EnableParams {
    pub const METHOD: &'static str = "Accessibility.enable";
}

impl super::Command for EnableParams {
    const METHOD: &'static str = "Accessibility.enable";
    type Returns = EnableReturns;
}

/// Parameters of `Accessibility.getPartialAXTree`.
///
/// Fetches the accessibility node and partial accessibility tree for this DOM node, if it exists.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetPartialAXTreeParams {
    /// Identifier of the node to get the partial accessibility tree for.
    #[serde(rename = "nodeId", default, skip_serializing_if = "Option::is_none")]
    pub node_id: Option<super::dom::NodeId>,
    /// Identifier of the backend node to get the partial accessibility tree for.
    #[serde(
        rename = "backendNodeId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub backend_node_id: Option<super::dom::BackendNodeId>,
    /// JavaScript object id of the node wrapper to get the partial accessibility tree for.
    #[serde(rename = "objectId", default, skip_serializing_if = "Option::is_none")]
    pub object_id: Option<super::runtime::RemoteObjectId>,
    /// Whether to fetch this node's ancestors, siblings and children. Defaults to true.
    #[serde(
        rename = "fetchRelatives",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub fetch_relatives: Option<bool>,
}

/// The answer to `Accessibility.getPartialAXTree`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetPartialAXTreeReturns {
    /// The `Accessibility.AXNode` for this DOM node, if it exists, plus its ancestors, siblings and
    /// children, if requested.
    pub nodes: Vec<AXNode>,
}

impl GetPartialAXTreeParams {
    pub const METHOD: &'static str = "Accessibility.getPartialAXTree";
}

impl super::Command for GetPartialAXTreeParams {
    const METHOD: &'static str = "Accessibility.getPartialAXTree";
    type Returns = GetPartialAXTreeReturns;
}

/// Parameters of `Accessibility.getFullAXTree`.
///
/// Fetches the entire accessibility tree for the root Document
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetFullAXTreeParams {
    /// The maximum depth at which descendants of the root node should be retrieved.
    /// If omitted, the full tree is returned.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub depth: Option<i64>,
    /// The frame for whose document the AX tree should be retrieved.
    /// If omitted, the root frame is used.
    #[serde(rename = "frameId", default, skip_serializing_if = "Option::is_none")]
    pub frame_id: Option<super::page::FrameId>,
}

/// The answer to `Accessibility.getFullAXTree`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetFullAXTreeReturns {
    pub nodes: Vec<AXNode>,
}

impl GetFullAXTreeParams {
    pub const METHOD: &'static str = "Accessibility.getFullAXTree";
}

impl super::Command for GetFullAXTreeParams {
    const METHOD: &'static str = "Accessibility.getFullAXTree";
    type Returns = GetFullAXTreeReturns;
}

/// Parameters of `Accessibility.getRootAXNode`.
///
/// Fetches the root node.
/// Requires `enable()` to have been called previously.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetRootAXNodeParams {
    /// The frame in whose document the node resides.
    /// If omitted, the root frame is used.
    #[serde(rename = "frameId", default, skip_serializing_if = "Option::is_none")]
    pub frame_id: Option<super::page::FrameId>,
}

/// The answer to `Accessibility.getRootAXNode`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetRootAXNodeReturns {
    pub node: AXNode,
}

impl GetRootAXNodeParams {
    pub const METHOD: &'static str = "Accessibility.getRootAXNode";
}

impl super::Command for GetRootAXNodeParams {
    const METHOD: &'static str = "Accessibility.getRootAXNode";
    type Returns = GetRootAXNodeReturns;
}

/// Parameters of `Accessibility.getAXNodeAndAncestors`.
///
/// Fetches a node and all ancestors up to and including the root.
/// Requires `enable()` to have been called previously.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAXNodeAndAncestorsParams {
    /// Identifier of the node to get.
    #[serde(rename = "nodeId", default, skip_serializing_if = "Option::is_none")]
    pub node_id: Option<super::dom::NodeId>,
    /// Identifier of the backend node to get.
    #[serde(
        rename = "backendNodeId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub backend_node_id: Option<super::dom::BackendNodeId>,
    /// JavaScript object id of the node wrapper to get.
    #[serde(rename = "objectId", default, skip_serializing_if = "Option::is_none")]
    pub object_id: Option<super::runtime::RemoteObjectId>,
}

/// The answer to `Accessibility.getAXNodeAndAncestors`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAXNodeAndAncestorsReturns {
    pub nodes: Vec<AXNode>,
}

impl GetAXNodeAndAncestorsParams {
    pub const METHOD: &'static str = "Accessibility.getAXNodeAndAncestors";
}

impl super::Command for GetAXNodeAndAncestorsParams {
    const METHOD: &'static str = "Accessibility.getAXNodeAndAncestors";
    type Returns = GetAXNodeAndAncestorsReturns;
}

/// Parameters of `Accessibility.getChildAXNodes`.
///
/// Fetches a particular accessibility node by AXNodeId.
/// Requires `enable()` to have been called previously.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetChildAXNodesParams {
    pub id: AXNodeId,
    /// The frame in whose document the node resides.
    /// If omitted, the root frame is used.
    #[serde(rename = "frameId", default, skip_serializing_if = "Option::is_none")]
    pub frame_id: Option<super::page::FrameId>,
}

/// The answer to `Accessibility.getChildAXNodes`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetChildAXNodesReturns {
    pub nodes: Vec<AXNode>,
}

impl GetChildAXNodesParams {
    pub const METHOD: &'static str = "Accessibility.getChildAXNodes";
}

impl super::Command for GetChildAXNodesParams {
    const METHOD: &'static str = "Accessibility.getChildAXNodes";
    type Returns = GetChildAXNodesReturns;
}

/// Parameters of `Accessibility.queryAXTree`.
///
/// Query a DOM node's accessibility subtree for accessible name and role.
/// This command computes the name and role for all nodes in the subtree, including those that are
/// ignored for accessibility, and returns those that match the specified name and role. If no DOM
/// node is specified, or the DOM node does not exist, the command returns an error. If neither
/// `accessibleName` or `role` is specified, it returns all the accessibility nodes in the subtree.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct QueryAXTreeParams {
    /// Identifier of the node for the root to query.
    #[serde(rename = "nodeId", default, skip_serializing_if = "Option::is_none")]
    pub node_id: Option<super::dom::NodeId>,
    /// Identifier of the backend node for the root to query.
    #[serde(
        rename = "backendNodeId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub backend_node_id: Option<super::dom::BackendNodeId>,
    /// JavaScript object id of the node wrapper for the root to query.
    #[serde(rename = "objectId", default, skip_serializing_if = "Option::is_none")]
    pub object_id: Option<super::runtime::RemoteObjectId>,
    /// Find nodes with this computed name.
    #[serde(
        rename = "accessibleName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub accessible_name: Option<String>,
    /// Find nodes with this computed role.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
}

/// The answer to `Accessibility.queryAXTree`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct QueryAXTreeReturns {
    /// A list of `Accessibility.AXNode` matching the specified attributes,
    /// including nodes that are ignored for accessibility.
    pub nodes: Vec<AXNode>,
}

impl QueryAXTreeParams {
    pub const METHOD: &'static str = "Accessibility.queryAXTree";
}

impl super::Command for QueryAXTreeParams {
    const METHOD: &'static str = "Accessibility.queryAXTree";
    type Returns = QueryAXTreeReturns;
}

/// The event `Accessibility.loadComplete`.
///
/// The loadComplete event mirrors the load complete event sent by the browser to assistive
/// technology when the web page has finished loading.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct LoadCompleteEvent {
    /// New document root node.
    pub root: AXNode,
}

impl LoadCompleteEvent {
    pub const NAME: &'static str = "Accessibility.loadComplete";
}

impl super::Event for LoadCompleteEvent {
    const NAME: &'static str = "Accessibility.loadComplete";
}

/// The event `Accessibility.nodesUpdated`.
///
/// The nodesUpdated event is sent every time a previously requested node has changed the in tree.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct NodesUpdatedEvent {
    /// Updated node data.
    pub nodes: Vec<AXNode>,
}

impl NodesUpdatedEvent {
    pub const NAME: &'static str = "Accessibility.nodesUpdated";
}

impl super::Event for NodesUpdatedEvent {
    const NAME: &'static str = "Accessibility.nodesUpdated";
}
