// Generated by eludite-cdp-generator from devtools-protocol 0.0.1709723 (protocol/cdp/PIN). Do not edit:
// change the generator or the pin and run `cargo run -p eludite-cdp-generator`.
//! The CDP domain `Browser`.
//!
//! The Browser domain defines methods and events for browser managing.

#![allow(
    clippy::upper_case_acronyms,
    clippy::doc_lazy_continuation,
    clippy::doc_overindented_list_items,
    clippy::large_enum_variant,
    clippy::empty_docs,
    clippy::struct_excessive_bools,
    rustdoc::bare_urls,
    rustdoc::broken_intra_doc_links,
    rustdoc::invalid_html_tags,
    rustdoc::invalid_rust_codeblocks
)]

use serde::{Deserialize, Serialize};

/// **Experimental.**
pub type BrowserContextID = String;

/// **Experimental.**
pub type WindowID = i64;

/// The state of the browser window.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum WindowState {
    /// `normal`
    Normal,
    /// `minimized`
    Minimized,
    /// `maximized`
    Maximized,
    /// `fullscreen`
    Fullscreen,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    WindowState {
        Normal => "normal",
        Minimized => "minimized",
        Maximized => "maximized",
        Fullscreen => "fullscreen",
    }
}

/// Browser window bounds information
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Bounds {
    /// The offset from the left edge of the screen to the window in pixels.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub left: Option<i64>,
    /// The offset from the top edge of the screen to the window in pixels.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub top: Option<i64>,
    /// The window width in pixels.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub width: Option<i64>,
    /// The window height in pixels.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub height: Option<i64>,
    /// The window state. Default to normal.
    #[serde(
        rename = "windowState",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub window_state: Option<WindowState>,
}

/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum PermissionType {
    /// `ar`
    Ar,
    /// `audioCapture`
    AudioCapture,
    /// `automaticFullscreen`
    AutomaticFullscreen,
    /// `backgroundFetch`
    BackgroundFetch,
    /// `backgroundSync`
    BackgroundSync,
    /// `cameraPanTiltZoom`
    CameraPanTiltZoom,
    /// `capturedSurfaceControl`
    CapturedSurfaceControl,
    /// `clipboardReadWrite`
    ClipboardReadWrite,
    /// `clipboardSanitizedWrite`
    ClipboardSanitizedWrite,
    /// `displayCapture`
    DisplayCapture,
    /// `durableStorage`
    DurableStorage,
    /// `geolocation`
    Geolocation,
    /// `handTracking`
    HandTracking,
    /// `idleDetection`
    IdleDetection,
    /// `keyboardLock`
    KeyboardLock,
    /// `localFonts`
    LocalFonts,
    /// `localNetwork`
    LocalNetwork,
    /// `localNetworkAccess`
    LocalNetworkAccess,
    /// `loopbackNetwork`
    LoopbackNetwork,
    /// `midi`
    Midi,
    /// `midiSysex`
    MidiSysex,
    /// `nfc`
    Nfc,
    /// `notifications`
    Notifications,
    /// `paymentHandler`
    PaymentHandler,
    /// `periodicBackgroundSync`
    PeriodicBackgroundSync,
    /// `pointerLock`
    PointerLock,
    /// `protectedMediaIdentifier`
    ProtectedMediaIdentifier,
    /// `sensors`
    Sensors,
    /// `smartCard`
    SmartCard,
    /// `speakerSelection`
    SpeakerSelection,
    /// `storageAccess`
    StorageAccess,
    /// `topLevelStorageAccess`
    TopLevelStorageAccess,
    /// `videoCapture`
    VideoCapture,
    /// `vr`
    Vr,
    /// `wakeLockScreen`
    WakeLockScreen,
    /// `wakeLockSystem`
    WakeLockSystem,
    /// `webAppInstallation`
    WebAppInstallation,
    /// `webPrinting`
    WebPrinting,
    /// `windowManagement`
    WindowManagement,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    PermissionType {
        Ar => "ar",
        AudioCapture => "audioCapture",
        AutomaticFullscreen => "automaticFullscreen",
        BackgroundFetch => "backgroundFetch",
        BackgroundSync => "backgroundSync",
        CameraPanTiltZoom => "cameraPanTiltZoom",
        CapturedSurfaceControl => "capturedSurfaceControl",
        ClipboardReadWrite => "clipboardReadWrite",
        ClipboardSanitizedWrite => "clipboardSanitizedWrite",
        DisplayCapture => "displayCapture",
        DurableStorage => "durableStorage",
        Geolocation => "geolocation",
        HandTracking => "handTracking",
        IdleDetection => "idleDetection",
        KeyboardLock => "keyboardLock",
        LocalFonts => "localFonts",
        LocalNetwork => "localNetwork",
        LocalNetworkAccess => "localNetworkAccess",
        LoopbackNetwork => "loopbackNetwork",
        Midi => "midi",
        MidiSysex => "midiSysex",
        Nfc => "nfc",
        Notifications => "notifications",
        PaymentHandler => "paymentHandler",
        PeriodicBackgroundSync => "periodicBackgroundSync",
        PointerLock => "pointerLock",
        ProtectedMediaIdentifier => "protectedMediaIdentifier",
        Sensors => "sensors",
        SmartCard => "smartCard",
        SpeakerSelection => "speakerSelection",
        StorageAccess => "storageAccess",
        TopLevelStorageAccess => "topLevelStorageAccess",
        VideoCapture => "videoCapture",
        Vr => "vr",
        WakeLockScreen => "wakeLockScreen",
        WakeLockSystem => "wakeLockSystem",
        WebAppInstallation => "webAppInstallation",
        WebPrinting => "webPrinting",
        WindowManagement => "windowManagement",
    }
}

/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum PermissionSetting {
    /// `granted`
    Granted,
    /// `denied`
    Denied,
    /// `prompt`
    Prompt,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    PermissionSetting {
        Granted => "granted",
        Denied => "denied",
        Prompt => "prompt",
    }
}

/// Definition of PermissionDescriptor defined in the Permissions API:
/// https://w3c.github.io/permissions/#dom-permissiondescriptor.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct PermissionDescriptor {
    /// Name of permission.
    /// See https://cs.chromium.org/chromium/src/third_party/blink/renderer/modules/permissions/permission_descriptor.idl for valid permission names.
    pub name: String,
    /// For "midi" permission, may also specify sysex control.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sysex: Option<bool>,
    /// For "push" permission, may specify userVisibleOnly.
    /// Note that userVisibleOnly = true is the only currently supported type.
    #[serde(
        rename = "userVisibleOnly",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub user_visible_only: Option<bool>,
    /// For "clipboard" permission, may specify allowWithoutSanitization.
    #[serde(
        rename = "allowWithoutSanitization",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub allow_without_sanitization: Option<bool>,
    /// For "fullscreen" permission, must specify allowWithoutGesture:true.
    #[serde(
        rename = "allowWithoutGesture",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub allow_without_gesture: Option<bool>,
    /// For "camera" permission, may specify panTiltZoom.
    #[serde(
        rename = "panTiltZoom",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pan_tilt_zoom: Option<bool>,
}

/// Browser command ids used by executeBrowserCommand.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum BrowserCommandId {
    /// `openTabSearch`
    OpenTabSearch,
    /// `closeTabSearch`
    CloseTabSearch,
    /// `openGlic`
    OpenGlic,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    BrowserCommandId {
        OpenTabSearch => "openTabSearch",
        CloseTabSearch => "closeTabSearch",
        OpenGlic => "openGlic",
    }
}

/// Chrome histogram bucket.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Bucket {
    /// Minimum value (inclusive).
    pub low: i64,
    /// Maximum value (exclusive).
    pub high: i64,
    /// Number of samples.
    pub count: i64,
}

/// Chrome histogram.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Histogram {
    /// Name.
    pub name: String,
    /// Sum of sample values.
    pub sum: i64,
    /// Total number of samples.
    pub count: i64,
    /// Buckets.
    pub buckets: Vec<Bucket>,
}

/// Parameters of `Browser.setPermission`.
///
/// Set permission settings for given embedding and embedded origins.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SetPermissionParams {
    /// Descriptor of permission to override.
    pub permission: PermissionDescriptor,
    /// Setting of the permission.
    pub setting: PermissionSetting,
    /// Embedding origin the permission applies to, all origins if not specified.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub origin: Option<String>,
    /// Embedded origin the permission applies to. It is ignored unless the embedding origin is
    /// present and valid. If the embedding origin is provided but the embedded origin isn't, the
    /// embedding origin is used as the embedded origin.
    #[serde(
        rename = "embeddedOrigin",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub embedded_origin: Option<String>,
    /// Context to override. When omitted, default browser context is used.
    #[serde(
        rename = "browserContextId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub browser_context_id: Option<BrowserContextID>,
}

/// The answer to `Browser.setPermission`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetPermissionReturns {}

impl SetPermissionParams {
    pub const METHOD: &'static str = "Browser.setPermission";
}

impl super::Command for SetPermissionParams {
    const METHOD: &'static str = "Browser.setPermission";
    type Returns = SetPermissionReturns;
}

/// Parameters of `Browser.grantPermissions`.
///
/// Grant specific permissions to the given origin and reject all others. Deprecated. Use
/// setPermission instead.
///
/// **Experimental.** **Deprecated.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GrantPermissionsParams {
    pub permissions: Vec<PermissionType>,
    /// Origin the permission applies to, all origins if not specified.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub origin: Option<String>,
    /// BrowserContext to override permissions. When omitted, default browser context is used.
    #[serde(
        rename = "browserContextId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub browser_context_id: Option<BrowserContextID>,
}

/// The answer to `Browser.grantPermissions`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GrantPermissionsReturns {}

impl GrantPermissionsParams {
    pub const METHOD: &'static str = "Browser.grantPermissions";
}

impl super::Command for GrantPermissionsParams {
    const METHOD: &'static str = "Browser.grantPermissions";
    type Returns = GrantPermissionsReturns;
}

/// Parameters of `Browser.resetPermissions`.
///
/// Reset all permission management for all origins.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ResetPermissionsParams {
    /// BrowserContext to reset permissions. When omitted, default browser context is used.
    #[serde(
        rename = "browserContextId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub browser_context_id: Option<BrowserContextID>,
}

/// The answer to `Browser.resetPermissions`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ResetPermissionsReturns {}

impl ResetPermissionsParams {
    pub const METHOD: &'static str = "Browser.resetPermissions";
}

impl super::Command for ResetPermissionsParams {
    const METHOD: &'static str = "Browser.resetPermissions";
    type Returns = ResetPermissionsReturns;
}

/// Parameters of `Browser.setDownloadBehavior`.
///
/// Set the behavior when downloading a file.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SetDownloadBehaviorParams {
    /// Whether to allow all or deny all download requests, or use default Chrome behavior if
    /// available (otherwise deny). |allowAndName| allows download and names files according to
    /// their download guids.
    pub behavior: SetDownloadBehaviorBehavior,
    /// BrowserContext to set download behavior. When omitted, default browser context is used.
    #[serde(
        rename = "browserContextId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub browser_context_id: Option<BrowserContextID>,
    /// The default path to save downloaded files to. This is required if behavior is set to 'allow'
    /// or 'allowAndName'.
    #[serde(
        rename = "downloadPath",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub download_path: Option<String>,
    /// Whether to emit download events (defaults to false).
    #[serde(
        rename = "eventsEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub events_enabled: Option<bool>,
}

/// Values of `SetDownloadBehavior`'s `behavior`.
///
/// Whether to allow all or deny all download requests, or use default Chrome behavior if
/// available (otherwise deny). |allowAndName| allows download and names files according to
/// their download guids.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SetDownloadBehaviorBehavior {
    /// `deny`
    Deny,
    /// `allow`
    Allow,
    /// `allowAndName`
    AllowAndName,
    /// `default`
    Default,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    SetDownloadBehaviorBehavior {
        Deny => "deny",
        Allow => "allow",
        AllowAndName => "allowAndName",
        Default => "default",
    }
}

/// The answer to `Browser.setDownloadBehavior`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetDownloadBehaviorReturns {}

impl SetDownloadBehaviorParams {
    pub const METHOD: &'static str = "Browser.setDownloadBehavior";
}

impl super::Command for SetDownloadBehaviorParams {
    const METHOD: &'static str = "Browser.setDownloadBehavior";
    type Returns = SetDownloadBehaviorReturns;
}

/// Parameters of `Browser.cancelDownload`.
///
/// Cancel a download if in progress
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CancelDownloadParams {
    /// Global unique identifier of the download.
    pub guid: String,
    /// BrowserContext to perform the action in. When omitted, default browser context is used.
    #[serde(
        rename = "browserContextId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub browser_context_id: Option<BrowserContextID>,
}

/// The answer to `Browser.cancelDownload`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CancelDownloadReturns {}

impl CancelDownloadParams {
    pub const METHOD: &'static str = "Browser.cancelDownload";
}

impl super::Command for CancelDownloadParams {
    const METHOD: &'static str = "Browser.cancelDownload";
    type Returns = CancelDownloadReturns;
}

/// Parameters of `Browser.close`.
///
/// Close browser gracefully.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CloseParams {}

/// The answer to `Browser.close`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CloseReturns {}

impl CloseParams {
    pub const METHOD: &'static str = "Browser.close";
}

impl super::Command for CloseParams {
    const METHOD: &'static str = "Browser.close";
    type Returns = CloseReturns;
}

/// Parameters of `Browser.crash`.
///
/// Crashes browser on the main thread.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CrashParams {}

/// The answer to `Browser.crash`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CrashReturns {}

impl CrashParams {
    pub const METHOD: &'static str = "Browser.crash";
}

impl super::Command for CrashParams {
    const METHOD: &'static str = "Browser.crash";
    type Returns = CrashReturns;
}

/// Parameters of `Browser.crashGpuProcess`.
///
/// Crashes GPU process.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CrashGpuProcessParams {}

/// The answer to `Browser.crashGpuProcess`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CrashGpuProcessReturns {}

impl CrashGpuProcessParams {
    pub const METHOD: &'static str = "Browser.crashGpuProcess";
}

impl super::Command for CrashGpuProcessParams {
    const METHOD: &'static str = "Browser.crashGpuProcess";
    type Returns = CrashGpuProcessReturns;
}

/// Parameters of `Browser.getVersion`.
///
/// Returns version information.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetVersionParams {}

/// The answer to `Browser.getVersion`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetVersionReturns {
    /// Protocol version.
    #[serde(rename = "protocolVersion")]
    pub protocol_version: String,
    /// Product name.
    pub product: String,
    /// Product revision.
    pub revision: String,
    /// User-Agent.
    #[serde(rename = "userAgent")]
    pub user_agent: String,
    /// V8 version.
    #[serde(rename = "jsVersion")]
    pub js_version: String,
}

impl GetVersionParams {
    pub const METHOD: &'static str = "Browser.getVersion";
}

impl super::Command for GetVersionParams {
    const METHOD: &'static str = "Browser.getVersion";
    type Returns = GetVersionReturns;
}

/// Parameters of `Browser.getBrowserCommandLine`.
///
/// Returns the command line switches for the browser process if, and only if
/// --enable-automation is on the commandline.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetBrowserCommandLineParams {}

/// The answer to `Browser.getBrowserCommandLine`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetBrowserCommandLineReturns {
    /// Commandline parameters
    pub arguments: Vec<String>,
}

impl GetBrowserCommandLineParams {
    pub const METHOD: &'static str = "Browser.getBrowserCommandLine";
}

impl super::Command for GetBrowserCommandLineParams {
    const METHOD: &'static str = "Browser.getBrowserCommandLine";
    type Returns = GetBrowserCommandLineReturns;
}

/// Parameters of `Browser.addMockCamera`.
///
/// Adds or updates a mock camera in the shared video capture device list for
/// test automation. The mock camera is not scoped to a particular page or
/// frame and is removed when the DevTools session that created it disconnects.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AddMockCameraParams {
    /// Required non-empty identifier for the mock camera. This is mapped to an
    /// internal virtual-device identifier and is not the MediaDeviceInfo.deviceId
    /// exposed to the page.
    #[serde(rename = "deviceId")]
    pub device_id: String,
}

/// The answer to `Browser.addMockCamera`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AddMockCameraReturns {}

impl AddMockCameraParams {
    pub const METHOD: &'static str = "Browser.addMockCamera";
}

impl super::Command for AddMockCameraParams {
    const METHOD: &'static str = "Browser.addMockCamera";
    type Returns = AddMockCameraReturns;
}

/// Parameters of `Browser.getHistograms`.
///
/// Get Chrome histograms.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetHistogramsParams {
    /// Requested substring in name. Only histograms which have query as a
    /// substring in their name are extracted. An empty or absent query returns
    /// all histograms.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    /// If true, retrieve delta since last delta call.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub delta: Option<bool>,
}

/// The answer to `Browser.getHistograms`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetHistogramsReturns {
    /// Histograms.
    pub histograms: Vec<Histogram>,
}

impl GetHistogramsParams {
    pub const METHOD: &'static str = "Browser.getHistograms";
}

impl super::Command for GetHistogramsParams {
    const METHOD: &'static str = "Browser.getHistograms";
    type Returns = GetHistogramsReturns;
}

/// Parameters of `Browser.getHistogram`.
///
/// Get a Chrome histogram by name.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetHistogramParams {
    /// Requested histogram name.
    pub name: String,
    /// If true, retrieve delta since last delta call.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub delta: Option<bool>,
}

/// The answer to `Browser.getHistogram`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetHistogramReturns {
    /// Histogram.
    pub histogram: Histogram,
}

impl GetHistogramParams {
    pub const METHOD: &'static str = "Browser.getHistogram";
}

impl super::Command for GetHistogramParams {
    const METHOD: &'static str = "Browser.getHistogram";
    type Returns = GetHistogramReturns;
}

/// Parameters of `Browser.getWindowBounds`.
///
/// Get position and size of the browser window.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetWindowBoundsParams {
    /// Browser window id.
    #[serde(rename = "windowId")]
    pub window_id: WindowID,
}

/// The answer to `Browser.getWindowBounds`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetWindowBoundsReturns {
    /// Bounds information of the window. When window state is 'minimized', the restored window
    /// position and size are returned.
    pub bounds: Bounds,
}

impl GetWindowBoundsParams {
    pub const METHOD: &'static str = "Browser.getWindowBounds";
}

impl super::Command for GetWindowBoundsParams {
    const METHOD: &'static str = "Browser.getWindowBounds";
    type Returns = GetWindowBoundsReturns;
}

/// Parameters of `Browser.getWindowForTarget`.
///
/// Get the browser window that contains the devtools target.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetWindowForTargetParams {
    /// Devtools agent host id. If called as a part of the session, associated targetId is used.
    #[serde(rename = "targetId", default, skip_serializing_if = "Option::is_none")]
    pub target_id: Option<super::target::TargetID>,
}

/// The answer to `Browser.getWindowForTarget`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetWindowForTargetReturns {
    /// Browser window id.
    #[serde(rename = "windowId")]
    pub window_id: WindowID,
    /// Bounds information of the window. When window state is 'minimized', the restored window
    /// position and size are returned.
    pub bounds: Bounds,
}

impl GetWindowForTargetParams {
    pub const METHOD: &'static str = "Browser.getWindowForTarget";
}

impl super::Command for GetWindowForTargetParams {
    const METHOD: &'static str = "Browser.getWindowForTarget";
    type Returns = GetWindowForTargetReturns;
}

/// Parameters of `Browser.setWindowBounds`.
///
/// Set position and/or size of the browser window.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetWindowBoundsParams {
    /// Browser window id.
    #[serde(rename = "windowId")]
    pub window_id: WindowID,
    /// New window bounds. The 'minimized', 'maximized' and 'fullscreen' states cannot be combined
    /// with 'left', 'top', 'width' or 'height'. Leaves unspecified fields unchanged.
    pub bounds: Bounds,
}

/// The answer to `Browser.setWindowBounds`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetWindowBoundsReturns {}

impl SetWindowBoundsParams {
    pub const METHOD: &'static str = "Browser.setWindowBounds";
}

impl super::Command for SetWindowBoundsParams {
    const METHOD: &'static str = "Browser.setWindowBounds";
    type Returns = SetWindowBoundsReturns;
}

/// Parameters of `Browser.setContentsSize`.
///
/// Set size of the browser contents resizing browser window as necessary.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetContentsSizeParams {
    /// Browser window id.
    #[serde(rename = "windowId")]
    pub window_id: WindowID,
    /// The window contents width in DIP. Assumes current width if omitted.
    /// Must be specified if 'height' is omitted.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub width: Option<i64>,
    /// The window contents height in DIP. Assumes current height if omitted.
    /// Must be specified if 'width' is omitted.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub height: Option<i64>,
}

/// The answer to `Browser.setContentsSize`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetContentsSizeReturns {}

impl SetContentsSizeParams {
    pub const METHOD: &'static str = "Browser.setContentsSize";
}

impl super::Command for SetContentsSizeParams {
    const METHOD: &'static str = "Browser.setContentsSize";
    type Returns = SetContentsSizeReturns;
}

/// Parameters of `Browser.setDockTile`.
///
/// Set dock tile details, platform-specific.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetDockTileParams {
    #[serde(
        rename = "badgeLabel",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub badge_label: Option<String>,
    /// Png encoded image. (Encoded as a base64 string when passed over JSON)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
}

/// The answer to `Browser.setDockTile`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetDockTileReturns {}

impl SetDockTileParams {
    pub const METHOD: &'static str = "Browser.setDockTile";
}

impl super::Command for SetDockTileParams {
    const METHOD: &'static str = "Browser.setDockTile";
    type Returns = SetDockTileReturns;
}

/// Parameters of `Browser.executeBrowserCommand`.
///
/// Invoke custom browser commands used by telemetry.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ExecuteBrowserCommandParams {
    #[serde(rename = "commandId")]
    pub command_id: BrowserCommandId,
}

/// The answer to `Browser.executeBrowserCommand`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ExecuteBrowserCommandReturns {}

impl ExecuteBrowserCommandParams {
    pub const METHOD: &'static str = "Browser.executeBrowserCommand";
}

impl super::Command for ExecuteBrowserCommandParams {
    const METHOD: &'static str = "Browser.executeBrowserCommand";
    type Returns = ExecuteBrowserCommandReturns;
}

/// Parameters of `Browser.addPrivacySandboxEnrollmentOverride`.
///
/// Allows a site to use privacy sandbox features that require enrollment
/// without the site actually being enrolled. Only supported on page targets.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AddPrivacySandboxEnrollmentOverrideParams {
    pub url: String,
}

/// The answer to `Browser.addPrivacySandboxEnrollmentOverride`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AddPrivacySandboxEnrollmentOverrideReturns {}

impl AddPrivacySandboxEnrollmentOverrideParams {
    pub const METHOD: &'static str = "Browser.addPrivacySandboxEnrollmentOverride";
}

impl super::Command for AddPrivacySandboxEnrollmentOverrideParams {
    const METHOD: &'static str = "Browser.addPrivacySandboxEnrollmentOverride";
    type Returns = AddPrivacySandboxEnrollmentOverrideReturns;
}

/// Parameters of `Browser.getGlobalPrivacyControl`.
///
/// Gets the current globally-applied privacy control status
/// See https://www.w3.org/TR/gpc/#get-global-privacy-control
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetGlobalPrivacyControlParams {}

/// The answer to `Browser.getGlobalPrivacyControl`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetGlobalPrivacyControlReturns {
    pub gpc: bool,
}

impl GetGlobalPrivacyControlParams {
    pub const METHOD: &'static str = "Browser.getGlobalPrivacyControl";
}

impl super::Command for GetGlobalPrivacyControlParams {
    const METHOD: &'static str = "Browser.getGlobalPrivacyControl";
    type Returns = GetGlobalPrivacyControlReturns;
}

/// Parameters of `Browser.setGlobalPrivacyControl`.
///
/// Sets and then gets the current globally-applied privacy control status
/// See https://www.w3.org/TR/gpc/#set-global-privacy-control
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetGlobalPrivacyControlParams {
    pub gpc: bool,
}

/// The answer to `Browser.setGlobalPrivacyControl`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetGlobalPrivacyControlReturns {
    pub gpc: bool,
}

impl SetGlobalPrivacyControlParams {
    pub const METHOD: &'static str = "Browser.setGlobalPrivacyControl";
}

impl super::Command for SetGlobalPrivacyControlParams {
    const METHOD: &'static str = "Browser.setGlobalPrivacyControl";
    type Returns = SetGlobalPrivacyControlReturns;
}

/// The event `Browser.downloadWillBegin`.
///
/// Fired when page is about to start a download.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DownloadWillBeginEvent {
    /// Id of the frame that caused the download to begin.
    #[serde(rename = "frameId")]
    pub frame_id: super::page::FrameId,
    /// Global unique identifier of the download.
    pub guid: String,
    /// URL of the resource being downloaded.
    pub url: String,
    /// Suggested file name of the resource (the actual name of the file saved on disk may differ).
    #[serde(rename = "suggestedFilename")]
    pub suggested_filename: String,
}

impl DownloadWillBeginEvent {
    pub const NAME: &'static str = "Browser.downloadWillBegin";
}

impl super::Event for DownloadWillBeginEvent {
    const NAME: &'static str = "Browser.downloadWillBegin";
}

/// The event `Browser.downloadProgress`.
///
/// Fired when download makes progress. Last call has |done| == true.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DownloadProgressEvent {
    /// Global unique identifier of the download.
    pub guid: String,
    /// Total expected bytes to download.
    #[serde(rename = "totalBytes")]
    pub total_bytes: f64,
    /// Total bytes received.
    #[serde(rename = "receivedBytes")]
    pub received_bytes: f64,
    /// Download status.
    pub state: DownloadProgressState,
    /// If download is "completed", provides the path of the downloaded file.
    /// Depending on the platform, it is not guaranteed to be set, nor the file
    /// is guaranteed to exist.
    ///
    /// **Experimental.**
    #[serde(rename = "filePath", default, skip_serializing_if = "Option::is_none")]
    pub file_path: Option<String>,
}

/// Values of `DownloadProgress`'s `state`.
///
/// Download status.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum DownloadProgressState {
    /// `inProgress`
    InProgress,
    /// `completed`
    Completed,
    /// `canceled`
    Canceled,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    DownloadProgressState {
        InProgress => "inProgress",
        Completed => "completed",
        Canceled => "canceled",
    }
}

impl DownloadProgressEvent {
    pub const NAME: &'static str = "Browser.downloadProgress";
}

impl super::Event for DownloadProgressEvent {
    const NAME: &'static str = "Browser.downloadProgress";
}
