// Generated by eludite-cdp-generator from devtools-protocol 0.0.1709723 (protocol/cdp/PIN). Do not edit:
// change the generator or the pin and run `cargo run -p eludite-cdp-generator`.
//! The CDP domain `DOM`.
//!
//! This domain exposes DOM read/write operations. Each DOM Node is represented with its mirror object
//! that has an `id`. This `id` can be used to get additional information on the Node, resolve it into
//! the JavaScript object wrapper, etc. It is important that client receives DOM events only for the
//! nodes that are known to the client. Backend keeps track of the nodes that were sent to the client
//! and never sends the same node twice. It is client's responsibility to collect information about
//! the nodes that were sent to the client. Note that `iframe` owner elements will return
//! corresponding document elements as their child nodes.

#![allow(
    clippy::upper_case_acronyms,
    clippy::doc_lazy_continuation,
    clippy::doc_overindented_list_items,
    clippy::large_enum_variant,
    clippy::empty_docs,
    clippy::struct_excessive_bools,
    rustdoc::bare_urls,
    rustdoc::broken_intra_doc_links,
    rustdoc::invalid_html_tags,
    rustdoc::invalid_rust_codeblocks
)]

use serde::{Deserialize, Serialize};

/// Unique DOM node identifier.
pub type NodeId = i64;

/// Unique DOM node identifier used to reference a node that may not have been pushed to the
/// front-end.
pub type BackendNodeId = i64;

/// Unique identifier for a CSS stylesheet.
pub type StyleSheetId = String;

/// Backend node with a friendly name.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct BackendNode {
    /// `Node`'s nodeType.
    #[serde(rename = "nodeType")]
    pub node_type: i64,
    /// `Node`'s nodeName.
    #[serde(rename = "nodeName")]
    pub node_name: String,
    #[serde(rename = "backendNodeId")]
    pub backend_node_id: BackendNodeId,
}

/// Pseudo element type.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum PseudoType {
    /// `first-line`
    FirstLine,
    /// `first-letter`
    FirstLetter,
    /// `checkmark`
    Checkmark,
    /// `before`
    Before,
    /// `after`
    After,
    /// `expand-icon`
    ExpandIcon,
    /// `picker-icon`
    PickerIcon,
    /// `interest-button`
    InterestButton,
    /// `marker`
    Marker,
    /// `backdrop`
    Backdrop,
    /// `column`
    Column,
    /// `selection`
    Selection,
    /// `search-text`
    SearchText,
    /// `target-text`
    TargetText,
    /// `spelling-error`
    SpellingError,
    /// `grammar-error`
    GrammarError,
    /// `highlight`
    Highlight,
    /// `first-line-inherited`
    FirstLineInherited,
    /// `scroll-marker`
    ScrollMarker,
    /// `scroll-marker-group`
    ScrollMarkerGroup,
    /// `scroll-button`
    ScrollButton,
    /// `scrollbar`
    Scrollbar,
    /// `scrollbar-thumb`
    ScrollbarThumb,
    /// `scrollbar-button`
    ScrollbarButton,
    /// `scrollbar-track`
    ScrollbarTrack,
    /// `scrollbar-track-piece`
    ScrollbarTrackPiece,
    /// `scrollbar-corner`
    ScrollbarCorner,
    /// `resizer`
    Resizer,
    /// `input-list-button`
    InputListButton,
    /// `view-transition`
    ViewTransition,
    /// `view-transition-group`
    ViewTransitionGroup,
    /// `view-transition-image-pair`
    ViewTransitionImagePair,
    /// `view-transition-group-children`
    ViewTransitionGroupChildren,
    /// `view-transition-old`
    ViewTransitionOld,
    /// `view-transition-new`
    ViewTransitionNew,
    /// `placeholder`
    Placeholder,
    /// `file-selector-button`
    FileSelectorButton,
    /// `details-content`
    DetailsContent,
    /// `picker`
    Picker,
    /// `select-listbox`
    SelectListbox,
    /// `permission-icon`
    PermissionIcon,
    /// `overscroll-area-parent`
    OverscrollAreaParent,
    /// `overscroll-backdrop`
    OverscrollBackdrop,
    /// `skeleton`
    Skeleton,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    PseudoType {
        FirstLine => "first-line",
        FirstLetter => "first-letter",
        Checkmark => "checkmark",
        Before => "before",
        After => "after",
        ExpandIcon => "expand-icon",
        PickerIcon => "picker-icon",
        InterestButton => "interest-button",
        Marker => "marker",
        Backdrop => "backdrop",
        Column => "column",
        Selection => "selection",
        SearchText => "search-text",
        TargetText => "target-text",
        SpellingError => "spelling-error",
        GrammarError => "grammar-error",
        Highlight => "highlight",
        FirstLineInherited => "first-line-inherited",
        ScrollMarker => "scroll-marker",
        ScrollMarkerGroup => "scroll-marker-group",
        ScrollButton => "scroll-button",
        Scrollbar => "scrollbar",
        ScrollbarThumb => "scrollbar-thumb",
        ScrollbarButton => "scrollbar-button",
        ScrollbarTrack => "scrollbar-track",
        ScrollbarTrackPiece => "scrollbar-track-piece",
        ScrollbarCorner => "scrollbar-corner",
        Resizer => "resizer",
        InputListButton => "input-list-button",
        ViewTransition => "view-transition",
        ViewTransitionGroup => "view-transition-group",
        ViewTransitionImagePair => "view-transition-image-pair",
        ViewTransitionGroupChildren => "view-transition-group-children",
        ViewTransitionOld => "view-transition-old",
        ViewTransitionNew => "view-transition-new",
        Placeholder => "placeholder",
        FileSelectorButton => "file-selector-button",
        DetailsContent => "details-content",
        Picker => "picker",
        SelectListbox => "select-listbox",
        PermissionIcon => "permission-icon",
        OverscrollAreaParent => "overscroll-area-parent",
        OverscrollBackdrop => "overscroll-backdrop",
        Skeleton => "skeleton",
    }
}

/// Shadow root type.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ShadowRootType {
    /// `user-agent`
    UserAgent,
    /// `open`
    Open,
    /// `closed`
    Closed,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    ShadowRootType {
        UserAgent => "user-agent",
        Open => "open",
        Closed => "closed",
    }
}

/// Document compatibility mode.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum CompatibilityMode {
    /// `QuirksMode`
    QuirksMode,
    /// `LimitedQuirksMode`
    LimitedQuirksMode,
    /// `NoQuirksMode`
    NoQuirksMode,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    CompatibilityMode {
        QuirksMode => "QuirksMode",
        LimitedQuirksMode => "LimitedQuirksMode",
        NoQuirksMode => "NoQuirksMode",
    }
}

/// ContainerSelector physical axes
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum PhysicalAxes {
    /// `Horizontal`
    Horizontal,
    /// `Vertical`
    Vertical,
    /// `Both`
    Both,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    PhysicalAxes {
        Horizontal => "Horizontal",
        Vertical => "Vertical",
        Both => "Both",
    }
}

/// ContainerSelector logical axes
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum LogicalAxes {
    /// `Inline`
    Inline,
    /// `Block`
    Block,
    /// `Both`
    Both,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    LogicalAxes {
        Inline => "Inline",
        Block => "Block",
        Both => "Both",
    }
}

/// Physical scroll orientation
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ScrollOrientation {
    /// `horizontal`
    Horizontal,
    /// `vertical`
    Vertical,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    ScrollOrientation {
        Horizontal => "horizontal",
        Vertical => "vertical",
    }
}

/// DOM interaction is implemented in terms of mirror objects that represent the actual DOM nodes.
/// DOMNode is a base node mirror type.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Node {
    /// Node identifier that is passed into the rest of the DOM messages as the `nodeId`. Backend
    /// will only push node with given `id` once. It is aware of all requested nodes and will only
    /// fire DOM events for nodes known to the client.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    /// The id of the parent node if any.
    #[serde(rename = "parentId", default, skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<NodeId>,
    /// The BackendNodeId for this node.
    #[serde(rename = "backendNodeId")]
    pub backend_node_id: BackendNodeId,
    /// `Node`'s nodeType.
    #[serde(rename = "nodeType")]
    pub node_type: i64,
    /// `Node`'s nodeName.
    #[serde(rename = "nodeName")]
    pub node_name: String,
    /// `Node`'s localName.
    #[serde(rename = "localName")]
    pub local_name: String,
    /// `Node`'s nodeValue.
    #[serde(rename = "nodeValue")]
    pub node_value: String,
    /// Child count for `Container` nodes.
    #[serde(
        rename = "childNodeCount",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub child_node_count: Option<i64>,
    /// Child nodes of this node when requested with children.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub children: Option<Vec<Node>>,
    /// Attributes of the `Element` node in the form of flat array `[name1, value1, name2, value2]`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Vec<String>>,
    /// Document URL that `Document` or `FrameOwner` node points to.
    #[serde(
        rename = "documentURL",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub document_url: Option<String>,
    /// Base URL that `Document` or `FrameOwner` node uses for URL completion.
    #[serde(rename = "baseURL", default, skip_serializing_if = "Option::is_none")]
    pub base_url: Option<String>,
    /// `DocumentType`'s publicId.
    #[serde(rename = "publicId", default, skip_serializing_if = "Option::is_none")]
    pub public_id: Option<String>,
    /// `DocumentType`'s systemId.
    #[serde(rename = "systemId", default, skip_serializing_if = "Option::is_none")]
    pub system_id: Option<String>,
    /// `DocumentType`'s internalSubset.
    #[serde(
        rename = "internalSubset",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub internal_subset: Option<String>,
    /// `Document`'s XML version in case of XML documents.
    #[serde(
        rename = "xmlVersion",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub xml_version: Option<String>,
    /// `Attr`'s name.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// `Attr`'s value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    /// Pseudo element type for this node.
    #[serde(
        rename = "pseudoType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pseudo_type: Option<PseudoType>,
    /// Pseudo element identifier for this node. Only present if there is a
    /// valid pseudoType.
    #[serde(
        rename = "pseudoIdentifier",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pseudo_identifier: Option<String>,
    /// Shadow root type.
    #[serde(
        rename = "shadowRootType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub shadow_root_type: Option<ShadowRootType>,
    /// Frame ID for frame owner elements.
    #[serde(rename = "frameId", default, skip_serializing_if = "Option::is_none")]
    pub frame_id: Option<super::page::FrameId>,
    /// Content document for frame owner elements.
    #[serde(
        rename = "contentDocument",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub content_document: Option<Box<Node>>,
    /// Shadow root list for given element host.
    #[serde(
        rename = "shadowRoots",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub shadow_roots: Option<Vec<Node>>,
    /// Content document fragment for template elements.
    #[serde(
        rename = "templateContent",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub template_content: Option<Box<Node>>,
    /// Pseudo elements associated with this node.
    #[serde(
        rename = "pseudoElements",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pseudo_elements: Option<Vec<Node>>,
    /// Deprecated, as the HTML Imports API has been removed (crbug.com/937746).
    /// This property used to return the imported document for the HTMLImport links.
    /// The property is always undefined now.
    ///
    /// **Deprecated.**
    #[serde(
        rename = "importedDocument",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub imported_document: Option<Box<Node>>,
    /// Distributed nodes for given insertion point.
    #[serde(
        rename = "distributedNodes",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub distributed_nodes: Option<Vec<BackendNode>>,
    /// Whether the node is SVG.
    #[serde(rename = "isSVG", default, skip_serializing_if = "Option::is_none")]
    pub is_svg: Option<bool>,
    #[serde(
        rename = "compatibilityMode",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub compatibility_mode: Option<CompatibilityMode>,
    #[serde(
        rename = "assignedSlot",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub assigned_slot: Option<BackendNode>,
    /// **Experimental.**
    #[serde(
        rename = "isScrollable",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_scrollable: Option<bool>,
    /// **Experimental.**
    #[serde(
        rename = "affectedByStartingStyles",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub affected_by_starting_styles: Option<bool>,
    /// **Experimental.**
    #[serde(
        rename = "adoptedStyleSheets",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub adopted_style_sheets: Option<Vec<StyleSheetId>>,
    /// **Experimental.**
    #[serde(
        rename = "adProvenance",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub ad_provenance: Option<super::network::AdProvenance>,
}

/// A structure to hold the top-level node of a detached tree and an array of its retained descendants.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DetachedElementInfo {
    #[serde(rename = "treeNode")]
    pub tree_node: Node,
    #[serde(rename = "retainedNodeIds")]
    pub retained_node_ids: Vec<NodeId>,
}

/// A structure holding an RGBA color.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RGBA {
    /// The red component, in the [0-255] range.
    pub r: i64,
    /// The green component, in the [0-255] range.
    pub g: i64,
    /// The blue component, in the [0-255] range.
    pub b: i64,
    /// The alpha component, in the [0-1] range (default: 1).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub a: Option<f64>,
}

/// An array of quad vertices, x immediately followed by y for each point, points clock-wise.
pub type Quad = Vec<f64>;

/// Box model.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct BoxModel {
    /// Content box
    pub content: Quad,
    /// Padding box
    pub padding: Quad,
    /// Border box
    pub border: Quad,
    /// Margin box
    pub margin: Quad,
    /// Node width
    pub width: i64,
    /// Node height
    pub height: i64,
    /// Shape outside coordinates
    #[serde(
        rename = "shapeOutside",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub shape_outside: Option<ShapeOutsideInfo>,
}

/// CSS Shape Outside details.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ShapeOutsideInfo {
    /// Shape bounds
    pub bounds: Quad,
    /// Shape coordinate details
    pub shape: Vec<serde_json::Value>,
    /// Margin shape bounds
    #[serde(rename = "marginShape")]
    pub margin_shape: Vec<serde_json::Value>,
}

/// Rectangle.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Rect {
    /// X coordinate
    pub x: f64,
    /// Y coordinate
    pub y: f64,
    /// Rectangle width
    pub width: f64,
    /// Rectangle height
    pub height: f64,
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CSSComputedStyleProperty {
    /// Computed style property name.
    pub name: String,
    /// Computed style property value.
    pub value: String,
}

/// Parameters of `DOM.collectClassNamesFromSubtree`.
///
/// Collects class names for the node with given id and all of it's child nodes.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CollectClassNamesFromSubtreeParams {
    /// Id of the node to collect class names.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
}

/// The answer to `DOM.collectClassNamesFromSubtree`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CollectClassNamesFromSubtreeReturns {
    /// Class name list.
    #[serde(rename = "classNames")]
    pub class_names: Vec<String>,
}

impl CollectClassNamesFromSubtreeParams {
    pub const METHOD: &'static str = "DOM.collectClassNamesFromSubtree";
}

impl super::Command for CollectClassNamesFromSubtreeParams {
    const METHOD: &'static str = "DOM.collectClassNamesFromSubtree";
    type Returns = CollectClassNamesFromSubtreeReturns;
}

/// Parameters of `DOM.copyTo`.
///
/// Creates a deep copy of the specified node and places it into the target container before the
/// given anchor.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CopyToParams {
    /// Id of the node to copy.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    /// Id of the element to drop the copy into.
    #[serde(rename = "targetNodeId")]
    pub target_node_id: NodeId,
    /// Drop the copy before this node (if absent, the copy becomes the last child of
    /// `targetNodeId`).
    #[serde(
        rename = "insertBeforeNodeId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub insert_before_node_id: Option<NodeId>,
}

/// The answer to `DOM.copyTo`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CopyToReturns {
    /// Id of the node clone.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
}

impl CopyToParams {
    pub const METHOD: &'static str = "DOM.copyTo";
}

impl super::Command for CopyToParams {
    const METHOD: &'static str = "DOM.copyTo";
    type Returns = CopyToReturns;
}

/// Parameters of `DOM.describeNode`.
///
/// Describes node given its id, does not require domain to be enabled. Does not start tracking any
/// objects, can be used for automation.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DescribeNodeParams {
    /// Identifier of the node.
    #[serde(rename = "nodeId", default, skip_serializing_if = "Option::is_none")]
    pub node_id: Option<NodeId>,
    /// Identifier of the backend node.
    #[serde(
        rename = "backendNodeId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub backend_node_id: Option<BackendNodeId>,
    /// JavaScript object id of the node wrapper.
    #[serde(rename = "objectId", default, skip_serializing_if = "Option::is_none")]
    pub object_id: Option<super::runtime::RemoteObjectId>,
    /// The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the
    /// entire subtree or provide an integer larger than 0.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub depth: Option<i64>,
    /// Whether or not iframes and shadow roots should be traversed when returning the subtree
    /// (default is false).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pierce: Option<bool>,
}

/// The answer to `DOM.describeNode`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DescribeNodeReturns {
    /// Node description.
    pub node: Node,
}

impl DescribeNodeParams {
    pub const METHOD: &'static str = "DOM.describeNode";
}

impl super::Command for DescribeNodeParams {
    const METHOD: &'static str = "DOM.describeNode";
    type Returns = DescribeNodeReturns;
}

/// Parameters of `DOM.scrollIntoViewIfNeeded`.
///
/// Scrolls the specified rect of the given node into view if not already visible.
/// Note: exactly one between nodeId, backendNodeId and objectId should be passed
/// to identify the node.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ScrollIntoViewIfNeededParams {
    /// Identifier of the node.
    #[serde(rename = "nodeId", default, skip_serializing_if = "Option::is_none")]
    pub node_id: Option<NodeId>,
    /// Identifier of the backend node.
    #[serde(
        rename = "backendNodeId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub backend_node_id: Option<BackendNodeId>,
    /// JavaScript object id of the node wrapper.
    #[serde(rename = "objectId", default, skip_serializing_if = "Option::is_none")]
    pub object_id: Option<super::runtime::RemoteObjectId>,
    /// The rect to be scrolled into view, relative to the node's border box, in CSS pixels.
    /// When omitted, center of the node will be used, similar to Element.scrollIntoView.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rect: Option<Rect>,
}

/// The answer to `DOM.scrollIntoViewIfNeeded`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ScrollIntoViewIfNeededReturns {}

impl ScrollIntoViewIfNeededParams {
    pub const METHOD: &'static str = "DOM.scrollIntoViewIfNeeded";
}

impl super::Command for ScrollIntoViewIfNeededParams {
    const METHOD: &'static str = "DOM.scrollIntoViewIfNeeded";
    type Returns = ScrollIntoViewIfNeededReturns;
}

/// Parameters of `DOM.disable`.
///
/// Disables DOM agent for the given page.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DisableParams {}

/// The answer to `DOM.disable`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DisableReturns {}

impl DisableParams {
    pub const METHOD: &'static str = "DOM.disable";
}

impl super::Command for DisableParams {
    const METHOD: &'static str = "DOM.disable";
    type Returns = DisableReturns;
}

/// Parameters of `DOM.discardSearchResults`.
///
/// Discards search results from the session with the given id. `getSearchResults` should no longer
/// be called for that search.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DiscardSearchResultsParams {
    /// Unique search session identifier.
    #[serde(rename = "searchId")]
    pub search_id: String,
}

/// The answer to `DOM.discardSearchResults`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DiscardSearchResultsReturns {}

impl DiscardSearchResultsParams {
    pub const METHOD: &'static str = "DOM.discardSearchResults";
}

impl super::Command for DiscardSearchResultsParams {
    const METHOD: &'static str = "DOM.discardSearchResults";
    type Returns = DiscardSearchResultsReturns;
}

/// Parameters of `DOM.enable`.
///
/// Enables DOM agent for the given page.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EnableParams {
    /// Whether to include whitespaces in the children array of returned Nodes.
    ///
    /// **Experimental.**
    #[serde(
        rename = "includeWhitespace",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub include_whitespace: Option<EnableIncludeWhitespace>,
}

/// Values of `Enable`'s `includeWhitespace`.
///
/// Whether to include whitespaces in the children array of returned Nodes.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum EnableIncludeWhitespace {
    /// `none`
    None,
    /// `all`
    All,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    EnableIncludeWhitespace {
        None => "none",
        All => "all",
    }
}

/// The answer to `DOM.enable`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EnableReturns {}

impl EnableParams {
    pub const METHOD: &'static str = "DOM.enable";
}

impl super::Command for EnableParams {
    const METHOD: &'static str = "DOM.enable";
    type Returns = EnableReturns;
}

/// Parameters of `DOM.focus`.
///
/// Focuses the given element.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct FocusParams {
    /// Identifier of the node.
    #[serde(rename = "nodeId", default, skip_serializing_if = "Option::is_none")]
    pub node_id: Option<NodeId>,
    /// Identifier of the backend node.
    #[serde(
        rename = "backendNodeId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub backend_node_id: Option<BackendNodeId>,
    /// JavaScript object id of the node wrapper.
    #[serde(rename = "objectId", default, skip_serializing_if = "Option::is_none")]
    pub object_id: Option<super::runtime::RemoteObjectId>,
}

/// The answer to `DOM.focus`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct FocusReturns {}

impl FocusParams {
    pub const METHOD: &'static str = "DOM.focus";
}

impl super::Command for FocusParams {
    const METHOD: &'static str = "DOM.focus";
    type Returns = FocusReturns;
}

/// Parameters of `DOM.getAttributes`.
///
/// Returns attributes for the specified node.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAttributesParams {
    /// Id of the node to retrieve attributes for.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
}

/// The answer to `DOM.getAttributes`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAttributesReturns {
    /// An interleaved array of node attribute names and values.
    pub attributes: Vec<String>,
}

impl GetAttributesParams {
    pub const METHOD: &'static str = "DOM.getAttributes";
}

impl super::Command for GetAttributesParams {
    const METHOD: &'static str = "DOM.getAttributes";
    type Returns = GetAttributesReturns;
}

/// Parameters of `DOM.getBoxModel`.
///
/// Returns boxes for the given node.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetBoxModelParams {
    /// Identifier of the node.
    #[serde(rename = "nodeId", default, skip_serializing_if = "Option::is_none")]
    pub node_id: Option<NodeId>,
    /// Identifier of the backend node.
    #[serde(
        rename = "backendNodeId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub backend_node_id: Option<BackendNodeId>,
    /// JavaScript object id of the node wrapper.
    #[serde(rename = "objectId", default, skip_serializing_if = "Option::is_none")]
    pub object_id: Option<super::runtime::RemoteObjectId>,
}

/// The answer to `DOM.getBoxModel`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetBoxModelReturns {
    /// Box model for the node.
    pub model: BoxModel,
}

impl GetBoxModelParams {
    pub const METHOD: &'static str = "DOM.getBoxModel";
}

impl super::Command for GetBoxModelParams {
    const METHOD: &'static str = "DOM.getBoxModel";
    type Returns = GetBoxModelReturns;
}

/// Parameters of `DOM.getContentQuads`.
///
/// Returns quads that describe node position on the page. This method
/// might return multiple quads for inline nodes.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetContentQuadsParams {
    /// Identifier of the node.
    #[serde(rename = "nodeId", default, skip_serializing_if = "Option::is_none")]
    pub node_id: Option<NodeId>,
    /// Identifier of the backend node.
    #[serde(
        rename = "backendNodeId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub backend_node_id: Option<BackendNodeId>,
    /// JavaScript object id of the node wrapper.
    #[serde(rename = "objectId", default, skip_serializing_if = "Option::is_none")]
    pub object_id: Option<super::runtime::RemoteObjectId>,
}

/// The answer to `DOM.getContentQuads`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetContentQuadsReturns {
    /// Quads that describe node layout relative to viewport.
    pub quads: Vec<Quad>,
}

impl GetContentQuadsParams {
    pub const METHOD: &'static str = "DOM.getContentQuads";
}

impl super::Command for GetContentQuadsParams {
    const METHOD: &'static str = "DOM.getContentQuads";
    type Returns = GetContentQuadsReturns;
}

/// Parameters of `DOM.getDocument`.
///
/// Returns the root DOM node (and optionally the subtree) to the caller.
/// Implicitly enables the DOM domain events for the current target.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetDocumentParams {
    /// The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the
    /// entire subtree or provide an integer larger than 0.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub depth: Option<i64>,
    /// Whether or not iframes and shadow roots should be traversed when returning the subtree
    /// (default is false).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pierce: Option<bool>,
}

/// The answer to `DOM.getDocument`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetDocumentReturns {
    /// Resulting node.
    pub root: Node,
}

impl GetDocumentParams {
    pub const METHOD: &'static str = "DOM.getDocument";
}

impl super::Command for GetDocumentParams {
    const METHOD: &'static str = "DOM.getDocument";
    type Returns = GetDocumentReturns;
}

/// Parameters of `DOM.getFlattenedDocument`.
///
/// Returns the root DOM node (and optionally the subtree) to the caller.
/// Deprecated, as it is not designed to work well with the rest of the DOM agent.
/// Use DOMSnapshot.captureSnapshot instead.
///
/// **Deprecated.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetFlattenedDocumentParams {
    /// The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the
    /// entire subtree or provide an integer larger than 0.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub depth: Option<i64>,
    /// Whether or not iframes and shadow roots should be traversed when returning the subtree
    /// (default is false).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pierce: Option<bool>,
}

/// The answer to `DOM.getFlattenedDocument`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetFlattenedDocumentReturns {
    /// Resulting node.
    pub nodes: Vec<Node>,
}

impl GetFlattenedDocumentParams {
    pub const METHOD: &'static str = "DOM.getFlattenedDocument";
}

impl super::Command for GetFlattenedDocumentParams {
    const METHOD: &'static str = "DOM.getFlattenedDocument";
    type Returns = GetFlattenedDocumentReturns;
}

/// Parameters of `DOM.getNodesForSubtreeByStyle`.
///
/// Finds nodes with a given computed style in a subtree.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetNodesForSubtreeByStyleParams {
    /// Node ID pointing to the root of a subtree.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    /// The style to filter nodes by (includes nodes if any of properties matches).
    #[serde(rename = "computedStyles")]
    pub computed_styles: Vec<CSSComputedStyleProperty>,
    /// Whether or not iframes and shadow roots in the same target should be traversed when returning the
    /// results (default is false).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pierce: Option<bool>,
}

/// The answer to `DOM.getNodesForSubtreeByStyle`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetNodesForSubtreeByStyleReturns {
    /// Resulting nodes.
    #[serde(rename = "nodeIds")]
    pub node_ids: Vec<NodeId>,
}

impl GetNodesForSubtreeByStyleParams {
    pub const METHOD: &'static str = "DOM.getNodesForSubtreeByStyle";
}

impl super::Command for GetNodesForSubtreeByStyleParams {
    const METHOD: &'static str = "DOM.getNodesForSubtreeByStyle";
    type Returns = GetNodesForSubtreeByStyleReturns;
}

/// Parameters of `DOM.getNodeForLocation`.
///
/// Returns node id at given location. Depending on whether DOM domain is enabled, nodeId is
/// either returned or not.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetNodeForLocationParams {
    /// X coordinate.
    pub x: i64,
    /// Y coordinate.
    pub y: i64,
    /// False to skip to the nearest non-UA shadow root ancestor (default: false).
    #[serde(
        rename = "includeUserAgentShadowDOM",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub include_user_agent_shadow_dom: Option<bool>,
    /// Whether to ignore pointer-events: none on elements and hit test them.
    #[serde(
        rename = "ignorePointerEventsNone",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub ignore_pointer_events_none: Option<bool>,
}

/// The answer to `DOM.getNodeForLocation`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetNodeForLocationReturns {
    /// Resulting node.
    #[serde(rename = "backendNodeId")]
    pub backend_node_id: BackendNodeId,
    /// Frame this node belongs to.
    #[serde(rename = "frameId")]
    pub frame_id: super::page::FrameId,
    /// Id of the node at given coordinates, only when enabled and requested document.
    #[serde(rename = "nodeId", default, skip_serializing_if = "Option::is_none")]
    pub node_id: Option<NodeId>,
}

impl GetNodeForLocationParams {
    pub const METHOD: &'static str = "DOM.getNodeForLocation";
}

impl super::Command for GetNodeForLocationParams {
    const METHOD: &'static str = "DOM.getNodeForLocation";
    type Returns = GetNodeForLocationReturns;
}

/// Parameters of `DOM.getOuterHTML`.
///
/// Returns node's HTML markup.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetOuterHTMLParams {
    /// Identifier of the node.
    #[serde(rename = "nodeId", default, skip_serializing_if = "Option::is_none")]
    pub node_id: Option<NodeId>,
    /// Identifier of the backend node.
    #[serde(
        rename = "backendNodeId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub backend_node_id: Option<BackendNodeId>,
    /// JavaScript object id of the node wrapper.
    #[serde(rename = "objectId", default, skip_serializing_if = "Option::is_none")]
    pub object_id: Option<super::runtime::RemoteObjectId>,
    /// Include all shadow roots. Equals to false if not specified.
    ///
    /// **Experimental.**
    #[serde(
        rename = "includeShadowDOM",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub include_shadow_dom: Option<bool>,
}

/// The answer to `DOM.getOuterHTML`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetOuterHTMLReturns {
    /// Outer HTML markup.
    #[serde(rename = "outerHTML")]
    pub outer_html: String,
}

impl GetOuterHTMLParams {
    pub const METHOD: &'static str = "DOM.getOuterHTML";
}

impl super::Command for GetOuterHTMLParams {
    const METHOD: &'static str = "DOM.getOuterHTML";
    type Returns = GetOuterHTMLReturns;
}

/// Parameters of `DOM.getRelayoutBoundary`.
///
/// Returns the id of the nearest ancestor that is a relayout boundary.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetRelayoutBoundaryParams {
    /// Id of the node.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
}

/// The answer to `DOM.getRelayoutBoundary`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetRelayoutBoundaryReturns {
    /// Relayout boundary node id for the given node.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
}

impl GetRelayoutBoundaryParams {
    pub const METHOD: &'static str = "DOM.getRelayoutBoundary";
}

impl super::Command for GetRelayoutBoundaryParams {
    const METHOD: &'static str = "DOM.getRelayoutBoundary";
    type Returns = GetRelayoutBoundaryReturns;
}

/// Parameters of `DOM.getSearchResults`.
///
/// Returns search results from given `fromIndex` to given `toIndex` from the search with the given
/// identifier.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetSearchResultsParams {
    /// Unique search session identifier.
    #[serde(rename = "searchId")]
    pub search_id: String,
    /// Start index of the search result to be returned.
    #[serde(rename = "fromIndex")]
    pub from_index: i64,
    /// End index of the search result to be returned.
    #[serde(rename = "toIndex")]
    pub to_index: i64,
}

/// The answer to `DOM.getSearchResults`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetSearchResultsReturns {
    /// Ids of the search result nodes.
    #[serde(rename = "nodeIds")]
    pub node_ids: Vec<NodeId>,
}

impl GetSearchResultsParams {
    pub const METHOD: &'static str = "DOM.getSearchResults";
}

impl super::Command for GetSearchResultsParams {
    const METHOD: &'static str = "DOM.getSearchResults";
    type Returns = GetSearchResultsReturns;
}

/// Parameters of `DOM.hideHighlight`.
///
/// Hides any highlight.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct HideHighlightParams {}

/// The answer to `DOM.hideHighlight`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct HideHighlightReturns {}

impl HideHighlightParams {
    pub const METHOD: &'static str = "DOM.hideHighlight";
}

impl super::Command for HideHighlightParams {
    const METHOD: &'static str = "DOM.hideHighlight";
    type Returns = HideHighlightReturns;
}

/// Parameters of `DOM.highlightNode`.
///
/// Highlights DOM node.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct HighlightNodeParams {}

/// The answer to `DOM.highlightNode`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct HighlightNodeReturns {}

impl HighlightNodeParams {
    pub const METHOD: &'static str = "DOM.highlightNode";
}

impl super::Command for HighlightNodeParams {
    const METHOD: &'static str = "DOM.highlightNode";
    type Returns = HighlightNodeReturns;
}

/// Parameters of `DOM.highlightRect`.
///
/// Highlights given rectangle.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct HighlightRectParams {}

/// The answer to `DOM.highlightRect`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct HighlightRectReturns {}

impl HighlightRectParams {
    pub const METHOD: &'static str = "DOM.highlightRect";
}

impl super::Command for HighlightRectParams {
    const METHOD: &'static str = "DOM.highlightRect";
    type Returns = HighlightRectReturns;
}

/// Parameters of `DOM.markUndoableState`.
///
/// Marks last undoable state.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct MarkUndoableStateParams {}

/// The answer to `DOM.markUndoableState`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct MarkUndoableStateReturns {}

impl MarkUndoableStateParams {
    pub const METHOD: &'static str = "DOM.markUndoableState";
}

impl super::Command for MarkUndoableStateParams {
    const METHOD: &'static str = "DOM.markUndoableState";
    type Returns = MarkUndoableStateReturns;
}

/// Parameters of `DOM.moveTo`.
///
/// Moves node into the new container, places it before the given anchor.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct MoveToParams {
    /// Id of the node to move.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    /// Id of the element to drop the moved node into.
    #[serde(rename = "targetNodeId")]
    pub target_node_id: NodeId,
    /// Drop node before this one (if absent, the moved node becomes the last child of
    /// `targetNodeId`).
    #[serde(
        rename = "insertBeforeNodeId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub insert_before_node_id: Option<NodeId>,
}

/// The answer to `DOM.moveTo`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct MoveToReturns {
    /// New id of the moved node.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
}

impl MoveToParams {
    pub const METHOD: &'static str = "DOM.moveTo";
}

impl super::Command for MoveToParams {
    const METHOD: &'static str = "DOM.moveTo";
    type Returns = MoveToReturns;
}

/// Parameters of `DOM.performSearch`.
///
/// Searches for a given string in the DOM tree. Use `getSearchResults` to access search results or
/// `cancelSearch` to end this search session.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct PerformSearchParams {
    /// Plain text or query selector or XPath search query.
    pub query: String,
    /// True to search in user agent shadow DOM.
    #[serde(
        rename = "includeUserAgentShadowDOM",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub include_user_agent_shadow_dom: Option<bool>,
}

/// The answer to `DOM.performSearch`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct PerformSearchReturns {
    /// Unique search session identifier.
    #[serde(rename = "searchId")]
    pub search_id: String,
    /// Number of search results.
    #[serde(rename = "resultCount")]
    pub result_count: i64,
}

impl PerformSearchParams {
    pub const METHOD: &'static str = "DOM.performSearch";
}

impl super::Command for PerformSearchParams {
    const METHOD: &'static str = "DOM.performSearch";
    type Returns = PerformSearchReturns;
}

/// Parameters of `DOM.pushNodeByPathToFrontend`.
///
/// Requests that the node is sent to the caller given its path. // FIXME, use XPath
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct PushNodeByPathToFrontendParams {
    /// Path to node in the proprietary format.
    pub path: String,
}

/// The answer to `DOM.pushNodeByPathToFrontend`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct PushNodeByPathToFrontendReturns {
    /// Id of the node for given path.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
}

impl PushNodeByPathToFrontendParams {
    pub const METHOD: &'static str = "DOM.pushNodeByPathToFrontend";
}

impl super::Command for PushNodeByPathToFrontendParams {
    const METHOD: &'static str = "DOM.pushNodeByPathToFrontend";
    type Returns = PushNodeByPathToFrontendReturns;
}

/// Parameters of `DOM.pushNodesByBackendIdsToFrontend`.
///
/// Requests that a batch of nodes is sent to the caller given their backend node ids.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct PushNodesByBackendIdsToFrontendParams {
    /// The array of backend node ids.
    #[serde(rename = "backendNodeIds")]
    pub backend_node_ids: Vec<BackendNodeId>,
}

/// The answer to `DOM.pushNodesByBackendIdsToFrontend`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct PushNodesByBackendIdsToFrontendReturns {
    /// The array of ids of pushed nodes that correspond to the backend ids specified in
    /// backendNodeIds.
    #[serde(rename = "nodeIds")]
    pub node_ids: Vec<NodeId>,
}

impl PushNodesByBackendIdsToFrontendParams {
    pub const METHOD: &'static str = "DOM.pushNodesByBackendIdsToFrontend";
}

impl super::Command for PushNodesByBackendIdsToFrontendParams {
    const METHOD: &'static str = "DOM.pushNodesByBackendIdsToFrontend";
    type Returns = PushNodesByBackendIdsToFrontendReturns;
}

/// Parameters of `DOM.querySelector`.
///
/// Executes `querySelector` on a given node.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct QuerySelectorParams {
    /// Id of the node to query upon.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    /// Selector string.
    pub selector: String,
}

/// The answer to `DOM.querySelector`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct QuerySelectorReturns {
    /// Query selector result.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
}

impl QuerySelectorParams {
    pub const METHOD: &'static str = "DOM.querySelector";
}

impl super::Command for QuerySelectorParams {
    const METHOD: &'static str = "DOM.querySelector";
    type Returns = QuerySelectorReturns;
}

/// Parameters of `DOM.querySelectorAll`.
///
/// Executes `querySelectorAll` on a given node.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct QuerySelectorAllParams {
    /// Id of the node to query upon.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    /// Selector string.
    pub selector: String,
}

/// The answer to `DOM.querySelectorAll`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct QuerySelectorAllReturns {
    /// Query selector result.
    #[serde(rename = "nodeIds")]
    pub node_ids: Vec<NodeId>,
}

impl QuerySelectorAllParams {
    pub const METHOD: &'static str = "DOM.querySelectorAll";
}

impl super::Command for QuerySelectorAllParams {
    const METHOD: &'static str = "DOM.querySelectorAll";
    type Returns = QuerySelectorAllReturns;
}

/// Parameters of `DOM.getTopLayerElements`.
///
/// Returns NodeIds of current top layer elements.
/// Top layer is rendered closest to the user within a viewport, therefore its elements always
/// appear on top of all other content.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetTopLayerElementsParams {}

/// The answer to `DOM.getTopLayerElements`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetTopLayerElementsReturns {
    /// NodeIds of top layer elements
    #[serde(rename = "nodeIds")]
    pub node_ids: Vec<NodeId>,
}

impl GetTopLayerElementsParams {
    pub const METHOD: &'static str = "DOM.getTopLayerElements";
}

impl super::Command for GetTopLayerElementsParams {
    const METHOD: &'static str = "DOM.getTopLayerElements";
    type Returns = GetTopLayerElementsReturns;
}

/// Parameters of `DOM.getElementByRelation`.
///
/// Returns the NodeId of the matched element according to certain relations.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GetElementByRelationParams {
    /// Id of the node from which to query the relation.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    /// Type of relation to get.
    pub relation: GetElementByRelationRelation,
}

/// Values of `GetElementByRelation`'s `relation`.
///
/// Type of relation to get.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum GetElementByRelationRelation {
    /// `PopoverTarget`
    PopoverTarget,
    /// `InterestTarget`
    InterestTarget,
    /// `CommandFor`
    CommandFor,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    GetElementByRelationRelation {
        PopoverTarget => "PopoverTarget",
        InterestTarget => "InterestTarget",
        CommandFor => "CommandFor",
    }
}

/// The answer to `DOM.getElementByRelation`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetElementByRelationReturns {
    /// NodeId of the element matching the queried relation.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
}

impl GetElementByRelationParams {
    pub const METHOD: &'static str = "DOM.getElementByRelation";
}

impl super::Command for GetElementByRelationParams {
    const METHOD: &'static str = "DOM.getElementByRelation";
    type Returns = GetElementByRelationReturns;
}

/// Parameters of `DOM.redo`.
///
/// Re-does the last undone action.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RedoParams {}

/// The answer to `DOM.redo`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RedoReturns {}

impl RedoParams {
    pub const METHOD: &'static str = "DOM.redo";
}

impl super::Command for RedoParams {
    const METHOD: &'static str = "DOM.redo";
    type Returns = RedoReturns;
}

/// Parameters of `DOM.removeAttribute`.
///
/// Removes attribute with given name from an element with given id.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RemoveAttributeParams {
    /// Id of the element to remove attribute from.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    /// Name of the attribute to remove.
    pub name: String,
}

/// The answer to `DOM.removeAttribute`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RemoveAttributeReturns {}

impl RemoveAttributeParams {
    pub const METHOD: &'static str = "DOM.removeAttribute";
}

impl super::Command for RemoveAttributeParams {
    const METHOD: &'static str = "DOM.removeAttribute";
    type Returns = RemoveAttributeReturns;
}

/// Parameters of `DOM.removeNode`.
///
/// Removes node with given id.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RemoveNodeParams {
    /// Id of the node to remove.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
}

/// The answer to `DOM.removeNode`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RemoveNodeReturns {}

impl RemoveNodeParams {
    pub const METHOD: &'static str = "DOM.removeNode";
}

impl super::Command for RemoveNodeParams {
    const METHOD: &'static str = "DOM.removeNode";
    type Returns = RemoveNodeReturns;
}

/// Parameters of `DOM.requestChildNodes`.
///
/// Requests that children of the node with given id are returned to the caller in form of
/// `setChildNodes` events where not only immediate children are retrieved, but all children down to
/// the specified depth.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RequestChildNodesParams {
    /// Id of the node to get children for.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    /// The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the
    /// entire subtree or provide an integer larger than 0.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub depth: Option<i64>,
    /// Whether or not iframes and shadow roots should be traversed when returning the sub-tree
    /// (default is false).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pierce: Option<bool>,
}

/// The answer to `DOM.requestChildNodes`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RequestChildNodesReturns {}

impl RequestChildNodesParams {
    pub const METHOD: &'static str = "DOM.requestChildNodes";
}

impl super::Command for RequestChildNodesParams {
    const METHOD: &'static str = "DOM.requestChildNodes";
    type Returns = RequestChildNodesReturns;
}

/// Parameters of `DOM.requestNode`.
///
/// Requests that the node is sent to the caller given the JavaScript node object reference. All
/// nodes that form the path from the node to the root are also sent to the client as a series of
/// `setChildNodes` notifications.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RequestNodeParams {
    /// JavaScript object id to convert into node.
    #[serde(rename = "objectId")]
    pub object_id: super::runtime::RemoteObjectId,
}

/// The answer to `DOM.requestNode`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RequestNodeReturns {
    /// Node id for given object.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
}

impl RequestNodeParams {
    pub const METHOD: &'static str = "DOM.requestNode";
}

impl super::Command for RequestNodeParams {
    const METHOD: &'static str = "DOM.requestNode";
    type Returns = RequestNodeReturns;
}

/// Parameters of `DOM.resolveNode`.
///
/// Resolves the JavaScript node object for a given NodeId or BackendNodeId.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ResolveNodeParams {
    /// Id of the node to resolve.
    #[serde(rename = "nodeId", default, skip_serializing_if = "Option::is_none")]
    pub node_id: Option<NodeId>,
    /// Backend identifier of the node to resolve.
    #[serde(
        rename = "backendNodeId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub backend_node_id: Option<BackendNodeId>,
    /// Symbolic group name that can be used to release multiple objects.
    #[serde(
        rename = "objectGroup",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub object_group: Option<String>,
    /// Execution context in which to resolve the node.
    #[serde(
        rename = "executionContextId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub execution_context_id: Option<super::runtime::ExecutionContextId>,
}

/// The answer to `DOM.resolveNode`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ResolveNodeReturns {
    /// JavaScript object wrapper for given node.
    pub object: super::runtime::RemoteObject,
}

impl ResolveNodeParams {
    pub const METHOD: &'static str = "DOM.resolveNode";
}

impl super::Command for ResolveNodeParams {
    const METHOD: &'static str = "DOM.resolveNode";
    type Returns = ResolveNodeReturns;
}

/// Parameters of `DOM.setAttributeValue`.
///
/// Sets attribute for an element with given id.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetAttributeValueParams {
    /// Id of the element to set attribute for.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    /// Attribute name.
    pub name: String,
    /// Attribute value.
    pub value: String,
}

/// The answer to `DOM.setAttributeValue`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetAttributeValueReturns {}

impl SetAttributeValueParams {
    pub const METHOD: &'static str = "DOM.setAttributeValue";
}

impl super::Command for SetAttributeValueParams {
    const METHOD: &'static str = "DOM.setAttributeValue";
    type Returns = SetAttributeValueReturns;
}

/// Parameters of `DOM.setAttributesAsText`.
///
/// Sets attributes on element with given id. This method is useful when user edits some existing
/// attribute value and types in several attribute name/value pairs.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetAttributesAsTextParams {
    /// Id of the element to set attributes for.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    /// Text with a number of attributes. Will parse this text using HTML parser.
    pub text: String,
    /// Attribute name to replace with new attributes derived from text in case text parsed
    /// successfully.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// The answer to `DOM.setAttributesAsText`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetAttributesAsTextReturns {}

impl SetAttributesAsTextParams {
    pub const METHOD: &'static str = "DOM.setAttributesAsText";
}

impl super::Command for SetAttributesAsTextParams {
    const METHOD: &'static str = "DOM.setAttributesAsText";
    type Returns = SetAttributesAsTextReturns;
}

/// Parameters of `DOM.setFileInputFiles`.
///
/// Sets files for the given file input element.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetFileInputFilesParams {
    /// Array of file paths to set.
    pub files: Vec<String>,
    /// Identifier of the node.
    #[serde(rename = "nodeId", default, skip_serializing_if = "Option::is_none")]
    pub node_id: Option<NodeId>,
    /// Identifier of the backend node.
    #[serde(
        rename = "backendNodeId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub backend_node_id: Option<BackendNodeId>,
    /// JavaScript object id of the node wrapper.
    #[serde(rename = "objectId", default, skip_serializing_if = "Option::is_none")]
    pub object_id: Option<super::runtime::RemoteObjectId>,
}

/// The answer to `DOM.setFileInputFiles`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetFileInputFilesReturns {}

impl SetFileInputFilesParams {
    pub const METHOD: &'static str = "DOM.setFileInputFiles";
}

impl super::Command for SetFileInputFilesParams {
    const METHOD: &'static str = "DOM.setFileInputFiles";
    type Returns = SetFileInputFilesReturns;
}

/// Parameters of `DOM.setNodeStackTracesEnabled`.
///
/// Sets if stack traces should be captured for Nodes. See `Node.getNodeStackTraces`. Default is disabled.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetNodeStackTracesEnabledParams {
    /// Enable or disable.
    pub enable: bool,
}

/// The answer to `DOM.setNodeStackTracesEnabled`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetNodeStackTracesEnabledReturns {}

impl SetNodeStackTracesEnabledParams {
    pub const METHOD: &'static str = "DOM.setNodeStackTracesEnabled";
}

impl super::Command for SetNodeStackTracesEnabledParams {
    const METHOD: &'static str = "DOM.setNodeStackTracesEnabled";
    type Returns = SetNodeStackTracesEnabledReturns;
}

/// Parameters of `DOM.getNodeStackTraces`.
///
/// Gets stack traces associated with a Node. As of now, only provides stack trace for Node creation.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetNodeStackTracesParams {
    /// Id of the node to get stack traces for.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
}

/// The answer to `DOM.getNodeStackTraces`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetNodeStackTracesReturns {
    /// Creation stack trace, if available.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub creation: Option<super::runtime::StackTrace>,
}

impl GetNodeStackTracesParams {
    pub const METHOD: &'static str = "DOM.getNodeStackTraces";
}

impl super::Command for GetNodeStackTracesParams {
    const METHOD: &'static str = "DOM.getNodeStackTraces";
    type Returns = GetNodeStackTracesReturns;
}

/// Parameters of `DOM.getFileInfo`.
///
/// Returns file information for the given
/// File wrapper.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetFileInfoParams {
    /// JavaScript object id of the node wrapper.
    #[serde(rename = "objectId")]
    pub object_id: super::runtime::RemoteObjectId,
}

/// The answer to `DOM.getFileInfo`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetFileInfoReturns {
    pub path: String,
}

impl GetFileInfoParams {
    pub const METHOD: &'static str = "DOM.getFileInfo";
}

impl super::Command for GetFileInfoParams {
    const METHOD: &'static str = "DOM.getFileInfo";
    type Returns = GetFileInfoReturns;
}

/// Parameters of `DOM.getDetachedDomNodes`.
///
/// Returns list of detached nodes
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetDetachedDomNodesParams {}

/// The answer to `DOM.getDetachedDomNodes`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetDetachedDomNodesReturns {
    /// The list of detached nodes
    #[serde(rename = "detachedNodes")]
    pub detached_nodes: Vec<DetachedElementInfo>,
}

impl GetDetachedDomNodesParams {
    pub const METHOD: &'static str = "DOM.getDetachedDomNodes";
}

impl super::Command for GetDetachedDomNodesParams {
    const METHOD: &'static str = "DOM.getDetachedDomNodes";
    type Returns = GetDetachedDomNodesReturns;
}

/// Parameters of `DOM.setInspectedNode`.
///
/// Enables console to refer to the node with given id via $x (see Command Line API for more details
/// $x functions).
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetInspectedNodeParams {
    /// DOM node id to be accessible by means of $x command line API.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
}

/// The answer to `DOM.setInspectedNode`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetInspectedNodeReturns {}

impl SetInspectedNodeParams {
    pub const METHOD: &'static str = "DOM.setInspectedNode";
}

impl super::Command for SetInspectedNodeParams {
    const METHOD: &'static str = "DOM.setInspectedNode";
    type Returns = SetInspectedNodeReturns;
}

/// Parameters of `DOM.setNodeName`.
///
/// Sets node name for a node with given id.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetNodeNameParams {
    /// Id of the node to set name for.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    /// New node's name.
    pub name: String,
}

/// The answer to `DOM.setNodeName`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetNodeNameReturns {
    /// New node's id.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
}

impl SetNodeNameParams {
    pub const METHOD: &'static str = "DOM.setNodeName";
}

impl super::Command for SetNodeNameParams {
    const METHOD: &'static str = "DOM.setNodeName";
    type Returns = SetNodeNameReturns;
}

/// Parameters of `DOM.setNodeValue`.
///
/// Sets node value for a node with given id.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetNodeValueParams {
    /// Id of the node to set value for.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    /// New node's value.
    pub value: String,
}

/// The answer to `DOM.setNodeValue`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetNodeValueReturns {}

impl SetNodeValueParams {
    pub const METHOD: &'static str = "DOM.setNodeValue";
}

impl super::Command for SetNodeValueParams {
    const METHOD: &'static str = "DOM.setNodeValue";
    type Returns = SetNodeValueReturns;
}

/// Parameters of `DOM.setOuterHTML`.
///
/// Sets node HTML markup, returns new node id.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetOuterHTMLParams {
    /// Id of the node to set markup for.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    /// Outer HTML markup to set.
    #[serde(rename = "outerHTML")]
    pub outer_html: String,
}

/// The answer to `DOM.setOuterHTML`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetOuterHTMLReturns {}

impl SetOuterHTMLParams {
    pub const METHOD: &'static str = "DOM.setOuterHTML";
}

impl super::Command for SetOuterHTMLParams {
    const METHOD: &'static str = "DOM.setOuterHTML";
    type Returns = SetOuterHTMLReturns;
}

/// Parameters of `DOM.undo`.
///
/// Undoes the last performed action.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct UndoParams {}

/// The answer to `DOM.undo`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct UndoReturns {}

impl UndoParams {
    pub const METHOD: &'static str = "DOM.undo";
}

impl super::Command for UndoParams {
    const METHOD: &'static str = "DOM.undo";
    type Returns = UndoReturns;
}

/// Parameters of `DOM.getFrameOwner`.
///
/// Returns iframe node that owns iframe with the given domain.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetFrameOwnerParams {
    #[serde(rename = "frameId")]
    pub frame_id: super::page::FrameId,
}

/// The answer to `DOM.getFrameOwner`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetFrameOwnerReturns {
    /// Resulting node.
    #[serde(rename = "backendNodeId")]
    pub backend_node_id: BackendNodeId,
    /// Id of the node at given coordinates, only when enabled and requested document.
    #[serde(rename = "nodeId", default, skip_serializing_if = "Option::is_none")]
    pub node_id: Option<NodeId>,
}

impl GetFrameOwnerParams {
    pub const METHOD: &'static str = "DOM.getFrameOwner";
}

impl super::Command for GetFrameOwnerParams {
    const METHOD: &'static str = "DOM.getFrameOwner";
    type Returns = GetFrameOwnerReturns;
}

/// Parameters of `DOM.getContainerForNode`.
///
/// Returns the query container of the given node based on container query
/// conditions: containerName, physical and logical axes, and whether it queries
/// scroll-state or anchored elements. If no axes are provided and
/// queriesScrollState is false, the style container is returned, which is the
/// direct parent or the closest element with a matching container-name.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetContainerForNodeParams {
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    #[serde(
        rename = "containerName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub container_name: Option<String>,
    #[serde(
        rename = "physicalAxes",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub physical_axes: Option<PhysicalAxes>,
    #[serde(
        rename = "logicalAxes",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub logical_axes: Option<LogicalAxes>,
    #[serde(
        rename = "queriesScrollState",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub queries_scroll_state: Option<bool>,
    #[serde(
        rename = "queriesAnchored",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub queries_anchored: Option<bool>,
}

/// The answer to `DOM.getContainerForNode`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetContainerForNodeReturns {
    /// The container node for the given node, or null if not found.
    #[serde(rename = "nodeId", default, skip_serializing_if = "Option::is_none")]
    pub node_id: Option<NodeId>,
}

impl GetContainerForNodeParams {
    pub const METHOD: &'static str = "DOM.getContainerForNode";
}

impl super::Command for GetContainerForNodeParams {
    const METHOD: &'static str = "DOM.getContainerForNode";
    type Returns = GetContainerForNodeReturns;
}

/// Parameters of `DOM.getQueryingDescendantsForContainer`.
///
/// Returns the descendants of a container query container that have
/// container queries against this container.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetQueryingDescendantsForContainerParams {
    /// Id of the container node to find querying descendants from.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
}

/// The answer to `DOM.getQueryingDescendantsForContainer`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetQueryingDescendantsForContainerReturns {
    /// Descendant nodes with container queries against the given container.
    #[serde(rename = "nodeIds")]
    pub node_ids: Vec<NodeId>,
}

impl GetQueryingDescendantsForContainerParams {
    pub const METHOD: &'static str = "DOM.getQueryingDescendantsForContainer";
}

impl super::Command for GetQueryingDescendantsForContainerParams {
    const METHOD: &'static str = "DOM.getQueryingDescendantsForContainer";
    type Returns = GetQueryingDescendantsForContainerReturns;
}

/// Parameters of `DOM.getAnchorElement`.
///
/// Returns the target anchor element of the given anchor query according to
/// https://www.w3.org/TR/css-anchor-position-1/#target.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAnchorElementParams {
    /// Id of the positioned element from which to find the anchor.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    /// An optional anchor specifier, as defined in
    /// https://www.w3.org/TR/css-anchor-position-1/#anchor-specifier.
    /// If not provided, it will return the implicit anchor element for
    /// the given positioned element.
    #[serde(
        rename = "anchorSpecifier",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub anchor_specifier: Option<String>,
}

/// The answer to `DOM.getAnchorElement`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAnchorElementReturns {
    /// The anchor element of the given anchor query.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
}

impl GetAnchorElementParams {
    pub const METHOD: &'static str = "DOM.getAnchorElement";
}

impl super::Command for GetAnchorElementParams {
    const METHOD: &'static str = "DOM.getAnchorElement";
    type Returns = GetAnchorElementReturns;
}

/// Parameters of `DOM.forceShowPopover`.
///
/// When enabling, this API force-opens the popover identified by nodeId
/// and keeps it open until disabled.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ForceShowPopoverParams {
    /// Id of the popover HTMLElement
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    /// If true, opens the popover and keeps it open. If false, closes the
    /// popover if it was previously force-opened.
    pub enable: bool,
    /// Optional ID of the element invoking this popover, used to establish the implicit anchor.
    /// If not provided, it will fall back to the first invoker in the document, preferring
    /// elements with a popovertarget attribute over those with a commandfor attribute. Note that
    /// if there are multiple invokers, this is just an estimate.
    #[serde(
        rename = "invokerNodeId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub invoker_node_id: Option<BackendNodeId>,
}

/// The answer to `DOM.forceShowPopover`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ForceShowPopoverReturns {
    /// List of popovers that were closed in order to respect popover stacking order.
    #[serde(rename = "nodeIds")]
    pub node_ids: Vec<NodeId>,
}

impl ForceShowPopoverParams {
    pub const METHOD: &'static str = "DOM.forceShowPopover";
}

impl super::Command for ForceShowPopoverParams {
    const METHOD: &'static str = "DOM.forceShowPopover";
    type Returns = ForceShowPopoverReturns;
}

/// Parameters of `DOM.getImplicitAnchorCandidates`.
///
/// Returns candidate nodes that are configured as triggers for the given popover.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetImplicitAnchorCandidatesParams {
    /// Id of the popover HTMLElement.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
}

/// The answer to `DOM.getImplicitAnchorCandidates`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetImplicitAnchorCandidatesReturns {
    /// Candidate elements that can invoke this popover.
    #[serde(rename = "backendNodeIds")]
    pub backend_node_ids: Vec<BackendNodeId>,
}

impl GetImplicitAnchorCandidatesParams {
    pub const METHOD: &'static str = "DOM.getImplicitAnchorCandidates";
}

impl super::Command for GetImplicitAnchorCandidatesParams {
    const METHOD: &'static str = "DOM.getImplicitAnchorCandidates";
    type Returns = GetImplicitAnchorCandidatesReturns;
}

/// Parameters of `DOM.forceShowInterest`.
///
/// When enabling, this API forces an element to gain interest in its target,
/// keeping interest active until disabled.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ForceShowInterestParams {
    /// Id of the interest invoker HTMLElement.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    /// If true, opens and holds interest. If false, releases forced interest.
    pub enable: bool,
}

/// The answer to `DOM.forceShowInterest`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ForceShowInterestReturns {}

impl ForceShowInterestParams {
    pub const METHOD: &'static str = "DOM.forceShowInterest";
}

impl super::Command for ForceShowInterestParams {
    const METHOD: &'static str = "DOM.forceShowInterest";
    type Returns = ForceShowInterestReturns;
}

/// Parameters of `DOM.setTextMarker`.
///
/// Sets a spelling or grammar error marker on the given range of text.
/// See https://github.com/Igalia/explainers/blob/main/force-spelling-grammar-markers/README.md
/// Note: exactly one between nodeId, backendNodeId and objectId should be passed
/// to identify the node.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SetTextMarkerParams {
    /// Identifier of the node.
    #[serde(rename = "nodeId", default, skip_serializing_if = "Option::is_none")]
    pub node_id: Option<NodeId>,
    /// Identifier of the backend node.
    #[serde(
        rename = "backendNodeId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub backend_node_id: Option<BackendNodeId>,
    /// JavaScript object id of the node wrapper.
    #[serde(rename = "objectId", default, skip_serializing_if = "Option::is_none")]
    pub object_id: Option<super::runtime::RemoteObjectId>,
    /// The type of marker to set on the given range of text.
    #[serde(rename = "type")]
    pub type_: SetTextMarkerType,
    /// Start offset into the element's rendered text in UTF-16 code units.
    /// For a text control, an offset into the control's value.
    /// Offsets count text in DOM order and do not enter shadow trees.
    /// To mark text inside a shadow tree, pass the element inside the shadow tree.
    pub start: i64,
    /// End offset (exclusive) in the same units and space as start.
    pub end: i64,
}

/// Values of `SetTextMarker`'s `type`.
///
/// The type of marker to set on the given range of text.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SetTextMarkerType {
    /// `spelling`
    Spelling,
    /// `grammar`
    Grammar,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    SetTextMarkerType {
        Spelling => "spelling",
        Grammar => "grammar",
    }
}

/// The answer to `DOM.setTextMarker`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetTextMarkerReturns {}

impl SetTextMarkerParams {
    pub const METHOD: &'static str = "DOM.setTextMarker";
}

impl super::Command for SetTextMarkerParams {
    const METHOD: &'static str = "DOM.setTextMarker";
    type Returns = SetTextMarkerReturns;
}

/// Parameters of `DOM.clearTextMarkers`.
///
/// Clears the spelling and grammar error text markers overlapping the ranges
/// set by setTextMarker in this session. These markers are also removed when
/// the DOM domain is disabled or the session ends.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearTextMarkersParams {}

/// The answer to `DOM.clearTextMarkers`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearTextMarkersReturns {}

impl ClearTextMarkersParams {
    pub const METHOD: &'static str = "DOM.clearTextMarkers";
}

impl super::Command for ClearTextMarkersParams {
    const METHOD: &'static str = "DOM.clearTextMarkers";
    type Returns = ClearTextMarkersReturns;
}

/// The event `DOM.attributeModified`.
///
/// Fired when `Element`'s attribute is modified.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AttributeModifiedEvent {
    /// Id of the node that has changed.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    /// Attribute name.
    pub name: String,
    /// Attribute value.
    pub value: String,
}

impl AttributeModifiedEvent {
    pub const NAME: &'static str = "DOM.attributeModified";
}

impl super::Event for AttributeModifiedEvent {
    const NAME: &'static str = "DOM.attributeModified";
}

/// The event `DOM.adoptedStyleSheetsModified`.
///
/// Fired when `Element`'s adoptedStyleSheets are modified.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AdoptedStyleSheetsModifiedEvent {
    /// Id of the node that has changed.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    /// New adoptedStyleSheets array.
    ///
    /// **Experimental.**
    #[serde(rename = "adoptedStyleSheets")]
    pub adopted_style_sheets: Vec<StyleSheetId>,
}

impl AdoptedStyleSheetsModifiedEvent {
    pub const NAME: &'static str = "DOM.adoptedStyleSheetsModified";
}

impl super::Event for AdoptedStyleSheetsModifiedEvent {
    const NAME: &'static str = "DOM.adoptedStyleSheetsModified";
}

/// The event `DOM.attributeRemoved`.
///
/// Fired when `Element`'s attribute is removed.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AttributeRemovedEvent {
    /// Id of the node that has changed.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    /// A ttribute name.
    pub name: String,
}

impl AttributeRemovedEvent {
    pub const NAME: &'static str = "DOM.attributeRemoved";
}

impl super::Event for AttributeRemovedEvent {
    const NAME: &'static str = "DOM.attributeRemoved";
}

/// The event `DOM.characterDataModified`.
///
/// Mirrors `DOMCharacterDataModified` event.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CharacterDataModifiedEvent {
    /// Id of the node that has changed.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    /// New text value.
    #[serde(rename = "characterData")]
    pub character_data: String,
}

impl CharacterDataModifiedEvent {
    pub const NAME: &'static str = "DOM.characterDataModified";
}

impl super::Event for CharacterDataModifiedEvent {
    const NAME: &'static str = "DOM.characterDataModified";
}

/// The event `DOM.childNodeCountUpdated`.
///
/// Fired when `Container`'s child node count has changed.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ChildNodeCountUpdatedEvent {
    /// Id of the node that has changed.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    /// New node count.
    #[serde(rename = "childNodeCount")]
    pub child_node_count: i64,
}

impl ChildNodeCountUpdatedEvent {
    pub const NAME: &'static str = "DOM.childNodeCountUpdated";
}

impl super::Event for ChildNodeCountUpdatedEvent {
    const NAME: &'static str = "DOM.childNodeCountUpdated";
}

/// The event `DOM.childNodeInserted`.
///
/// Mirrors `DOMNodeInserted` event.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ChildNodeInsertedEvent {
    /// Id of the node that has changed.
    #[serde(rename = "parentNodeId")]
    pub parent_node_id: NodeId,
    /// Id of the previous sibling.
    #[serde(rename = "previousNodeId")]
    pub previous_node_id: NodeId,
    /// Inserted node data.
    pub node: Node,
}

impl ChildNodeInsertedEvent {
    pub const NAME: &'static str = "DOM.childNodeInserted";
}

impl super::Event for ChildNodeInsertedEvent {
    const NAME: &'static str = "DOM.childNodeInserted";
}

/// The event `DOM.childNodeRemoved`.
///
/// Mirrors `DOMNodeRemoved` event.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ChildNodeRemovedEvent {
    /// Parent id.
    #[serde(rename = "parentNodeId")]
    pub parent_node_id: NodeId,
    /// Id of the node that has been removed.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
}

impl ChildNodeRemovedEvent {
    pub const NAME: &'static str = "DOM.childNodeRemoved";
}

impl super::Event for ChildNodeRemovedEvent {
    const NAME: &'static str = "DOM.childNodeRemoved";
}

/// The event `DOM.distributedNodesUpdated`.
///
/// Called when distribution is changed.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DistributedNodesUpdatedEvent {
    /// Insertion point where distributed nodes were updated.
    #[serde(rename = "insertionPointId")]
    pub insertion_point_id: NodeId,
    /// Distributed nodes for given insertion point.
    #[serde(rename = "distributedNodes")]
    pub distributed_nodes: Vec<BackendNode>,
}

impl DistributedNodesUpdatedEvent {
    pub const NAME: &'static str = "DOM.distributedNodesUpdated";
}

impl super::Event for DistributedNodesUpdatedEvent {
    const NAME: &'static str = "DOM.distributedNodesUpdated";
}

/// The event `DOM.documentUpdated`.
///
/// Fired when `Document` has been totally updated. Node ids are no longer valid.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentUpdatedEvent {}

impl DocumentUpdatedEvent {
    pub const NAME: &'static str = "DOM.documentUpdated";
}

impl super::Event for DocumentUpdatedEvent {
    const NAME: &'static str = "DOM.documentUpdated";
}

/// The event `DOM.inlineStyleInvalidated`.
///
/// Fired when `Element`'s inline style is modified via a CSS property modification.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineStyleInvalidatedEvent {
    /// Ids of the nodes for which the inline styles have been invalidated.
    #[serde(rename = "nodeIds")]
    pub node_ids: Vec<NodeId>,
}

impl InlineStyleInvalidatedEvent {
    pub const NAME: &'static str = "DOM.inlineStyleInvalidated";
}

impl super::Event for InlineStyleInvalidatedEvent {
    const NAME: &'static str = "DOM.inlineStyleInvalidated";
}

/// The event `DOM.pseudoElementAdded`.
///
/// Called when a pseudo element is added to an element.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct PseudoElementAddedEvent {
    /// Pseudo element's parent element id.
    #[serde(rename = "parentId")]
    pub parent_id: NodeId,
    /// The added pseudo element.
    #[serde(rename = "pseudoElement")]
    pub pseudo_element: Node,
}

impl PseudoElementAddedEvent {
    pub const NAME: &'static str = "DOM.pseudoElementAdded";
}

impl super::Event for PseudoElementAddedEvent {
    const NAME: &'static str = "DOM.pseudoElementAdded";
}

/// The event `DOM.topLayerElementsUpdated`.
///
/// Called when top layer elements are changed.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct TopLayerElementsUpdatedEvent {}

impl TopLayerElementsUpdatedEvent {
    pub const NAME: &'static str = "DOM.topLayerElementsUpdated";
}

impl super::Event for TopLayerElementsUpdatedEvent {
    const NAME: &'static str = "DOM.topLayerElementsUpdated";
}

/// The event `DOM.scrollableFlagUpdated`.
///
/// Fired when a node's scrollability state changes.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ScrollableFlagUpdatedEvent {
    /// The id of the node.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    /// If the node is scrollable.
    #[serde(rename = "isScrollable")]
    pub is_scrollable: bool,
}

impl ScrollableFlagUpdatedEvent {
    pub const NAME: &'static str = "DOM.scrollableFlagUpdated";
}

impl super::Event for ScrollableFlagUpdatedEvent {
    const NAME: &'static str = "DOM.scrollableFlagUpdated";
}

/// The event `DOM.adRelatedStateUpdated`.
///
/// Fired when a node's ad related state changes.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AdRelatedStateUpdatedEvent {
    /// The id of the node.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    /// The provenance of the ad related node, if it is ad related.
    #[serde(
        rename = "adProvenance",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub ad_provenance: Option<super::network::AdProvenance>,
}

impl AdRelatedStateUpdatedEvent {
    pub const NAME: &'static str = "DOM.adRelatedStateUpdated";
}

impl super::Event for AdRelatedStateUpdatedEvent {
    const NAME: &'static str = "DOM.adRelatedStateUpdated";
}

/// The event `DOM.affectedByStartingStylesFlagUpdated`.
///
/// Fired when a node's starting styles changes.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AffectedByStartingStylesFlagUpdatedEvent {
    /// The id of the node.
    #[serde(rename = "nodeId")]
    pub node_id: NodeId,
    /// If the node has starting styles.
    #[serde(rename = "affectedByStartingStyles")]
    pub affected_by_starting_styles: bool,
}

impl AffectedByStartingStylesFlagUpdatedEvent {
    pub const NAME: &'static str = "DOM.affectedByStartingStylesFlagUpdated";
}

impl super::Event for AffectedByStartingStylesFlagUpdatedEvent {
    const NAME: &'static str = "DOM.affectedByStartingStylesFlagUpdated";
}

/// The event `DOM.pseudoElementRemoved`.
///
/// Called when a pseudo element is removed from an element.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct PseudoElementRemovedEvent {
    /// Pseudo element's parent element id.
    #[serde(rename = "parentId")]
    pub parent_id: NodeId,
    /// The removed pseudo element id.
    #[serde(rename = "pseudoElementId")]
    pub pseudo_element_id: NodeId,
}

impl PseudoElementRemovedEvent {
    pub const NAME: &'static str = "DOM.pseudoElementRemoved";
}

impl super::Event for PseudoElementRemovedEvent {
    const NAME: &'static str = "DOM.pseudoElementRemoved";
}

/// The event `DOM.setChildNodes`.
///
/// Fired when backend wants to provide client with the missing DOM structure. This happens upon
/// most of the calls requesting node ids.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetChildNodesEvent {
    /// Parent node id to populate with children.
    #[serde(rename = "parentId")]
    pub parent_id: NodeId,
    /// Child nodes array.
    pub nodes: Vec<Node>,
}

impl SetChildNodesEvent {
    pub const NAME: &'static str = "DOM.setChildNodes";
}

impl super::Event for SetChildNodesEvent {
    const NAME: &'static str = "DOM.setChildNodes";
}

/// The event `DOM.shadowRootPopped`.
///
/// Called when shadow root is popped from the element.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ShadowRootPoppedEvent {
    /// Host element id.
    #[serde(rename = "hostId")]
    pub host_id: NodeId,
    /// Shadow root id.
    #[serde(rename = "rootId")]
    pub root_id: NodeId,
}

impl ShadowRootPoppedEvent {
    pub const NAME: &'static str = "DOM.shadowRootPopped";
}

impl super::Event for ShadowRootPoppedEvent {
    const NAME: &'static str = "DOM.shadowRootPopped";
}

/// The event `DOM.shadowRootPushed`.
///
/// Called when shadow root is pushed into the element.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ShadowRootPushedEvent {
    /// Host element id.
    #[serde(rename = "hostId")]
    pub host_id: NodeId,
    /// Shadow root.
    pub root: Node,
}

impl ShadowRootPushedEvent {
    pub const NAME: &'static str = "DOM.shadowRootPushed";
}

impl super::Event for ShadowRootPushedEvent {
    const NAME: &'static str = "DOM.shadowRootPushed";
}
