// Generated by eludite-cdp-generator from devtools-protocol 0.0.1709723 (protocol/cdp/PIN). Do not edit:
// change the generator or the pin and run `cargo run -p eludite-cdp-generator`.
//! The CDP domain `DOMStorage`.
//!
//! Query and modify DOM storage.
//!
//! **Experimental.**

#![allow(
    clippy::upper_case_acronyms,
    clippy::doc_lazy_continuation,
    clippy::doc_overindented_list_items,
    clippy::large_enum_variant,
    clippy::empty_docs,
    clippy::struct_excessive_bools,
    rustdoc::bare_urls,
    rustdoc::broken_intra_doc_links,
    rustdoc::invalid_html_tags,
    rustdoc::invalid_rust_codeblocks
)]

use serde::{Deserialize, Serialize};

pub type SerializedStorageKey = String;

/// DOM Storage identifier.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct StorageId {
    /// Security origin for the storage.
    #[serde(
        rename = "securityOrigin",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub security_origin: Option<String>,
    /// Represents a key by which DOM Storage keys its CachedStorageAreas
    #[serde(
        rename = "storageKey",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub storage_key: Option<SerializedStorageKey>,
    /// Whether the storage is local storage (not session storage).
    #[serde(rename = "isLocalStorage")]
    pub is_local_storage: bool,
}

/// DOM Storage item.
pub type Item = Vec<String>;

/// Parameters of `DOMStorage.clear`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearParams {
    #[serde(rename = "storageId")]
    pub storage_id: StorageId,
}

/// The answer to `DOMStorage.clear`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearReturns {}

impl ClearParams {
    pub const METHOD: &'static str = "DOMStorage.clear";
}

impl super::Command for ClearParams {
    const METHOD: &'static str = "DOMStorage.clear";
    type Returns = ClearReturns;
}

/// Parameters of `DOMStorage.disable`.
///
/// Disables storage tracking, prevents storage events from being sent to the client.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DisableParams {}

/// The answer to `DOMStorage.disable`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DisableReturns {}

impl DisableParams {
    pub const METHOD: &'static str = "DOMStorage.disable";
}

impl super::Command for DisableParams {
    const METHOD: &'static str = "DOMStorage.disable";
    type Returns = DisableReturns;
}

/// Parameters of `DOMStorage.enable`.
///
/// Enables storage tracking, storage events will now be delivered to the client.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EnableParams {}

/// The answer to `DOMStorage.enable`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EnableReturns {}

impl EnableParams {
    pub const METHOD: &'static str = "DOMStorage.enable";
}

impl super::Command for EnableParams {
    const METHOD: &'static str = "DOMStorage.enable";
    type Returns = EnableReturns;
}

/// Parameters of `DOMStorage.getDOMStorageItems`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetDOMStorageItemsParams {
    #[serde(rename = "storageId")]
    pub storage_id: StorageId,
}

/// The answer to `DOMStorage.getDOMStorageItems`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetDOMStorageItemsReturns {
    pub entries: Vec<Item>,
}

impl GetDOMStorageItemsParams {
    pub const METHOD: &'static str = "DOMStorage.getDOMStorageItems";
}

impl super::Command for GetDOMStorageItemsParams {
    const METHOD: &'static str = "DOMStorage.getDOMStorageItems";
    type Returns = GetDOMStorageItemsReturns;
}

/// Parameters of `DOMStorage.removeDOMStorageItem`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RemoveDOMStorageItemParams {
    #[serde(rename = "storageId")]
    pub storage_id: StorageId,
    pub key: String,
}

/// The answer to `DOMStorage.removeDOMStorageItem`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RemoveDOMStorageItemReturns {}

impl RemoveDOMStorageItemParams {
    pub const METHOD: &'static str = "DOMStorage.removeDOMStorageItem";
}

impl super::Command for RemoveDOMStorageItemParams {
    const METHOD: &'static str = "DOMStorage.removeDOMStorageItem";
    type Returns = RemoveDOMStorageItemReturns;
}

/// Parameters of `DOMStorage.setDOMStorageItem`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetDOMStorageItemParams {
    #[serde(rename = "storageId")]
    pub storage_id: StorageId,
    pub key: String,
    pub value: String,
}

/// The answer to `DOMStorage.setDOMStorageItem`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetDOMStorageItemReturns {}

impl SetDOMStorageItemParams {
    pub const METHOD: &'static str = "DOMStorage.setDOMStorageItem";
}

impl super::Command for SetDOMStorageItemParams {
    const METHOD: &'static str = "DOMStorage.setDOMStorageItem";
    type Returns = SetDOMStorageItemReturns;
}

/// The event `DOMStorage.domStorageItemAdded`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DomStorageItemAddedEvent {
    #[serde(rename = "storageId")]
    pub storage_id: StorageId,
    pub key: String,
    #[serde(rename = "newValue")]
    pub new_value: String,
}

impl DomStorageItemAddedEvent {
    pub const NAME: &'static str = "DOMStorage.domStorageItemAdded";
}

impl super::Event for DomStorageItemAddedEvent {
    const NAME: &'static str = "DOMStorage.domStorageItemAdded";
}

/// The event `DOMStorage.domStorageItemRemoved`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DomStorageItemRemovedEvent {
    #[serde(rename = "storageId")]
    pub storage_id: StorageId,
    pub key: String,
}

impl DomStorageItemRemovedEvent {
    pub const NAME: &'static str = "DOMStorage.domStorageItemRemoved";
}

impl super::Event for DomStorageItemRemovedEvent {
    const NAME: &'static str = "DOMStorage.domStorageItemRemoved";
}

/// The event `DOMStorage.domStorageItemUpdated`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DomStorageItemUpdatedEvent {
    #[serde(rename = "storageId")]
    pub storage_id: StorageId,
    pub key: String,
    #[serde(rename = "oldValue")]
    pub old_value: String,
    #[serde(rename = "newValue")]
    pub new_value: String,
}

impl DomStorageItemUpdatedEvent {
    pub const NAME: &'static str = "DOMStorage.domStorageItemUpdated";
}

impl super::Event for DomStorageItemUpdatedEvent {
    const NAME: &'static str = "DOMStorage.domStorageItemUpdated";
}

/// The event `DOMStorage.domStorageItemsCleared`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DomStorageItemsClearedEvent {
    #[serde(rename = "storageId")]
    pub storage_id: StorageId,
}

impl DomStorageItemsClearedEvent {
    pub const NAME: &'static str = "DOMStorage.domStorageItemsCleared";
}

impl super::Event for DomStorageItemsClearedEvent {
    const NAME: &'static str = "DOMStorage.domStorageItemsCleared";
}
