// Generated by eludite-cdp-generator from devtools-protocol 0.0.1709723 (protocol/cdp/PIN). Do not edit:
// change the generator or the pin and run `cargo run -p eludite-cdp-generator`.
//! The CDP domain `Emulation`.
//!
//! This domain emulates different environments for the page.

#![allow(
    clippy::upper_case_acronyms,
    clippy::doc_lazy_continuation,
    clippy::doc_overindented_list_items,
    clippy::large_enum_variant,
    clippy::empty_docs,
    clippy::struct_excessive_bools,
    rustdoc::bare_urls,
    rustdoc::broken_intra_doc_links,
    rustdoc::invalid_html_tags,
    rustdoc::invalid_rust_codeblocks
)]

use serde::{Deserialize, Serialize};

/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SafeAreaInsets {
    /// Overrides safe-area-inset-top.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub top: Option<i64>,
    /// Overrides safe-area-max-inset-top.
    #[serde(rename = "topMax", default, skip_serializing_if = "Option::is_none")]
    pub top_max: Option<i64>,
    /// Overrides safe-area-inset-left.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub left: Option<i64>,
    /// Overrides safe-area-max-inset-left.
    #[serde(rename = "leftMax", default, skip_serializing_if = "Option::is_none")]
    pub left_max: Option<i64>,
    /// Overrides safe-area-inset-bottom.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bottom: Option<i64>,
    /// Overrides safe-area-max-inset-bottom.
    #[serde(rename = "bottomMax", default, skip_serializing_if = "Option::is_none")]
    pub bottom_max: Option<i64>,
    /// Overrides safe-area-inset-right.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub right: Option<i64>,
    /// Overrides safe-area-max-inset-right.
    #[serde(rename = "rightMax", default, skip_serializing_if = "Option::is_none")]
    pub right_max: Option<i64>,
}

/// Screen orientation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ScreenOrientation {
    /// Orientation type.
    #[serde(rename = "type")]
    pub type_: ScreenOrientationType,
    /// Orientation angle.
    pub angle: i64,
}

/// Values of `ScreenOrientation`'s `type`.
///
/// Orientation type.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ScreenOrientationType {
    /// `portraitPrimary`
    PortraitPrimary,
    /// `portraitSecondary`
    PortraitSecondary,
    /// `landscapePrimary`
    LandscapePrimary,
    /// `landscapeSecondary`
    LandscapeSecondary,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    ScreenOrientationType {
        PortraitPrimary => "portraitPrimary",
        PortraitSecondary => "portraitSecondary",
        LandscapePrimary => "landscapePrimary",
        LandscapeSecondary => "landscapeSecondary",
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DisplayFeature {
    /// Orientation of a display feature in relation to screen
    pub orientation: DisplayFeatureOrientation,
    /// The offset from the screen origin in either the x (for vertical
    /// orientation) or y (for horizontal orientation) direction.
    pub offset: i64,
    /// A display feature may mask content such that it is not physically
    /// displayed - this length along with the offset describes this area.
    /// A display feature that only splits content will have a 0 mask_length.
    #[serde(rename = "maskLength")]
    pub mask_length: i64,
}

/// Values of `DisplayFeature`'s `orientation`.
///
/// Orientation of a display feature in relation to screen
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum DisplayFeatureOrientation {
    /// `vertical`
    Vertical,
    /// `horizontal`
    Horizontal,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    DisplayFeatureOrientation {
        Vertical => "vertical",
        Horizontal => "horizontal",
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DevicePosture {
    /// Current posture of the device
    #[serde(rename = "type")]
    pub type_: DevicePostureType,
}

/// Values of `DevicePosture`'s `type`.
///
/// Current posture of the device
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum DevicePostureType {
    /// `continuous`
    Continuous,
    /// `folded`
    Folded,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    DevicePostureType {
        Continuous => "continuous",
        Folded => "folded",
    }
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct MediaFeature {
    pub name: String,
    pub value: String,
}

/// advance: If the scheduler runs out of immediate work, the virtual time base may fast forward to
/// allow the next delayed task (if any) to run; pause: The virtual time base may not advance;
/// pauseIfNetworkFetchesPending: The virtual time base may not advance if there are any pending
/// resource fetches.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum VirtualTimePolicy {
    /// `advance`
    Advance,
    /// `pause`
    Pause,
    /// `pauseIfNetworkFetchesPending`
    PauseIfNetworkFetchesPending,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    VirtualTimePolicy {
        Advance => "advance",
        Pause => "pause",
        PauseIfNetworkFetchesPending => "pauseIfNetworkFetchesPending",
    }
}

/// Used to specify User Agent Client Hints to emulate. See https://wicg.github.io/ua-client-hints
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct UserAgentBrandVersion {
    pub brand: String,
    pub version: String,
}

/// Used to specify User Agent Client Hints to emulate. See https://wicg.github.io/ua-client-hints
/// Missing optional values will be filled in by the target with what it would normally use.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct UserAgentMetadata {
    /// Brands appearing in Sec-CH-UA.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub brands: Option<Vec<UserAgentBrandVersion>>,
    /// Brands appearing in Sec-CH-UA-Full-Version-List.
    #[serde(
        rename = "fullVersionList",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub full_version_list: Option<Vec<UserAgentBrandVersion>>,
    /// **Deprecated.**
    #[serde(
        rename = "fullVersion",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub full_version: Option<String>,
    pub platform: String,
    #[serde(rename = "platformVersion")]
    pub platform_version: String,
    pub architecture: String,
    pub model: String,
    pub mobile: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bitness: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub wow64: Option<bool>,
    /// Used to specify User Agent form-factor values.
    /// See https://wicg.github.io/ua-client-hints/#sec-ch-ua-form-factors
    #[serde(
        rename = "formFactors",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub form_factors: Option<Vec<String>>,
}

/// Used to specify sensor types to emulate.
/// See https://w3c.github.io/sensors/#automation for more information.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SensorType {
    /// `absolute-orientation`
    AbsoluteOrientation,
    /// `accelerometer`
    Accelerometer,
    /// `ambient-light`
    AmbientLight,
    /// `gravity`
    Gravity,
    /// `gyroscope`
    Gyroscope,
    /// `linear-acceleration`
    LinearAcceleration,
    /// `magnetometer`
    Magnetometer,
    /// `relative-orientation`
    RelativeOrientation,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    SensorType {
        AbsoluteOrientation => "absolute-orientation",
        Accelerometer => "accelerometer",
        AmbientLight => "ambient-light",
        Gravity => "gravity",
        Gyroscope => "gyroscope",
        LinearAcceleration => "linear-acceleration",
        Magnetometer => "magnetometer",
        RelativeOrientation => "relative-orientation",
    }
}

/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SensorMetadata {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub available: Option<bool>,
    #[serde(
        rename = "minimumFrequency",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub minimum_frequency: Option<f64>,
    #[serde(
        rename = "maximumFrequency",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub maximum_frequency: Option<f64>,
}

/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SensorReadingSingle {
    pub value: f64,
}

/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SensorReadingXYZ {
    pub x: f64,
    pub y: f64,
    pub z: f64,
}

/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SensorReadingQuaternion {
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub w: f64,
}

/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SensorReading {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub single: Option<SensorReadingSingle>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub xyz: Option<SensorReadingXYZ>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub quaternion: Option<SensorReadingQuaternion>,
}

/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum PressureSource {
    /// `cpu`
    Cpu,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    PressureSource {
        Cpu => "cpu",
    }
}

/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum PressureState {
    /// `nominal`
    Nominal,
    /// `fair`
    Fair,
    /// `serious`
    Serious,
    /// `critical`
    Critical,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    PressureState {
        Nominal => "nominal",
        Fair => "fair",
        Serious => "serious",
        Critical => "critical",
    }
}

/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct PressureMetadata {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub available: Option<bool>,
}

/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct WorkAreaInsets {
    /// Work area top inset in pixels. Default is 0;
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub top: Option<i64>,
    /// Work area left inset in pixels. Default is 0;
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub left: Option<i64>,
    /// Work area bottom inset in pixels. Default is 0;
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bottom: Option<i64>,
    /// Work area right inset in pixels. Default is 0;
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub right: Option<i64>,
}

/// **Experimental.**
pub type ScreenId = String;

/// Screen information similar to the one returned by window.getScreenDetails() method,
/// see https://w3c.github.io/window-management/#screendetailed.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ScreenInfo {
    /// Offset of the left edge of the screen.
    pub left: i64,
    /// Offset of the top edge of the screen.
    pub top: i64,
    /// Width of the screen.
    pub width: i64,
    /// Height of the screen.
    pub height: i64,
    /// Offset of the left edge of the available screen area.
    #[serde(rename = "availLeft")]
    pub avail_left: i64,
    /// Offset of the top edge of the available screen area.
    #[serde(rename = "availTop")]
    pub avail_top: i64,
    /// Width of the available screen area.
    #[serde(rename = "availWidth")]
    pub avail_width: i64,
    /// Height of the available screen area.
    #[serde(rename = "availHeight")]
    pub avail_height: i64,
    /// Specifies the screen's device pixel ratio.
    #[serde(rename = "devicePixelRatio")]
    pub device_pixel_ratio: f64,
    /// Specifies the screen's orientation.
    pub orientation: ScreenOrientation,
    /// Specifies the screen's color depth in bits.
    #[serde(rename = "colorDepth")]
    pub color_depth: i64,
    /// Indicates whether the device has multiple screens.
    #[serde(rename = "isExtended")]
    pub is_extended: bool,
    /// Indicates whether the screen is internal to the device or external, attached to the device.
    #[serde(rename = "isInternal")]
    pub is_internal: bool,
    /// Indicates whether the screen is set as the the operating system primary screen.
    #[serde(rename = "isPrimary")]
    pub is_primary: bool,
    /// Specifies the descriptive label for the screen.
    pub label: String,
    /// Specifies the unique identifier of the screen.
    pub id: ScreenId,
}

/// Enum of image types that can be disabled.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum DisabledImageType {
    /// `avif`
    Avif,
    /// `jxl`
    Jxl,
    /// `webp`
    Webp,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    DisabledImageType {
        Avif => "avif",
        Jxl => "jxl",
        Webp => "webp",
    }
}

/// Parameters of `Emulation.canEmulate`.
///
/// Tells whether emulation is supported.
///
/// **Deprecated.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CanEmulateParams {}

/// The answer to `Emulation.canEmulate`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CanEmulateReturns {
    /// True if emulation is supported.
    pub result: bool,
}

impl CanEmulateParams {
    pub const METHOD: &'static str = "Emulation.canEmulate";
}

impl super::Command for CanEmulateParams {
    const METHOD: &'static str = "Emulation.canEmulate";
    type Returns = CanEmulateReturns;
}

/// Parameters of `Emulation.clearDeviceMetricsOverride`.
///
/// Clears the overridden device metrics.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearDeviceMetricsOverrideParams {}

/// The answer to `Emulation.clearDeviceMetricsOverride`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearDeviceMetricsOverrideReturns {}

impl ClearDeviceMetricsOverrideParams {
    pub const METHOD: &'static str = "Emulation.clearDeviceMetricsOverride";
}

impl super::Command for ClearDeviceMetricsOverrideParams {
    const METHOD: &'static str = "Emulation.clearDeviceMetricsOverride";
    type Returns = ClearDeviceMetricsOverrideReturns;
}

/// Parameters of `Emulation.clearGeolocationOverride`.
///
/// Clears the overridden Geolocation Position and Error.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearGeolocationOverrideParams {}

/// The answer to `Emulation.clearGeolocationOverride`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearGeolocationOverrideReturns {}

impl ClearGeolocationOverrideParams {
    pub const METHOD: &'static str = "Emulation.clearGeolocationOverride";
}

impl super::Command for ClearGeolocationOverrideParams {
    const METHOD: &'static str = "Emulation.clearGeolocationOverride";
    type Returns = ClearGeolocationOverrideReturns;
}

/// Parameters of `Emulation.resetPageScaleFactor`.
///
/// Requests that page scale factor is reset to initial values.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ResetPageScaleFactorParams {}

/// The answer to `Emulation.resetPageScaleFactor`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ResetPageScaleFactorReturns {}

impl ResetPageScaleFactorParams {
    pub const METHOD: &'static str = "Emulation.resetPageScaleFactor";
}

impl super::Command for ResetPageScaleFactorParams {
    const METHOD: &'static str = "Emulation.resetPageScaleFactor";
    type Returns = ResetPageScaleFactorReturns;
}

/// Parameters of `Emulation.setFocusEmulationEnabled`.
///
/// Enables or disables simulating a focused and active page.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetFocusEmulationEnabledParams {
    /// Whether to enable to disable focus emulation.
    pub enabled: bool,
}

/// The answer to `Emulation.setFocusEmulationEnabled`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetFocusEmulationEnabledReturns {}

impl SetFocusEmulationEnabledParams {
    pub const METHOD: &'static str = "Emulation.setFocusEmulationEnabled";
}

impl super::Command for SetFocusEmulationEnabledParams {
    const METHOD: &'static str = "Emulation.setFocusEmulationEnabled";
    type Returns = SetFocusEmulationEnabledReturns;
}

/// Parameters of `Emulation.setAutoDarkModeOverride`.
///
/// Automatically render all web contents using a dark theme.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetAutoDarkModeOverrideParams {
    /// Whether to enable or disable automatic dark mode.
    /// If not specified, any existing override will be cleared.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

/// The answer to `Emulation.setAutoDarkModeOverride`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetAutoDarkModeOverrideReturns {}

impl SetAutoDarkModeOverrideParams {
    pub const METHOD: &'static str = "Emulation.setAutoDarkModeOverride";
}

impl super::Command for SetAutoDarkModeOverrideParams {
    const METHOD: &'static str = "Emulation.setAutoDarkModeOverride";
    type Returns = SetAutoDarkModeOverrideReturns;
}

/// Parameters of `Emulation.setCPUThrottlingRate`.
///
/// Enables CPU throttling to emulate slow CPUs.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetCPUThrottlingRateParams {
    /// Throttling rate as a slowdown factor (1 is no throttle, 2 is 2x slowdown, etc).
    pub rate: f64,
}

/// The answer to `Emulation.setCPUThrottlingRate`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetCPUThrottlingRateReturns {}

impl SetCPUThrottlingRateParams {
    pub const METHOD: &'static str = "Emulation.setCPUThrottlingRate";
}

impl super::Command for SetCPUThrottlingRateParams {
    const METHOD: &'static str = "Emulation.setCPUThrottlingRate";
    type Returns = SetCPUThrottlingRateReturns;
}

/// Parameters of `Emulation.setDefaultBackgroundColorOverride`.
///
/// Sets or clears an override of the default background color of the frame. This override is used
/// if the content does not specify one.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetDefaultBackgroundColorOverrideParams {
    /// RGBA of the default background color. If not specified, any existing override will be
    /// cleared.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color: Option<super::dom::RGBA>,
}

/// The answer to `Emulation.setDefaultBackgroundColorOverride`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetDefaultBackgroundColorOverrideReturns {}

impl SetDefaultBackgroundColorOverrideParams {
    pub const METHOD: &'static str = "Emulation.setDefaultBackgroundColorOverride";
}

impl super::Command for SetDefaultBackgroundColorOverrideParams {
    const METHOD: &'static str = "Emulation.setDefaultBackgroundColorOverride";
    type Returns = SetDefaultBackgroundColorOverrideReturns;
}

/// Parameters of `Emulation.setSafeAreaInsetsOverride`.
///
/// Overrides the values for env(safe-area-inset-*) and env(safe-area-max-inset-*). Unset values will cause the
/// respective variables to be undefined, even if previously overridden.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetSafeAreaInsetsOverrideParams {
    pub insets: SafeAreaInsets,
}

/// The answer to `Emulation.setSafeAreaInsetsOverride`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetSafeAreaInsetsOverrideReturns {}

impl SetSafeAreaInsetsOverrideParams {
    pub const METHOD: &'static str = "Emulation.setSafeAreaInsetsOverride";
}

impl super::Command for SetSafeAreaInsetsOverrideParams {
    const METHOD: &'static str = "Emulation.setSafeAreaInsetsOverride";
    type Returns = SetSafeAreaInsetsOverrideReturns;
}

/// Parameters of `Emulation.setVirtualKeyboardGeometryOverride`.
///
/// Overrides virtual keyboard geometry in CSS pixels, relative to the top-level viewport. The
/// provided rect is used for navigator.virtualKeyboard.boundingRect, geometrychange events, and
/// env(keyboard-inset-*) values on the inspected frame. The override applies independently of
/// navigator.virtualKeyboard.overlaysContent so clients can preview overlay geometry without
/// mutating page state. Values are rounded to the nearest CSS pixel. Omitting the rect clears the
/// override.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetVirtualKeyboardGeometryOverrideParams {
    #[serde(
        rename = "keyboardRect",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub keyboard_rect: Option<super::dom::Rect>,
}

/// The answer to `Emulation.setVirtualKeyboardGeometryOverride`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetVirtualKeyboardGeometryOverrideReturns {}

impl SetVirtualKeyboardGeometryOverrideParams {
    pub const METHOD: &'static str = "Emulation.setVirtualKeyboardGeometryOverride";
}

impl super::Command for SetVirtualKeyboardGeometryOverrideParams {
    const METHOD: &'static str = "Emulation.setVirtualKeyboardGeometryOverride";
    type Returns = SetVirtualKeyboardGeometryOverrideReturns;
}

/// Parameters of `Emulation.setDeviceMetricsOverride`.
///
/// Overrides the values of device screen dimensions (window.screen.width, window.screen.height,
/// window.innerWidth, window.innerHeight, and "device-width"/"device-height"-related CSS media
/// query results).
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetDeviceMetricsOverrideParams {
    /// Overriding width value in pixels (minimum 0, maximum 10000000). 0 disables the override.
    pub width: i64,
    /// Overriding height value in pixels (minimum 0, maximum 10000000). 0 disables the override.
    pub height: i64,
    /// Overriding device scale factor value. 0 disables the override.
    #[serde(rename = "deviceScaleFactor")]
    pub device_scale_factor: f64,
    /// Whether to emulate mobile device. This includes viewport meta tag, overlay scrollbars, text
    /// autosizing and more.
    pub mobile: bool,
    /// Scale to apply to resulting view image.
    ///
    /// **Experimental.**
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scale: Option<f64>,
    /// Overriding screen width value in pixels (minimum 0, maximum 10000000).
    ///
    /// **Experimental.**
    #[serde(
        rename = "screenWidth",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub screen_width: Option<i64>,
    /// Overriding screen height value in pixels (minimum 0, maximum 10000000).
    ///
    /// **Experimental.**
    #[serde(
        rename = "screenHeight",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub screen_height: Option<i64>,
    /// Overriding view X position on screen in pixels (minimum 0, maximum 10000000).
    ///
    /// **Experimental.**
    #[serde(rename = "positionX", default, skip_serializing_if = "Option::is_none")]
    pub position_x: Option<i64>,
    /// Overriding view Y position on screen in pixels (minimum 0, maximum 10000000).
    ///
    /// **Experimental.**
    #[serde(rename = "positionY", default, skip_serializing_if = "Option::is_none")]
    pub position_y: Option<i64>,
    /// Do not set visible view size, rely upon explicit setVisibleSize call.
    ///
    /// **Experimental.**
    #[serde(
        rename = "dontSetVisibleSize",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub dont_set_visible_size: Option<bool>,
    /// Screen orientation override.
    #[serde(
        rename = "screenOrientation",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub screen_orientation: Option<ScreenOrientation>,
    /// If set, the visible area of the page will be overridden to this viewport. This viewport
    /// change is not observed by the page, e.g. viewport-relative elements do not change positions.
    ///
    /// **Experimental.**
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub viewport: Option<super::page::Viewport>,
    /// If set, the display feature of a multi-segment screen. If not set, multi-segment support
    /// is turned-off.
    /// Deprecated, use Emulation.setDisplayFeaturesOverride.
    ///
    /// **Experimental.** **Deprecated.**
    #[serde(
        rename = "displayFeature",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub display_feature: Option<DisplayFeature>,
    /// If set, the posture of a foldable device. If not set the posture is set
    /// to continuous.
    /// Deprecated, use Emulation.setDevicePostureOverride.
    ///
    /// **Experimental.** **Deprecated.**
    #[serde(
        rename = "devicePosture",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub device_posture: Option<DevicePosture>,
    /// Scrollbar type. Default: `default`.
    ///
    /// **Experimental.**
    #[serde(
        rename = "scrollbarType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub scrollbar_type: Option<SetDeviceMetricsOverrideScrollbarType>,
    /// If set to true, enables screen orientation lock emulation, which
    /// intercepts screen.orientation.lock() calls from the page and reports
    /// orientation changes via screenOrientationLockChanged events. This is
    /// useful for emulating mobile device orientation lock behavior in
    /// responsive design mode.
    ///
    /// **Experimental.**
    #[serde(
        rename = "screenOrientationLockEmulation",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub screen_orientation_lock_emulation: Option<bool>,
    /// Viewport meta tag behavior. Default: `default`. Note: if `mobile` is `true`,
    /// the viewport meta tag is always enabled.
    ///
    /// **Experimental.**
    #[serde(
        rename = "viewportMeta",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub viewport_meta: Option<SetDeviceMetricsOverrideViewportMeta>,
    /// Text layout mode. Default: `default`. Note: if `mobile` is `true`,
    /// mobile text layout mode (text autosizing) is always enabled.
    ///
    /// **Experimental.**
    #[serde(
        rename = "textLayoutMode",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub text_layout_mode: Option<SetDeviceMetricsOverrideTextLayoutMode>,
}

/// Values of `SetDeviceMetricsOverride`'s `scrollbarType`.
///
/// Scrollbar type. Default: `default`.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SetDeviceMetricsOverrideScrollbarType {
    /// `overlay`
    Overlay,
    /// `default`
    Default,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    SetDeviceMetricsOverrideScrollbarType {
        Overlay => "overlay",
        Default => "default",
    }
}

/// Values of `SetDeviceMetricsOverride`'s `viewportMeta`.
///
/// Viewport meta tag behavior. Default: `default`. Note: if `mobile` is `true`,
/// the viewport meta tag is always enabled.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SetDeviceMetricsOverrideViewportMeta {
    /// `enable`
    Enable,
    /// `default`
    Default,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    SetDeviceMetricsOverrideViewportMeta {
        Enable => "enable",
        Default => "default",
    }
}

/// Values of `SetDeviceMetricsOverride`'s `textLayoutMode`.
///
/// Text layout mode. Default: `default`. Note: if `mobile` is `true`,
/// mobile text layout mode (text autosizing) is always enabled.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SetDeviceMetricsOverrideTextLayoutMode {
    /// `mobile`
    Mobile,
    /// `default`
    Default,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    SetDeviceMetricsOverrideTextLayoutMode {
        Mobile => "mobile",
        Default => "default",
    }
}

/// The answer to `Emulation.setDeviceMetricsOverride`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetDeviceMetricsOverrideReturns {}

impl SetDeviceMetricsOverrideParams {
    pub const METHOD: &'static str = "Emulation.setDeviceMetricsOverride";
}

impl super::Command for SetDeviceMetricsOverrideParams {
    const METHOD: &'static str = "Emulation.setDeviceMetricsOverride";
    type Returns = SetDeviceMetricsOverrideReturns;
}

/// Parameters of `Emulation.setDevicePostureOverride`.
///
/// Start reporting the given posture value to the Device Posture API.
/// This override can also be set in setDeviceMetricsOverride().
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SetDevicePostureOverrideParams {
    pub posture: DevicePosture,
}

/// The answer to `Emulation.setDevicePostureOverride`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetDevicePostureOverrideReturns {}

impl SetDevicePostureOverrideParams {
    pub const METHOD: &'static str = "Emulation.setDevicePostureOverride";
}

impl super::Command for SetDevicePostureOverrideParams {
    const METHOD: &'static str = "Emulation.setDevicePostureOverride";
    type Returns = SetDevicePostureOverrideReturns;
}

/// Parameters of `Emulation.clearDevicePostureOverride`.
///
/// Clears a device posture override set with either setDeviceMetricsOverride()
/// or setDevicePostureOverride() and starts using posture information from the
/// platform again.
/// Does nothing if no override is set.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearDevicePostureOverrideParams {}

/// The answer to `Emulation.clearDevicePostureOverride`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearDevicePostureOverrideReturns {}

impl ClearDevicePostureOverrideParams {
    pub const METHOD: &'static str = "Emulation.clearDevicePostureOverride";
}

impl super::Command for ClearDevicePostureOverrideParams {
    const METHOD: &'static str = "Emulation.clearDevicePostureOverride";
    type Returns = ClearDevicePostureOverrideReturns;
}

/// Parameters of `Emulation.setDisplayFeaturesOverride`.
///
/// Start using the given display features to pupulate the Viewport Segments API.
/// This override can also be set in setDeviceMetricsOverride().
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetDisplayFeaturesOverrideParams {
    pub features: Vec<DisplayFeature>,
}

/// The answer to `Emulation.setDisplayFeaturesOverride`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetDisplayFeaturesOverrideReturns {}

impl SetDisplayFeaturesOverrideParams {
    pub const METHOD: &'static str = "Emulation.setDisplayFeaturesOverride";
}

impl super::Command for SetDisplayFeaturesOverrideParams {
    const METHOD: &'static str = "Emulation.setDisplayFeaturesOverride";
    type Returns = SetDisplayFeaturesOverrideReturns;
}

/// Parameters of `Emulation.clearDisplayFeaturesOverride`.
///
/// Clears the display features override set with either setDeviceMetricsOverride()
/// or setDisplayFeaturesOverride() and starts using display features from the
/// platform again.
/// Does nothing if no override is set.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearDisplayFeaturesOverrideParams {}

/// The answer to `Emulation.clearDisplayFeaturesOverride`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearDisplayFeaturesOverrideReturns {}

impl ClearDisplayFeaturesOverrideParams {
    pub const METHOD: &'static str = "Emulation.clearDisplayFeaturesOverride";
}

impl super::Command for ClearDisplayFeaturesOverrideParams {
    const METHOD: &'static str = "Emulation.clearDisplayFeaturesOverride";
    type Returns = ClearDisplayFeaturesOverrideReturns;
}

/// Parameters of `Emulation.setScrollbarsHidden`.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetScrollbarsHiddenParams {
    /// Whether scrollbars should be always hidden.
    pub hidden: bool,
}

/// The answer to `Emulation.setScrollbarsHidden`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetScrollbarsHiddenReturns {}

impl SetScrollbarsHiddenParams {
    pub const METHOD: &'static str = "Emulation.setScrollbarsHidden";
}

impl super::Command for SetScrollbarsHiddenParams {
    const METHOD: &'static str = "Emulation.setScrollbarsHidden";
    type Returns = SetScrollbarsHiddenReturns;
}

/// Parameters of `Emulation.setDocumentCookieDisabled`.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetDocumentCookieDisabledParams {
    /// Whether document.coookie API should be disabled.
    pub disabled: bool,
}

/// The answer to `Emulation.setDocumentCookieDisabled`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetDocumentCookieDisabledReturns {}

impl SetDocumentCookieDisabledParams {
    pub const METHOD: &'static str = "Emulation.setDocumentCookieDisabled";
}

impl super::Command for SetDocumentCookieDisabledParams {
    const METHOD: &'static str = "Emulation.setDocumentCookieDisabled";
    type Returns = SetDocumentCookieDisabledReturns;
}

/// Parameters of `Emulation.setEmitTouchEventsForMouse`.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetEmitTouchEventsForMouseParams {
    /// Whether touch emulation based on mouse input should be enabled.
    pub enabled: bool,
    /// Touch/gesture events configuration. Default: current platform.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub configuration: Option<SetEmitTouchEventsForMouseConfiguration>,
}

/// Values of `SetEmitTouchEventsForMouse`'s `configuration`.
///
/// Touch/gesture events configuration. Default: current platform.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SetEmitTouchEventsForMouseConfiguration {
    /// `mobile`
    Mobile,
    /// `desktop`
    Desktop,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    SetEmitTouchEventsForMouseConfiguration {
        Mobile => "mobile",
        Desktop => "desktop",
    }
}

/// The answer to `Emulation.setEmitTouchEventsForMouse`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetEmitTouchEventsForMouseReturns {}

impl SetEmitTouchEventsForMouseParams {
    pub const METHOD: &'static str = "Emulation.setEmitTouchEventsForMouse";
}

impl super::Command for SetEmitTouchEventsForMouseParams {
    const METHOD: &'static str = "Emulation.setEmitTouchEventsForMouse";
    type Returns = SetEmitTouchEventsForMouseReturns;
}

/// Parameters of `Emulation.setEmulatedMedia`.
///
/// Emulates the given media type or media feature for CSS media queries.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetEmulatedMediaParams {
    /// Media type to emulate. Empty string disables the override.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub media: Option<String>,
    /// Media features to emulate.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub features: Option<Vec<MediaFeature>>,
}

/// The answer to `Emulation.setEmulatedMedia`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetEmulatedMediaReturns {}

impl SetEmulatedMediaParams {
    pub const METHOD: &'static str = "Emulation.setEmulatedMedia";
}

impl super::Command for SetEmulatedMediaParams {
    const METHOD: &'static str = "Emulation.setEmulatedMedia";
    type Returns = SetEmulatedMediaReturns;
}

/// Parameters of `Emulation.setEmulatedVisionDeficiency`.
///
/// Emulates the given vision deficiency.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SetEmulatedVisionDeficiencyParams {
    /// Vision deficiency to emulate. Order: best-effort emulations come first, followed by any
    /// physiologically accurate emulations for medically recognized color vision deficiencies.
    #[serde(rename = "type")]
    pub type_: SetEmulatedVisionDeficiencyType,
}

/// Values of `SetEmulatedVisionDeficiency`'s `type`.
///
/// Vision deficiency to emulate. Order: best-effort emulations come first, followed by any
/// physiologically accurate emulations for medically recognized color vision deficiencies.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SetEmulatedVisionDeficiencyType {
    /// `none`
    None,
    /// `blurredVision`
    BlurredVision,
    /// `reducedContrast`
    ReducedContrast,
    /// `achromatopsia`
    Achromatopsia,
    /// `deuteranopia`
    Deuteranopia,
    /// `protanopia`
    Protanopia,
    /// `tritanopia`
    Tritanopia,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    SetEmulatedVisionDeficiencyType {
        None => "none",
        BlurredVision => "blurredVision",
        ReducedContrast => "reducedContrast",
        Achromatopsia => "achromatopsia",
        Deuteranopia => "deuteranopia",
        Protanopia => "protanopia",
        Tritanopia => "tritanopia",
    }
}

/// The answer to `Emulation.setEmulatedVisionDeficiency`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetEmulatedVisionDeficiencyReturns {}

impl SetEmulatedVisionDeficiencyParams {
    pub const METHOD: &'static str = "Emulation.setEmulatedVisionDeficiency";
}

impl super::Command for SetEmulatedVisionDeficiencyParams {
    const METHOD: &'static str = "Emulation.setEmulatedVisionDeficiency";
    type Returns = SetEmulatedVisionDeficiencyReturns;
}

/// Parameters of `Emulation.setEmulatedOSTextScale`.
///
/// Emulates the given OS text scale.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetEmulatedOSTextScaleParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scale: Option<f64>,
}

/// The answer to `Emulation.setEmulatedOSTextScale`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetEmulatedOSTextScaleReturns {}

impl SetEmulatedOSTextScaleParams {
    pub const METHOD: &'static str = "Emulation.setEmulatedOSTextScale";
}

impl super::Command for SetEmulatedOSTextScaleParams {
    const METHOD: &'static str = "Emulation.setEmulatedOSTextScale";
    type Returns = SetEmulatedOSTextScaleReturns;
}

/// Parameters of `Emulation.setGeolocationOverride`.
///
/// Overrides the Geolocation Position or Error. Omitting latitude, longitude or
/// accuracy emulates position unavailable.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetGeolocationOverrideParams {
    /// Mock latitude
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    /// Mock longitude
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
    /// Mock accuracy
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub accuracy: Option<f64>,
    /// Mock altitude
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub altitude: Option<f64>,
    /// Mock altitudeAccuracy
    #[serde(
        rename = "altitudeAccuracy",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub altitude_accuracy: Option<f64>,
    /// Mock heading
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub heading: Option<f64>,
    /// Mock speed
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub speed: Option<f64>,
}

/// The answer to `Emulation.setGeolocationOverride`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetGeolocationOverrideReturns {}

impl SetGeolocationOverrideParams {
    pub const METHOD: &'static str = "Emulation.setGeolocationOverride";
}

impl super::Command for SetGeolocationOverrideParams {
    const METHOD: &'static str = "Emulation.setGeolocationOverride";
    type Returns = SetGeolocationOverrideReturns;
}

/// Parameters of `Emulation.getOverriddenSensorInformation`.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GetOverriddenSensorInformationParams {
    #[serde(rename = "type")]
    pub type_: SensorType,
}

/// The answer to `Emulation.getOverriddenSensorInformation`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetOverriddenSensorInformationReturns {
    #[serde(rename = "requestedSamplingFrequency")]
    pub requested_sampling_frequency: f64,
}

impl GetOverriddenSensorInformationParams {
    pub const METHOD: &'static str = "Emulation.getOverriddenSensorInformation";
}

impl super::Command for GetOverriddenSensorInformationParams {
    const METHOD: &'static str = "Emulation.getOverriddenSensorInformation";
    type Returns = GetOverriddenSensorInformationReturns;
}

/// Parameters of `Emulation.setSensorOverrideEnabled`.
///
/// Overrides a platform sensor of a given type. If |enabled| is true, calls to
/// Sensor.start() will use a virtual sensor as backend rather than fetching
/// data from a real hardware sensor. Otherwise, existing virtual
/// sensor-backend Sensor objects will fire an error event and new calls to
/// Sensor.start() will attempt to use a real sensor instead.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SetSensorOverrideEnabledParams {
    pub enabled: bool,
    #[serde(rename = "type")]
    pub type_: SensorType,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<SensorMetadata>,
}

/// The answer to `Emulation.setSensorOverrideEnabled`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetSensorOverrideEnabledReturns {}

impl SetSensorOverrideEnabledParams {
    pub const METHOD: &'static str = "Emulation.setSensorOverrideEnabled";
}

impl super::Command for SetSensorOverrideEnabledParams {
    const METHOD: &'static str = "Emulation.setSensorOverrideEnabled";
    type Returns = SetSensorOverrideEnabledReturns;
}

/// Parameters of `Emulation.setSensorOverrideReadings`.
///
/// Updates the sensor readings reported by a sensor type previously overridden
/// by setSensorOverrideEnabled.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SetSensorOverrideReadingsParams {
    #[serde(rename = "type")]
    pub type_: SensorType,
    pub reading: SensorReading,
}

/// The answer to `Emulation.setSensorOverrideReadings`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetSensorOverrideReadingsReturns {}

impl SetSensorOverrideReadingsParams {
    pub const METHOD: &'static str = "Emulation.setSensorOverrideReadings";
}

impl super::Command for SetSensorOverrideReadingsParams {
    const METHOD: &'static str = "Emulation.setSensorOverrideReadings";
    type Returns = SetSensorOverrideReadingsReturns;
}

/// Parameters of `Emulation.setPressureSourceOverrideEnabled`.
///
/// Overrides a pressure source of a given type, as used by the Compute
/// Pressure API, so that updates to PressureObserver.observe() are provided
/// via setPressureStateOverride instead of being retrieved from
/// platform-provided telemetry data.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SetPressureSourceOverrideEnabledParams {
    pub enabled: bool,
    pub source: PressureSource,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<PressureMetadata>,
}

/// The answer to `Emulation.setPressureSourceOverrideEnabled`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetPressureSourceOverrideEnabledReturns {}

impl SetPressureSourceOverrideEnabledParams {
    pub const METHOD: &'static str = "Emulation.setPressureSourceOverrideEnabled";
}

impl super::Command for SetPressureSourceOverrideEnabledParams {
    const METHOD: &'static str = "Emulation.setPressureSourceOverrideEnabled";
    type Returns = SetPressureSourceOverrideEnabledReturns;
}

/// Parameters of `Emulation.setPressureStateOverride`.
///
/// Provides a given pressure state that will be processed and eventually be
/// delivered to PressureObserver users. |source| must have been previously
/// overridden by setPressureSourceOverrideEnabled.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SetPressureStateOverrideParams {
    pub source: PressureSource,
    pub state: PressureState,
}

/// The answer to `Emulation.setPressureStateOverride`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetPressureStateOverrideReturns {}

impl SetPressureStateOverrideParams {
    pub const METHOD: &'static str = "Emulation.setPressureStateOverride";
}

impl super::Command for SetPressureStateOverrideParams {
    const METHOD: &'static str = "Emulation.setPressureStateOverride";
    type Returns = SetPressureStateOverrideReturns;
}

/// Parameters of `Emulation.setIdleOverride`.
///
/// Overrides the Idle state.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetIdleOverrideParams {
    /// Mock isUserActive
    #[serde(rename = "isUserActive")]
    pub is_user_active: bool,
    /// Mock isScreenUnlocked
    #[serde(rename = "isScreenUnlocked")]
    pub is_screen_unlocked: bool,
}

/// The answer to `Emulation.setIdleOverride`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetIdleOverrideReturns {}

impl SetIdleOverrideParams {
    pub const METHOD: &'static str = "Emulation.setIdleOverride";
}

impl super::Command for SetIdleOverrideParams {
    const METHOD: &'static str = "Emulation.setIdleOverride";
    type Returns = SetIdleOverrideReturns;
}

/// Parameters of `Emulation.clearIdleOverride`.
///
/// Clears Idle state overrides.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearIdleOverrideParams {}

/// The answer to `Emulation.clearIdleOverride`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearIdleOverrideReturns {}

impl ClearIdleOverrideParams {
    pub const METHOD: &'static str = "Emulation.clearIdleOverride";
}

impl super::Command for ClearIdleOverrideParams {
    const METHOD: &'static str = "Emulation.clearIdleOverride";
    type Returns = ClearIdleOverrideReturns;
}

/// Parameters of `Emulation.setNavigatorOverrides`.
///
/// Overrides value returned by the javascript navigator object.
///
/// **Experimental.** **Deprecated.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetNavigatorOverridesParams {
    /// The platform navigator.platform should return.
    pub platform: String,
}

/// The answer to `Emulation.setNavigatorOverrides`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetNavigatorOverridesReturns {}

impl SetNavigatorOverridesParams {
    pub const METHOD: &'static str = "Emulation.setNavigatorOverrides";
}

impl super::Command for SetNavigatorOverridesParams {
    const METHOD: &'static str = "Emulation.setNavigatorOverrides";
    type Returns = SetNavigatorOverridesReturns;
}

/// Parameters of `Emulation.setPageScaleFactor`.
///
/// Sets a specified page scale factor.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetPageScaleFactorParams {
    /// Page scale factor.
    #[serde(rename = "pageScaleFactor")]
    pub page_scale_factor: f64,
}

/// The answer to `Emulation.setPageScaleFactor`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetPageScaleFactorReturns {}

impl SetPageScaleFactorParams {
    pub const METHOD: &'static str = "Emulation.setPageScaleFactor";
}

impl super::Command for SetPageScaleFactorParams {
    const METHOD: &'static str = "Emulation.setPageScaleFactor";
    type Returns = SetPageScaleFactorReturns;
}

/// Parameters of `Emulation.setScriptExecutionDisabled`.
///
/// Switches script execution in the page.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetScriptExecutionDisabledParams {
    /// Whether script execution should be disabled in the page.
    pub value: bool,
}

/// The answer to `Emulation.setScriptExecutionDisabled`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetScriptExecutionDisabledReturns {}

impl SetScriptExecutionDisabledParams {
    pub const METHOD: &'static str = "Emulation.setScriptExecutionDisabled";
}

impl super::Command for SetScriptExecutionDisabledParams {
    const METHOD: &'static str = "Emulation.setScriptExecutionDisabled";
    type Returns = SetScriptExecutionDisabledReturns;
}

/// Parameters of `Emulation.setTouchEmulationEnabled`.
///
/// Enables touch on platforms which do not support them.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetTouchEmulationEnabledParams {
    /// Whether the touch event emulation should be enabled.
    pub enabled: bool,
    /// Maximum touch points supported. Defaults to one.
    #[serde(
        rename = "maxTouchPoints",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_touch_points: Option<i64>,
}

/// The answer to `Emulation.setTouchEmulationEnabled`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetTouchEmulationEnabledReturns {}

impl SetTouchEmulationEnabledParams {
    pub const METHOD: &'static str = "Emulation.setTouchEmulationEnabled";
}

impl super::Command for SetTouchEmulationEnabledParams {
    const METHOD: &'static str = "Emulation.setTouchEmulationEnabled";
    type Returns = SetTouchEmulationEnabledReturns;
}

/// Parameters of `Emulation.setVirtualTimePolicy`.
///
/// Turns on virtual time for all frames (replacing real-time with a synthetic time source) and sets
/// the current virtual time policy.  Note this supersedes any previous time budget.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SetVirtualTimePolicyParams {
    pub policy: VirtualTimePolicy,
    /// If set, after this many virtual milliseconds have elapsed virtual time will be paused and a
    /// virtualTimeBudgetExpired event is sent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub budget: Option<f64>,
    /// If set this specifies the maximum number of tasks that can be run before virtual is forced
    /// forwards to prevent deadlock.
    #[serde(
        rename = "maxVirtualTimeTaskStarvationCount",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_virtual_time_task_starvation_count: Option<i64>,
    /// If set, base::Time::Now will be overridden to initially return this value.
    #[serde(
        rename = "initialVirtualTime",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub initial_virtual_time: Option<super::network::TimeSinceEpoch>,
}

/// The answer to `Emulation.setVirtualTimePolicy`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetVirtualTimePolicyReturns {
    /// Absolute timestamp at which virtual time was first enabled (up time in milliseconds).
    #[serde(rename = "virtualTimeTicksBase")]
    pub virtual_time_ticks_base: f64,
}

impl SetVirtualTimePolicyParams {
    pub const METHOD: &'static str = "Emulation.setVirtualTimePolicy";
}

impl super::Command for SetVirtualTimePolicyParams {
    const METHOD: &'static str = "Emulation.setVirtualTimePolicy";
    type Returns = SetVirtualTimePolicyReturns;
}

/// Parameters of `Emulation.setLocaleOverride`.
///
/// Overrides default host system locale with the specified one.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetLocaleOverrideParams {
    /// ICU style C locale (e.g. "en_US"). If not specified or empty, disables the override and
    /// restores default host system locale.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub locale: Option<String>,
}

/// The answer to `Emulation.setLocaleOverride`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetLocaleOverrideReturns {}

impl SetLocaleOverrideParams {
    pub const METHOD: &'static str = "Emulation.setLocaleOverride";
}

impl super::Command for SetLocaleOverrideParams {
    const METHOD: &'static str = "Emulation.setLocaleOverride";
    type Returns = SetLocaleOverrideReturns;
}

/// Parameters of `Emulation.setTimezoneOverride`.
///
/// Overrides default host system timezone with the specified one.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetTimezoneOverrideParams {
    /// The timezone identifier. List of supported timezones:
    /// https://source.chromium.org/chromium/chromium/deps/icu.git/+/faee8bc70570192d82d2978a71e2a615788597d1:source/data/misc/metaZones.txt
    /// If empty, disables the override and restores default host system timezone.
    #[serde(rename = "timezoneId")]
    pub timezone_id: String,
}

/// The answer to `Emulation.setTimezoneOverride`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetTimezoneOverrideReturns {}

impl SetTimezoneOverrideParams {
    pub const METHOD: &'static str = "Emulation.setTimezoneOverride";
}

impl super::Command for SetTimezoneOverrideParams {
    const METHOD: &'static str = "Emulation.setTimezoneOverride";
    type Returns = SetTimezoneOverrideReturns;
}

/// Parameters of `Emulation.setVisibleSize`.
///
/// Resizes the frame/viewport of the page. Note that this does not affect the frame's container
/// (e.g. browser window). Can be used to produce screenshots of the specified size. Not supported
/// on Android.
///
/// **Experimental.** **Deprecated.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetVisibleSizeParams {
    /// Frame width (DIP).
    pub width: i64,
    /// Frame height (DIP).
    pub height: i64,
}

/// The answer to `Emulation.setVisibleSize`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetVisibleSizeReturns {}

impl SetVisibleSizeParams {
    pub const METHOD: &'static str = "Emulation.setVisibleSize";
}

impl super::Command for SetVisibleSizeParams {
    const METHOD: &'static str = "Emulation.setVisibleSize";
    type Returns = SetVisibleSizeReturns;
}

/// Parameters of `Emulation.setDisabledImageTypes`.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetDisabledImageTypesParams {
    /// Image types to disable.
    #[serde(rename = "imageTypes")]
    pub image_types: Vec<DisabledImageType>,
}

/// The answer to `Emulation.setDisabledImageTypes`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetDisabledImageTypesReturns {}

impl SetDisabledImageTypesParams {
    pub const METHOD: &'static str = "Emulation.setDisabledImageTypes";
}

impl super::Command for SetDisabledImageTypesParams {
    const METHOD: &'static str = "Emulation.setDisabledImageTypes";
    type Returns = SetDisabledImageTypesReturns;
}

/// Parameters of `Emulation.setDataSaverOverride`.
///
/// Override the value of navigator.connection.saveData
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetDataSaverOverrideParams {
    /// Override value. Omitting the parameter disables the override.
    #[serde(
        rename = "dataSaverEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub data_saver_enabled: Option<bool>,
}

/// The answer to `Emulation.setDataSaverOverride`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetDataSaverOverrideReturns {}

impl SetDataSaverOverrideParams {
    pub const METHOD: &'static str = "Emulation.setDataSaverOverride";
}

impl super::Command for SetDataSaverOverrideParams {
    const METHOD: &'static str = "Emulation.setDataSaverOverride";
    type Returns = SetDataSaverOverrideReturns;
}

/// Parameters of `Emulation.setHardwareConcurrencyOverride`.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetHardwareConcurrencyOverrideParams {
    /// Hardware concurrency to report
    #[serde(rename = "hardwareConcurrency")]
    pub hardware_concurrency: i64,
}

/// The answer to `Emulation.setHardwareConcurrencyOverride`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetHardwareConcurrencyOverrideReturns {}

impl SetHardwareConcurrencyOverrideParams {
    pub const METHOD: &'static str = "Emulation.setHardwareConcurrencyOverride";
}

impl super::Command for SetHardwareConcurrencyOverrideParams {
    const METHOD: &'static str = "Emulation.setHardwareConcurrencyOverride";
    type Returns = SetHardwareConcurrencyOverrideReturns;
}

/// Parameters of `Emulation.setCPUPerformanceOverride`.
///
/// Overrides the value of navigator.cpuPerformance
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetCPUPerformanceOverrideParams {
    /// Override value. Omitting the parameter disables the override.
    #[serde(
        rename = "performanceTier",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub performance_tier: Option<SetCPUPerformanceOverridePerformanceTier>,
}

/// Values of `SetCPUPerformanceOverride`'s `performanceTier`.
///
/// Override value. Omitting the parameter disables the override.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SetCPUPerformanceOverridePerformanceTier {
    /// `unknown`
    Unknown,
    /// `low`
    Low,
    /// `mid`
    Mid,
    /// `high`
    High,
    /// `ultra`
    Ultra,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    SetCPUPerformanceOverridePerformanceTier {
        Unknown => "unknown",
        Low => "low",
        Mid => "mid",
        High => "high",
        Ultra => "ultra",
    }
}

/// The answer to `Emulation.setCPUPerformanceOverride`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetCPUPerformanceOverrideReturns {}

impl SetCPUPerformanceOverrideParams {
    pub const METHOD: &'static str = "Emulation.setCPUPerformanceOverride";
}

impl super::Command for SetCPUPerformanceOverrideParams {
    const METHOD: &'static str = "Emulation.setCPUPerformanceOverride";
    type Returns = SetCPUPerformanceOverrideReturns;
}

/// Parameters of `Emulation.setUserAgentOverride`.
///
/// Allows overriding user agent with the given string.
/// `userAgentMetadata` must be set for Client Hint headers to be sent.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetUserAgentOverrideParams {
    /// User agent to use.
    #[serde(rename = "userAgent")]
    pub user_agent: String,
    /// Browser language to emulate.
    #[serde(
        rename = "acceptLanguage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub accept_language: Option<String>,
    /// The platform navigator.platform should return.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub platform: Option<String>,
    /// To be sent in Sec-CH-UA-* headers and returned in navigator.userAgentData
    ///
    /// **Experimental.**
    #[serde(
        rename = "userAgentMetadata",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub user_agent_metadata: Option<UserAgentMetadata>,
}

/// The answer to `Emulation.setUserAgentOverride`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetUserAgentOverrideReturns {}

impl SetUserAgentOverrideParams {
    pub const METHOD: &'static str = "Emulation.setUserAgentOverride";
}

impl super::Command for SetUserAgentOverrideParams {
    const METHOD: &'static str = "Emulation.setUserAgentOverride";
    type Returns = SetUserAgentOverrideReturns;
}

/// Parameters of `Emulation.setAutomationOverride`.
///
/// Allows overriding the automation flag.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetAutomationOverrideParams {
    /// Whether the override should be enabled.
    pub enabled: bool,
}

/// The answer to `Emulation.setAutomationOverride`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetAutomationOverrideReturns {}

impl SetAutomationOverrideParams {
    pub const METHOD: &'static str = "Emulation.setAutomationOverride";
}

impl super::Command for SetAutomationOverrideParams {
    const METHOD: &'static str = "Emulation.setAutomationOverride";
    type Returns = SetAutomationOverrideReturns;
}

/// Parameters of `Emulation.setSmallViewportHeightDifferenceOverride`.
///
/// Allows overriding the difference between the small and large viewport sizes, which determine the
/// value of the `svh` and `lvh` unit, respectively. Only supported for top-level frames.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetSmallViewportHeightDifferenceOverrideParams {
    /// This will cause an element of size 100svh to be `difference` pixels smaller than an element
    /// of size 100lvh.
    pub difference: i64,
}

/// The answer to `Emulation.setSmallViewportHeightDifferenceOverride`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetSmallViewportHeightDifferenceOverrideReturns {}

impl SetSmallViewportHeightDifferenceOverrideParams {
    pub const METHOD: &'static str = "Emulation.setSmallViewportHeightDifferenceOverride";
}

impl super::Command for SetSmallViewportHeightDifferenceOverrideParams {
    const METHOD: &'static str = "Emulation.setSmallViewportHeightDifferenceOverride";
    type Returns = SetSmallViewportHeightDifferenceOverrideReturns;
}

/// Parameters of `Emulation.getScreenInfos`.
///
/// Returns device's screen configuration. In headful mode, the physical screens configuration is returned,
/// whereas in headless mode, a virtual headless screen configuration is provided instead.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetScreenInfosParams {}

/// The answer to `Emulation.getScreenInfos`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetScreenInfosReturns {
    #[serde(rename = "screenInfos")]
    pub screen_infos: Vec<ScreenInfo>,
}

impl GetScreenInfosParams {
    pub const METHOD: &'static str = "Emulation.getScreenInfos";
}

impl super::Command for GetScreenInfosParams {
    const METHOD: &'static str = "Emulation.getScreenInfos";
    type Returns = GetScreenInfosReturns;
}

/// Parameters of `Emulation.addScreen`.
///
/// Add a new screen to the device. Only supported in headless mode.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AddScreenParams {
    /// Offset of the left edge of the screen in pixels.
    pub left: i64,
    /// Offset of the top edge of the screen in pixels.
    pub top: i64,
    /// The width of the screen in pixels.
    pub width: i64,
    /// The height of the screen in pixels.
    pub height: i64,
    /// Specifies the screen's work area. Default is entire screen.
    #[serde(
        rename = "workAreaInsets",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub work_area_insets: Option<WorkAreaInsets>,
    /// Specifies the screen's device pixel ratio. Default is 1.
    #[serde(
        rename = "devicePixelRatio",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub device_pixel_ratio: Option<f64>,
    /// Specifies the screen's rotation angle. Available values are 0, 90, 180 and 270. Default is 0.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rotation: Option<i64>,
    /// Specifies the screen's color depth in bits. Default is 24.
    #[serde(
        rename = "colorDepth",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub color_depth: Option<i64>,
    /// Specifies the descriptive label for the screen. Default is none.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// Indicates whether the screen is internal to the device or external, attached to the device. Default is false.
    #[serde(
        rename = "isInternal",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_internal: Option<bool>,
}

/// The answer to `Emulation.addScreen`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AddScreenReturns {
    #[serde(rename = "screenInfo")]
    pub screen_info: ScreenInfo,
}

impl AddScreenParams {
    pub const METHOD: &'static str = "Emulation.addScreen";
}

impl super::Command for AddScreenParams {
    const METHOD: &'static str = "Emulation.addScreen";
    type Returns = AddScreenReturns;
}

/// Parameters of `Emulation.updateScreen`.
///
/// Updates specified screen parameters. Only supported in headless mode.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateScreenParams {
    /// Target screen identifier.
    #[serde(rename = "screenId")]
    pub screen_id: ScreenId,
    /// Offset of the left edge of the screen in pixels.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub left: Option<i64>,
    /// Offset of the top edge of the screen in pixels.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub top: Option<i64>,
    /// The width of the screen in pixels.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub width: Option<i64>,
    /// The height of the screen in pixels.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub height: Option<i64>,
    /// Specifies the screen's work area.
    #[serde(
        rename = "workAreaInsets",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub work_area_insets: Option<WorkAreaInsets>,
    /// Specifies the screen's device pixel ratio.
    #[serde(
        rename = "devicePixelRatio",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub device_pixel_ratio: Option<f64>,
    /// Specifies the screen's rotation angle. Available values are 0, 90, 180 and 270.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rotation: Option<i64>,
    /// Specifies the screen's color depth in bits.
    #[serde(
        rename = "colorDepth",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub color_depth: Option<i64>,
    /// Specifies the descriptive label for the screen.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// Indicates whether the screen is internal to the device or external, attached to the device. Default is false.
    #[serde(
        rename = "isInternal",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_internal: Option<bool>,
}

/// The answer to `Emulation.updateScreen`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct UpdateScreenReturns {
    #[serde(rename = "screenInfo")]
    pub screen_info: ScreenInfo,
}

impl UpdateScreenParams {
    pub const METHOD: &'static str = "Emulation.updateScreen";
}

impl super::Command for UpdateScreenParams {
    const METHOD: &'static str = "Emulation.updateScreen";
    type Returns = UpdateScreenReturns;
}

/// Parameters of `Emulation.removeScreen`.
///
/// Remove screen from the device. Only supported in headless mode.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RemoveScreenParams {
    #[serde(rename = "screenId")]
    pub screen_id: ScreenId,
}

/// The answer to `Emulation.removeScreen`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RemoveScreenReturns {}

impl RemoveScreenParams {
    pub const METHOD: &'static str = "Emulation.removeScreen";
}

impl super::Command for RemoveScreenParams {
    const METHOD: &'static str = "Emulation.removeScreen";
    type Returns = RemoveScreenReturns;
}

/// Parameters of `Emulation.setPrimaryScreen`.
///
/// Set primary screen. Only supported in headless mode.
/// Note that this changes the coordinate system origin to the top-left
/// of the new primary screen, updating the bounds and work areas
/// of all existing screens accordingly.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetPrimaryScreenParams {
    #[serde(rename = "screenId")]
    pub screen_id: ScreenId,
}

/// The answer to `Emulation.setPrimaryScreen`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetPrimaryScreenReturns {}

impl SetPrimaryScreenParams {
    pub const METHOD: &'static str = "Emulation.setPrimaryScreen";
}

impl super::Command for SetPrimaryScreenParams {
    const METHOD: &'static str = "Emulation.setPrimaryScreen";
    type Returns = SetPrimaryScreenReturns;
}

/// The event `Emulation.virtualTimeBudgetExpired`.
///
/// Notification sent after the virtual time budget for the current VirtualTimePolicy has run out.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct VirtualTimeBudgetExpiredEvent {}

impl VirtualTimeBudgetExpiredEvent {
    pub const NAME: &'static str = "Emulation.virtualTimeBudgetExpired";
}

impl super::Event for VirtualTimeBudgetExpiredEvent {
    const NAME: &'static str = "Emulation.virtualTimeBudgetExpired";
}

/// The event `Emulation.screenOrientationLockChanged`.
///
/// Fired when a page calls screen.orientation.lock() or screen.orientation.unlock()
/// while device emulation is enabled. This allows the DevTools frontend to update the
/// emulated device orientation accordingly.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ScreenOrientationLockChangedEvent {
    /// Whether the screen orientation is currently locked.
    pub locked: bool,
    /// The orientation lock type requested by the page. Only set when locked is true.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub orientation: Option<ScreenOrientation>,
}

impl ScreenOrientationLockChangedEvent {
    pub const NAME: &'static str = "Emulation.screenOrientationLockChanged";
}

impl super::Event for ScreenOrientationLockChangedEvent {
    const NAME: &'static str = "Emulation.screenOrientationLockChanged";
}
