// Generated by eludite-cdp-generator from devtools-protocol 0.0.1709723 (protocol/cdp/PIN). Do not edit:
// change the generator or the pin and run `cargo run -p eludite-cdp-generator`.
//! The CDP domain `Log`.
//!
//! Provides access to log entries.

#![allow(
    clippy::upper_case_acronyms,
    clippy::doc_lazy_continuation,
    clippy::doc_overindented_list_items,
    clippy::large_enum_variant,
    clippy::empty_docs,
    clippy::struct_excessive_bools,
    rustdoc::bare_urls,
    rustdoc::broken_intra_doc_links,
    rustdoc::invalid_html_tags,
    rustdoc::invalid_rust_codeblocks
)]

use serde::{Deserialize, Serialize};

/// Log entry.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LogEntry {
    /// Log entry source.
    pub source: LogEntrySource,
    /// Log entry severity.
    pub level: LogEntryLevel,
    /// Logged text.
    pub text: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub category: Option<LogEntryCategory>,
    /// Timestamp when this entry was added.
    pub timestamp: super::runtime::Timestamp,
    /// URL of the resource if known.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Line number in the resource.
    #[serde(
        rename = "lineNumber",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub line_number: Option<i64>,
    /// JavaScript stack trace.
    #[serde(
        rename = "stackTrace",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub stack_trace: Option<super::runtime::StackTrace>,
    /// Identifier of the network request associated with this entry.
    #[serde(
        rename = "networkRequestId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub network_request_id: Option<super::network::RequestId>,
    /// Identifier of the worker associated with this entry.
    #[serde(rename = "workerId", default, skip_serializing_if = "Option::is_none")]
    pub worker_id: Option<String>,
    /// Call arguments.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub args: Option<Vec<super::runtime::RemoteObject>>,
}

/// Values of `LogEntry`'s `source`.
///
/// Log entry source.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum LogEntrySource {
    /// `xml`
    Xml,
    /// `javascript`
    Javascript,
    /// `network`
    Network,
    /// `storage`
    Storage,
    /// `appcache`
    Appcache,
    /// `rendering`
    Rendering,
    /// `security`
    Security,
    /// `deprecation`
    Deprecation,
    /// `worker`
    Worker,
    /// `violation`
    Violation,
    /// `intervention`
    Intervention,
    /// `recommendation`
    Recommendation,
    /// `other`
    OtherValue,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    LogEntrySource {
        Xml => "xml",
        Javascript => "javascript",
        Network => "network",
        Storage => "storage",
        Appcache => "appcache",
        Rendering => "rendering",
        Security => "security",
        Deprecation => "deprecation",
        Worker => "worker",
        Violation => "violation",
        Intervention => "intervention",
        Recommendation => "recommendation",
        OtherValue => "other",
    }
}

/// Values of `LogEntry`'s `level`.
///
/// Log entry severity.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum LogEntryLevel {
    /// `verbose`
    Verbose,
    /// `info`
    Info,
    /// `warning`
    Warning,
    /// `error`
    Error,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    LogEntryLevel {
        Verbose => "verbose",
        Info => "info",
        Warning => "warning",
        Error => "error",
    }
}

/// Values of `LogEntry`'s `category`.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum LogEntryCategory {
    /// `cors`
    Cors,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    LogEntryCategory {
        Cors => "cors",
    }
}

/// Violation configuration setting.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ViolationSetting {
    /// Violation type.
    pub name: ViolationSettingName,
    /// Time threshold to trigger upon.
    pub threshold: f64,
}

/// Values of `ViolationSetting`'s `name`.
///
/// Violation type.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ViolationSettingName {
    /// `longTask`
    LongTask,
    /// `longLayout`
    LongLayout,
    /// `blockedEvent`
    BlockedEvent,
    /// `blockedParser`
    BlockedParser,
    /// `discouragedAPIUse`
    DiscouragedAPIUse,
    /// `handler`
    Handler,
    /// `recurringHandler`
    RecurringHandler,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    ViolationSettingName {
        LongTask => "longTask",
        LongLayout => "longLayout",
        BlockedEvent => "blockedEvent",
        BlockedParser => "blockedParser",
        DiscouragedAPIUse => "discouragedAPIUse",
        Handler => "handler",
        RecurringHandler => "recurringHandler",
    }
}

/// Parameters of `Log.clear`.
///
/// Clears the log.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearParams {}

/// The answer to `Log.clear`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearReturns {}

impl ClearParams {
    pub const METHOD: &'static str = "Log.clear";
}

impl super::Command for ClearParams {
    const METHOD: &'static str = "Log.clear";
    type Returns = ClearReturns;
}

/// Parameters of `Log.disable`.
///
/// Disables log domain, prevents further log entries from being reported to the client.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DisableParams {}

/// The answer to `Log.disable`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DisableReturns {}

impl DisableParams {
    pub const METHOD: &'static str = "Log.disable";
}

impl super::Command for DisableParams {
    const METHOD: &'static str = "Log.disable";
    type Returns = DisableReturns;
}

/// Parameters of `Log.enable`.
///
/// Enables log domain, sends the entries collected so far to the client by means of the
/// `entryAdded` notification.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EnableParams {}

/// The answer to `Log.enable`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EnableReturns {}

impl EnableParams {
    pub const METHOD: &'static str = "Log.enable";
}

impl super::Command for EnableParams {
    const METHOD: &'static str = "Log.enable";
    type Returns = EnableReturns;
}

/// Parameters of `Log.startViolationsReport`.
///
/// start violation reporting.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct StartViolationsReportParams {
    /// Configuration for violations.
    pub config: Vec<ViolationSetting>,
}

/// The answer to `Log.startViolationsReport`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct StartViolationsReportReturns {}

impl StartViolationsReportParams {
    pub const METHOD: &'static str = "Log.startViolationsReport";
}

impl super::Command for StartViolationsReportParams {
    const METHOD: &'static str = "Log.startViolationsReport";
    type Returns = StartViolationsReportReturns;
}

/// Parameters of `Log.stopViolationsReport`.
///
/// Stop violation reporting.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct StopViolationsReportParams {}

/// The answer to `Log.stopViolationsReport`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct StopViolationsReportReturns {}

impl StopViolationsReportParams {
    pub const METHOD: &'static str = "Log.stopViolationsReport";
}

impl super::Command for StopViolationsReportParams {
    const METHOD: &'static str = "Log.stopViolationsReport";
    type Returns = StopViolationsReportReturns;
}

/// The event `Log.entryAdded`.
///
/// Issued when new message was logged.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EntryAddedEvent {
    /// The entry.
    pub entry: LogEntry,
}

impl EntryAddedEvent {
    pub const NAME: &'static str = "Log.entryAdded";
}

impl super::Event for EntryAddedEvent {
    const NAME: &'static str = "Log.entryAdded";
}
