// Generated by eludite-cdp-generator from devtools-protocol 0.0.1709723 (protocol/cdp/PIN). Do not edit:
// change the generator or the pin and run `cargo run -p eludite-cdp-generator`.
//! Chrome DevTools Protocol types, generated from the pinned protocol JSON in `protocol/cdp/` (brief 0023).
//!
//! The domains Eludite uses (Target, Page, DOM, Accessibility, Runtime, Log, Network, Input, Emulation, Browser, Security, Storage, DOMStorage) and every domain they reference. Each command has `<Command>Params`
//! (implementing [`Command`]) and `<Command>Returns`; each event a `<Event>Event` (implementing [`Event`]). Every
//! enum decodes a value this protocol version does not list as `Other(String)`, since Chrome adds values. The
//! message envelope (`id`, `method`, `params`, `sessionId`, `result`, `error`) is not described by the protocol
//! JSON; clients type it themselves.

#![allow(
    clippy::upper_case_acronyms,
    clippy::doc_lazy_continuation,
    clippy::doc_overindented_list_items,
    clippy::large_enum_variant,
    clippy::empty_docs,
    clippy::struct_excessive_bools,
    rustdoc::bare_urls,
    rustdoc::broken_intra_doc_links,
    rustdoc::invalid_html_tags,
    rustdoc::invalid_rust_codeblocks
)]

/// A CDP command: its parameters, its method name and the type of its answer.
pub trait Command: serde::Serialize {
    const METHOD: &'static str;
    type Returns: serde::de::DeserializeOwned;
}

/// A CDP event's parameters and its name.
pub trait Event: serde::de::DeserializeOwned {
    const NAME: &'static str;
}

/// The methods of a string enum with an `Other(String)` catch-all: `as_str`, `From<&str>`, `Display` and
/// serde as a plain string.
macro_rules! string_enum {
    ($name:ident { $($variant:ident => $value:literal,)* }) => {
        impl $name {
            /// The protocol's string.
            pub fn as_str(&self) -> &str {
                match self {
                    $(Self::$variant => $value,)*
                    Self::Other(s) => s,
                }
            }
        }

        impl From<&str> for $name {
            fn from(s: &str) -> Self {
                match s {
                    $($value => Self::$variant,)*
                    other => Self::Other(other.to_owned()),
                }
            }
        }

        impl std::fmt::Display for $name {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.write_str(self.as_str())
            }
        }

        impl serde::Serialize for $name {
            fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
                serializer.serialize_str(self.as_str())
            }
        }

        impl<'de> serde::Deserialize<'de> for $name {
            fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
                let s = <std::borrow::Cow<'de, str> as serde::Deserialize>::deserialize(deserializer)?;
                Ok(Self::from(s.as_ref()))
            }
        }
    };
}

pub mod accessibility;
pub mod browser;
pub mod debugger;
pub mod dom;
pub mod dom_storage;
pub mod emulation;
pub mod input;
pub mod io;
pub mod log;
pub mod network;
pub mod page;
pub mod runtime;
pub mod security;
pub mod storage;
pub mod target;
