// Generated by eludite-cdp-generator from devtools-protocol 0.0.1709723 (protocol/cdp/PIN). Do not edit:
// change the generator or the pin and run `cargo run -p eludite-cdp-generator`.
//! The CDP domain `Runtime`.
//!
//! Runtime domain exposes JavaScript runtime by means of remote evaluation and mirror objects.
//! Evaluation results are returned as mirror object that expose object type, string representation
//! and unique identifier that can be used for further object reference. Original objects are
//! maintained in memory unless they are either explicitly released or are released along with the
//! other objects in their object group.

#![allow(
    clippy::upper_case_acronyms,
    clippy::doc_lazy_continuation,
    clippy::doc_overindented_list_items,
    clippy::large_enum_variant,
    clippy::empty_docs,
    clippy::struct_excessive_bools,
    rustdoc::bare_urls,
    rustdoc::broken_intra_doc_links,
    rustdoc::invalid_html_tags,
    rustdoc::invalid_rust_codeblocks
)]

use serde::{Deserialize, Serialize};

/// Unique script identifier.
pub type ScriptId = String;

/// Represents options for serialization. Overrides `generatePreview` and `returnByValue`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SerializationOptions {
    pub serialization: SerializationOptionsSerialization,
    /// Deep serialization depth. Default is full depth. Respected only in `deep` serialization mode.
    #[serde(rename = "maxDepth", default, skip_serializing_if = "Option::is_none")]
    pub max_depth: Option<i64>,
    /// Embedder-specific parameters. For example if connected to V8 in Chrome these control DOM
    /// serialization via `maxNodeDepth: integer` and `includeShadowTree: "none" | "open" | "all"`.
    /// Values can be only of type string or integer.
    #[serde(
        rename = "additionalParameters",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub additional_parameters: Option<serde_json::Map<String, serde_json::Value>>,
}

/// Values of `SerializationOptions`'s `serialization`.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SerializationOptionsSerialization {
    /// `deep`
    Deep,
    /// `json`
    Json,
    /// `idOnly`
    IdOnly,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    SerializationOptionsSerialization {
        Deep => "deep",
        Json => "json",
        IdOnly => "idOnly",
    }
}

/// Represents deep serialized value.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DeepSerializedValue {
    #[serde(rename = "type")]
    pub type_: DeepSerializedValueType,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<serde_json::Value>,
    #[serde(rename = "objectId", default, skip_serializing_if = "Option::is_none")]
    pub object_id: Option<String>,
    /// Set if value reference met more then once during serialization. In such
    /// case, value is provided only to one of the serialized values. Unique
    /// per value in the scope of one CDP call.
    #[serde(
        rename = "weakLocalObjectReference",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub weak_local_object_reference: Option<i64>,
}

/// Values of `DeepSerializedValue`'s `type`.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum DeepSerializedValueType {
    /// `undefined`
    Undefined,
    /// `null`
    Null,
    /// `string`
    String,
    /// `number`
    Number,
    /// `boolean`
    Boolean,
    /// `bigint`
    Bigint,
    /// `regexp`
    Regexp,
    /// `date`
    Date,
    /// `symbol`
    Symbol,
    /// `array`
    Array,
    /// `object`
    Object,
    /// `function`
    Function,
    /// `map`
    Map,
    /// `set`
    Set,
    /// `weakmap`
    Weakmap,
    /// `weakset`
    Weakset,
    /// `error`
    Error,
    /// `proxy`
    Proxy,
    /// `promise`
    Promise,
    /// `typedarray`
    Typedarray,
    /// `arraybuffer`
    Arraybuffer,
    /// `node`
    Node,
    /// `window`
    Window,
    /// `generator`
    Generator,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    DeepSerializedValueType {
        Undefined => "undefined",
        Null => "null",
        String => "string",
        Number => "number",
        Boolean => "boolean",
        Bigint => "bigint",
        Regexp => "regexp",
        Date => "date",
        Symbol => "symbol",
        Array => "array",
        Object => "object",
        Function => "function",
        Map => "map",
        Set => "set",
        Weakmap => "weakmap",
        Weakset => "weakset",
        Error => "error",
        Proxy => "proxy",
        Promise => "promise",
        Typedarray => "typedarray",
        Arraybuffer => "arraybuffer",
        Node => "node",
        Window => "window",
        Generator => "generator",
    }
}

/// Unique object identifier.
pub type RemoteObjectId = String;

/// Primitive value which cannot be JSON-stringified. Includes values `-0`, `NaN`, `Infinity`,
/// `-Infinity`, and bigint literals.
pub type UnserializableValue = String;

/// Mirror object referencing original JavaScript object.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RemoteObject {
    /// Object type.
    #[serde(rename = "type")]
    pub type_: RemoteObjectType,
    /// Object subtype hint. Specified for `object` type values only.
    /// NOTE: If you change anything here, make sure to also update
    /// `subtype` in `ObjectPreview` and `PropertyPreview` below.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subtype: Option<RemoteObjectSubtype>,
    /// Object class (constructor) name. Specified for `object` type values only.
    #[serde(rename = "className", default, skip_serializing_if = "Option::is_none")]
    pub class_name: Option<String>,
    /// Remote object value in case of primitive values or JSON values (if it was requested).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<serde_json::Value>,
    /// Primitive value which can not be JSON-stringified does not have `value`, but gets this
    /// property.
    #[serde(
        rename = "unserializableValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unserializable_value: Option<UnserializableValue>,
    /// String representation of the object.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Deep serialized value.
    ///
    /// **Experimental.**
    #[serde(
        rename = "deepSerializedValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub deep_serialized_value: Option<DeepSerializedValue>,
    /// Unique object identifier (for non-primitive values).
    #[serde(rename = "objectId", default, skip_serializing_if = "Option::is_none")]
    pub object_id: Option<RemoteObjectId>,
    /// Preview containing abbreviated property values. Specified for `object` type values only.
    ///
    /// **Experimental.**
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub preview: Option<ObjectPreview>,
    /// **Experimental.**
    #[serde(
        rename = "customPreview",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub custom_preview: Option<CustomPreview>,
}

/// Values of `RemoteObject`'s `type`.
///
/// Object type.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum RemoteObjectType {
    /// `object`
    Object,
    /// `function`
    Function,
    /// `undefined`
    Undefined,
    /// `string`
    String,
    /// `number`
    Number,
    /// `boolean`
    Boolean,
    /// `symbol`
    Symbol,
    /// `bigint`
    Bigint,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    RemoteObjectType {
        Object => "object",
        Function => "function",
        Undefined => "undefined",
        String => "string",
        Number => "number",
        Boolean => "boolean",
        Symbol => "symbol",
        Bigint => "bigint",
    }
}

/// Values of `RemoteObject`'s `subtype`.
///
/// Object subtype hint. Specified for `object` type values only.
/// NOTE: If you change anything here, make sure to also update
/// `subtype` in `ObjectPreview` and `PropertyPreview` below.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum RemoteObjectSubtype {
    /// `array`
    Array,
    /// `null`
    Null,
    /// `node`
    Node,
    /// `regexp`
    Regexp,
    /// `date`
    Date,
    /// `map`
    Map,
    /// `set`
    Set,
    /// `weakmap`
    Weakmap,
    /// `weakset`
    Weakset,
    /// `iterator`
    Iterator,
    /// `generator`
    Generator,
    /// `error`
    Error,
    /// `proxy`
    Proxy,
    /// `promise`
    Promise,
    /// `typedarray`
    Typedarray,
    /// `arraybuffer`
    Arraybuffer,
    /// `dataview`
    Dataview,
    /// `webassemblymemory`
    Webassemblymemory,
    /// `wasmvalue`
    Wasmvalue,
    /// `deferredmodule`
    Deferredmodule,
    /// `trustedtype`
    Trustedtype,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    RemoteObjectSubtype {
        Array => "array",
        Null => "null",
        Node => "node",
        Regexp => "regexp",
        Date => "date",
        Map => "map",
        Set => "set",
        Weakmap => "weakmap",
        Weakset => "weakset",
        Iterator => "iterator",
        Generator => "generator",
        Error => "error",
        Proxy => "proxy",
        Promise => "promise",
        Typedarray => "typedarray",
        Arraybuffer => "arraybuffer",
        Dataview => "dataview",
        Webassemblymemory => "webassemblymemory",
        Wasmvalue => "wasmvalue",
        Deferredmodule => "deferredmodule",
        Trustedtype => "trustedtype",
    }
}

/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CustomPreview {
    /// The JSON-stringified result of formatter.header(object, config) call.
    /// It contains json ML array that represents RemoteObject.
    pub header: String,
    /// If formatter returns true as a result of formatter.hasBody call then bodyGetterId will
    /// contain RemoteObjectId for the function that returns result of formatter.body(object, config) call.
    /// The result value is json ML array.
    #[serde(
        rename = "bodyGetterId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub body_getter_id: Option<RemoteObjectId>,
}

/// Object containing abbreviated remote object value.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ObjectPreview {
    /// Object type.
    #[serde(rename = "type")]
    pub type_: ObjectPreviewType,
    /// Object subtype hint. Specified for `object` type values only.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subtype: Option<ObjectPreviewSubtype>,
    /// String representation of the object.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// True iff some of the properties or entries of the original object did not fit.
    pub overflow: bool,
    /// List of the properties.
    pub properties: Vec<PropertyPreview>,
    /// List of the entries. Specified for `map` and `set` subtype values only.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub entries: Option<Vec<EntryPreview>>,
}

/// Values of `ObjectPreview`'s `type`.
///
/// Object type.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ObjectPreviewType {
    /// `object`
    Object,
    /// `function`
    Function,
    /// `undefined`
    Undefined,
    /// `string`
    String,
    /// `number`
    Number,
    /// `boolean`
    Boolean,
    /// `symbol`
    Symbol,
    /// `bigint`
    Bigint,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    ObjectPreviewType {
        Object => "object",
        Function => "function",
        Undefined => "undefined",
        String => "string",
        Number => "number",
        Boolean => "boolean",
        Symbol => "symbol",
        Bigint => "bigint",
    }
}

/// Values of `ObjectPreview`'s `subtype`.
///
/// Object subtype hint. Specified for `object` type values only.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ObjectPreviewSubtype {
    /// `array`
    Array,
    /// `null`
    Null,
    /// `node`
    Node,
    /// `regexp`
    Regexp,
    /// `date`
    Date,
    /// `map`
    Map,
    /// `set`
    Set,
    /// `weakmap`
    Weakmap,
    /// `weakset`
    Weakset,
    /// `iterator`
    Iterator,
    /// `generator`
    Generator,
    /// `error`
    Error,
    /// `proxy`
    Proxy,
    /// `promise`
    Promise,
    /// `typedarray`
    Typedarray,
    /// `arraybuffer`
    Arraybuffer,
    /// `dataview`
    Dataview,
    /// `webassemblymemory`
    Webassemblymemory,
    /// `wasmvalue`
    Wasmvalue,
    /// `deferredmodule`
    Deferredmodule,
    /// `trustedtype`
    Trustedtype,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    ObjectPreviewSubtype {
        Array => "array",
        Null => "null",
        Node => "node",
        Regexp => "regexp",
        Date => "date",
        Map => "map",
        Set => "set",
        Weakmap => "weakmap",
        Weakset => "weakset",
        Iterator => "iterator",
        Generator => "generator",
        Error => "error",
        Proxy => "proxy",
        Promise => "promise",
        Typedarray => "typedarray",
        Arraybuffer => "arraybuffer",
        Dataview => "dataview",
        Webassemblymemory => "webassemblymemory",
        Wasmvalue => "wasmvalue",
        Deferredmodule => "deferredmodule",
        Trustedtype => "trustedtype",
    }
}

/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PropertyPreview {
    /// Property name.
    pub name: String,
    /// Object type. Accessor means that the property itself is an accessor property.
    #[serde(rename = "type")]
    pub type_: PropertyPreviewType,
    /// User-friendly property value string.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    /// Nested value preview.
    #[serde(
        rename = "valuePreview",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub value_preview: Option<ObjectPreview>,
    /// Object subtype hint. Specified for `object` type values only.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subtype: Option<PropertyPreviewSubtype>,
}

/// Values of `PropertyPreview`'s `type`.
///
/// Object type. Accessor means that the property itself is an accessor property.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum PropertyPreviewType {
    /// `object`
    Object,
    /// `function`
    Function,
    /// `undefined`
    Undefined,
    /// `string`
    String,
    /// `number`
    Number,
    /// `boolean`
    Boolean,
    /// `symbol`
    Symbol,
    /// `accessor`
    Accessor,
    /// `bigint`
    Bigint,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    PropertyPreviewType {
        Object => "object",
        Function => "function",
        Undefined => "undefined",
        String => "string",
        Number => "number",
        Boolean => "boolean",
        Symbol => "symbol",
        Accessor => "accessor",
        Bigint => "bigint",
    }
}

/// Values of `PropertyPreview`'s `subtype`.
///
/// Object subtype hint. Specified for `object` type values only.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum PropertyPreviewSubtype {
    /// `array`
    Array,
    /// `null`
    Null,
    /// `node`
    Node,
    /// `regexp`
    Regexp,
    /// `date`
    Date,
    /// `map`
    Map,
    /// `set`
    Set,
    /// `weakmap`
    Weakmap,
    /// `weakset`
    Weakset,
    /// `iterator`
    Iterator,
    /// `generator`
    Generator,
    /// `error`
    Error,
    /// `proxy`
    Proxy,
    /// `promise`
    Promise,
    /// `typedarray`
    Typedarray,
    /// `arraybuffer`
    Arraybuffer,
    /// `dataview`
    Dataview,
    /// `webassemblymemory`
    Webassemblymemory,
    /// `wasmvalue`
    Wasmvalue,
    /// `deferredmodule`
    Deferredmodule,
    /// `trustedtype`
    Trustedtype,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    PropertyPreviewSubtype {
        Array => "array",
        Null => "null",
        Node => "node",
        Regexp => "regexp",
        Date => "date",
        Map => "map",
        Set => "set",
        Weakmap => "weakmap",
        Weakset => "weakset",
        Iterator => "iterator",
        Generator => "generator",
        Error => "error",
        Proxy => "proxy",
        Promise => "promise",
        Typedarray => "typedarray",
        Arraybuffer => "arraybuffer",
        Dataview => "dataview",
        Webassemblymemory => "webassemblymemory",
        Wasmvalue => "wasmvalue",
        Deferredmodule => "deferredmodule",
        Trustedtype => "trustedtype",
    }
}

/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EntryPreview {
    /// Preview of the key. Specified for map-like collection entries.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<ObjectPreview>,
    /// Preview of the value.
    pub value: ObjectPreview,
}

/// Object property descriptor.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct PropertyDescriptor {
    /// Property name or symbol description.
    pub name: String,
    /// The value associated with the property.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<RemoteObject>,
    /// True if the value associated with the property may be changed (data descriptors only).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub writable: Option<bool>,
    /// A function which serves as a getter for the property, or `undefined` if there is no getter
    /// (accessor descriptors only).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub get: Option<RemoteObject>,
    /// A function which serves as a setter for the property, or `undefined` if there is no setter
    /// (accessor descriptors only).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub set: Option<RemoteObject>,
    /// True if the type of this property descriptor may be changed and if the property may be
    /// deleted from the corresponding object.
    pub configurable: bool,
    /// True if this property shows up during enumeration of the properties on the corresponding
    /// object.
    pub enumerable: bool,
    /// True if the result was thrown during the evaluation.
    #[serde(rename = "wasThrown", default, skip_serializing_if = "Option::is_none")]
    pub was_thrown: Option<bool>,
    /// True if the property is owned for the object.
    #[serde(rename = "isOwn", default, skip_serializing_if = "Option::is_none")]
    pub is_own: Option<bool>,
    /// Property symbol object, if the property is of the `symbol` type.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub symbol: Option<RemoteObject>,
}

/// Object internal property descriptor. This property isn't normally visible in JavaScript code.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct InternalPropertyDescriptor {
    /// Conventional property name.
    pub name: String,
    /// The value associated with the property.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<RemoteObject>,
}

/// Object private field descriptor.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct PrivatePropertyDescriptor {
    /// Private property name.
    pub name: String,
    /// The value associated with the private property.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<RemoteObject>,
    /// A function which serves as a getter for the private property,
    /// or `undefined` if there is no getter (accessor descriptors only).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub get: Option<RemoteObject>,
    /// A function which serves as a setter for the private property,
    /// or `undefined` if there is no setter (accessor descriptors only).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub set: Option<RemoteObject>,
}

/// Represents function call argument. Either remote object id `objectId`, primitive `value`,
/// unserializable primitive value or neither of (for undefined) them should be specified.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CallArgument {
    /// Primitive value or serializable javascript object.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<serde_json::Value>,
    /// Primitive value which can not be JSON-stringified.
    #[serde(
        rename = "unserializableValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unserializable_value: Option<UnserializableValue>,
    /// Remote object handle.
    #[serde(rename = "objectId", default, skip_serializing_if = "Option::is_none")]
    pub object_id: Option<RemoteObjectId>,
}

/// Id of an execution context.
pub type ExecutionContextId = i64;

/// Description of an isolated world.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ExecutionContextDescription {
    /// Unique id of the execution context. It can be used to specify in which execution context
    /// script evaluation should be performed.
    pub id: ExecutionContextId,
    /// Execution context origin.
    pub origin: String,
    /// Human readable name describing given context.
    pub name: String,
    /// A system-unique execution context identifier. Unlike the id, this is unique across
    /// multiple processes, so can be reliably used to identify specific context while backend
    /// performs a cross-process navigation.
    ///
    /// **Experimental.**
    #[serde(rename = "uniqueId")]
    pub unique_id: String,
    /// Embedder-specific auxiliary data likely matching {isDefault: boolean, type: 'default'|'isolated'|'worker', frameId: string}
    #[serde(rename = "auxData", default, skip_serializing_if = "Option::is_none")]
    pub aux_data: Option<serde_json::Map<String, serde_json::Value>>,
}

/// Detailed information about exception (or error) that was thrown during script compilation or
/// execution.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ExceptionDetails {
    /// Exception id.
    #[serde(rename = "exceptionId")]
    pub exception_id: i64,
    /// Exception text, which should be used together with exception object when available.
    pub text: String,
    /// Line number of the exception location (0-based).
    #[serde(rename = "lineNumber")]
    pub line_number: i64,
    /// Column number of the exception location (0-based).
    #[serde(rename = "columnNumber")]
    pub column_number: i64,
    /// Script ID of the exception location.
    #[serde(rename = "scriptId", default, skip_serializing_if = "Option::is_none")]
    pub script_id: Option<ScriptId>,
    /// URL of the exception location, to be used when the script was not reported.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// JavaScript stack trace if available.
    #[serde(
        rename = "stackTrace",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub stack_trace: Option<StackTrace>,
    /// Exception object if available.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exception: Option<RemoteObject>,
    /// Identifier of the context where exception happened.
    #[serde(
        rename = "executionContextId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub execution_context_id: Option<ExecutionContextId>,
    /// Dictionary with entries of meta data that the client associated
    /// with this exception, such as information about associated network
    /// requests, etc.
    ///
    /// **Experimental.**
    #[serde(
        rename = "exceptionMetaData",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub exception_meta_data: Option<serde_json::Map<String, serde_json::Value>>,
}

/// Number of milliseconds since epoch.
pub type Timestamp = f64;

/// Number of milliseconds.
pub type TimeDelta = f64;

/// Stack entry for runtime errors and assertions.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CallFrame {
    /// JavaScript function name.
    #[serde(rename = "functionName")]
    pub function_name: String,
    /// JavaScript script id.
    #[serde(rename = "scriptId")]
    pub script_id: ScriptId,
    /// JavaScript script name or url.
    pub url: String,
    /// JavaScript script line number (0-based).
    #[serde(rename = "lineNumber")]
    pub line_number: i64,
    /// JavaScript script column number (0-based).
    #[serde(rename = "columnNumber")]
    pub column_number: i64,
}

/// Call frames for assertions or error messages.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct StackTrace {
    /// String label of this stack trace. For async traces this may be a name of the function that
    /// initiated the async call.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// JavaScript function name.
    #[serde(rename = "callFrames")]
    pub call_frames: Vec<CallFrame>,
    /// Asynchronous JavaScript stack trace that preceded this stack, if available.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent: Option<Box<StackTrace>>,
    /// Asynchronous JavaScript stack trace that preceded this stack, if available.
    ///
    /// **Experimental.**
    #[serde(rename = "parentId", default, skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<StackTraceId>,
}

/// Unique identifier of current debugger.
///
/// **Experimental.**
pub type UniqueDebuggerId = String;

/// If `debuggerId` is set stack trace comes from another debugger and can be resolved there. This
/// allows to track cross-debugger calls. See `Runtime.StackTrace` and `Debugger.paused` for usages.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct StackTraceId {
    pub id: String,
    #[serde(
        rename = "debuggerId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub debugger_id: Option<UniqueDebuggerId>,
}

/// Parameters of `Runtime.awaitPromise`.
///
/// Add handler to promise with given promise object id.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AwaitPromiseParams {
    /// Identifier of the promise.
    #[serde(rename = "promiseObjectId")]
    pub promise_object_id: RemoteObjectId,
    /// Whether the result is expected to be a JSON object that should be sent by value.
    #[serde(
        rename = "returnByValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub return_by_value: Option<bool>,
    /// Whether preview should be generated for the result.
    #[serde(
        rename = "generatePreview",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub generate_preview: Option<bool>,
}

/// The answer to `Runtime.awaitPromise`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AwaitPromiseReturns {
    /// Promise result. Will contain rejected value if promise was rejected.
    pub result: RemoteObject,
    /// Exception details if stack strace is available.
    #[serde(
        rename = "exceptionDetails",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub exception_details: Option<ExceptionDetails>,
}

impl AwaitPromiseParams {
    pub const METHOD: &'static str = "Runtime.awaitPromise";
}

impl super::Command for AwaitPromiseParams {
    const METHOD: &'static str = "Runtime.awaitPromise";
    type Returns = AwaitPromiseReturns;
}

/// Parameters of `Runtime.callFunctionOn`.
///
/// Calls function with given declaration on the given object. Object group of the result is
/// inherited from the target object.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CallFunctionOnParams {
    /// Declaration of the function to call.
    #[serde(rename = "functionDeclaration")]
    pub function_declaration: String,
    /// Identifier of the object to call function on. Either objectId or executionContextId should
    /// be specified.
    #[serde(rename = "objectId", default, skip_serializing_if = "Option::is_none")]
    pub object_id: Option<RemoteObjectId>,
    /// Call arguments. All call arguments must belong to the same JavaScript world as the target
    /// object.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arguments: Option<Vec<CallArgument>>,
    /// In silent mode exceptions thrown during evaluation are not reported and do not pause
    /// execution. Overrides `setPauseOnException` state.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub silent: Option<bool>,
    /// Whether the result is expected to be a JSON object which should be sent by value.
    /// Can be overriden by `serializationOptions`.
    #[serde(
        rename = "returnByValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub return_by_value: Option<bool>,
    /// Whether preview should be generated for the result.
    ///
    /// **Experimental.**
    #[serde(
        rename = "generatePreview",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub generate_preview: Option<bool>,
    /// Whether execution should be treated as initiated by user in the UI.
    #[serde(
        rename = "userGesture",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub user_gesture: Option<bool>,
    /// Whether execution should `await` for resulting value and return once awaited promise is
    /// resolved.
    #[serde(
        rename = "awaitPromise",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub await_promise: Option<bool>,
    /// Specifies execution context which global object will be used to call function on. Either
    /// executionContextId or objectId should be specified.
    #[serde(
        rename = "executionContextId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub execution_context_id: Option<ExecutionContextId>,
    /// Symbolic group name that can be used to release multiple objects. If objectGroup is not
    /// specified and objectId is, objectGroup will be inherited from object.
    #[serde(
        rename = "objectGroup",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub object_group: Option<String>,
    /// Whether to throw an exception if side effect cannot be ruled out during evaluation.
    ///
    /// **Experimental.**
    #[serde(
        rename = "throwOnSideEffect",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub throw_on_side_effect: Option<bool>,
    /// An alternative way to specify the execution context to call function on.
    /// Compared to contextId that may be reused across processes, this is guaranteed to be
    /// system-unique, so it can be used to prevent accidental function call
    /// in context different than intended (e.g. as a result of navigation across process
    /// boundaries).
    /// This is mutually exclusive with `executionContextId`.
    ///
    /// **Experimental.**
    #[serde(
        rename = "uniqueContextId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unique_context_id: Option<String>,
    /// Specifies the result serialization. If provided, overrides
    /// `generatePreview` and `returnByValue`.
    ///
    /// **Experimental.**
    #[serde(
        rename = "serializationOptions",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub serialization_options: Option<SerializationOptions>,
}

/// The answer to `Runtime.callFunctionOn`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CallFunctionOnReturns {
    /// Call result.
    pub result: RemoteObject,
    /// Exception details.
    #[serde(
        rename = "exceptionDetails",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub exception_details: Option<ExceptionDetails>,
}

impl CallFunctionOnParams {
    pub const METHOD: &'static str = "Runtime.callFunctionOn";
}

impl super::Command for CallFunctionOnParams {
    const METHOD: &'static str = "Runtime.callFunctionOn";
    type Returns = CallFunctionOnReturns;
}

/// Parameters of `Runtime.compileScript`.
///
/// Compiles expression.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CompileScriptParams {
    /// Expression to compile.
    pub expression: String,
    /// Source url to be set for the script.
    #[serde(rename = "sourceURL")]
    pub source_url: String,
    /// Specifies whether the compiled script should be persisted.
    #[serde(rename = "persistScript")]
    pub persist_script: bool,
    /// Specifies in which execution context to perform script run. If the parameter is omitted the
    /// evaluation will be performed in the context of the inspected page.
    #[serde(
        rename = "executionContextId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub execution_context_id: Option<ExecutionContextId>,
}

/// The answer to `Runtime.compileScript`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CompileScriptReturns {
    /// Id of the script.
    #[serde(rename = "scriptId", default, skip_serializing_if = "Option::is_none")]
    pub script_id: Option<ScriptId>,
    /// Exception details.
    #[serde(
        rename = "exceptionDetails",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub exception_details: Option<ExceptionDetails>,
}

impl CompileScriptParams {
    pub const METHOD: &'static str = "Runtime.compileScript";
}

impl super::Command for CompileScriptParams {
    const METHOD: &'static str = "Runtime.compileScript";
    type Returns = CompileScriptReturns;
}

/// Parameters of `Runtime.disable`.
///
/// Disables reporting of execution contexts creation.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DisableParams {}

/// The answer to `Runtime.disable`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DisableReturns {}

impl DisableParams {
    pub const METHOD: &'static str = "Runtime.disable";
}

impl super::Command for DisableParams {
    const METHOD: &'static str = "Runtime.disable";
    type Returns = DisableReturns;
}

/// Parameters of `Runtime.discardConsoleEntries`.
///
/// Discards collected exceptions and console API calls.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DiscardConsoleEntriesParams {}

/// The answer to `Runtime.discardConsoleEntries`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DiscardConsoleEntriesReturns {}

impl DiscardConsoleEntriesParams {
    pub const METHOD: &'static str = "Runtime.discardConsoleEntries";
}

impl super::Command for DiscardConsoleEntriesParams {
    const METHOD: &'static str = "Runtime.discardConsoleEntries";
    type Returns = DiscardConsoleEntriesReturns;
}

/// Parameters of `Runtime.enable`.
///
/// Enables reporting of execution contexts creation by means of `executionContextCreated` event.
/// When the reporting gets enabled the event will be sent immediately for each existing execution
/// context.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EnableParams {}

/// The answer to `Runtime.enable`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EnableReturns {}

impl EnableParams {
    pub const METHOD: &'static str = "Runtime.enable";
}

impl super::Command for EnableParams {
    const METHOD: &'static str = "Runtime.enable";
    type Returns = EnableReturns;
}

/// Parameters of `Runtime.evaluate`.
///
/// Evaluates expression on global object.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EvaluateParams {
    /// Expression to evaluate.
    pub expression: String,
    /// Symbolic group name that can be used to release multiple objects.
    #[serde(
        rename = "objectGroup",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub object_group: Option<String>,
    /// Determines whether Command Line API should be available during the evaluation.
    #[serde(
        rename = "includeCommandLineAPI",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub include_command_line_api: Option<bool>,
    /// In silent mode exceptions thrown during evaluation are not reported and do not pause
    /// execution. Overrides `setPauseOnException` state.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub silent: Option<bool>,
    /// Specifies in which execution context to perform evaluation. If the parameter is omitted the
    /// evaluation will be performed in the context of the inspected page.
    /// This is mutually exclusive with `uniqueContextId`, which offers an
    /// alternative way to identify the execution context that is more reliable
    /// in a multi-process environment.
    #[serde(rename = "contextId", default, skip_serializing_if = "Option::is_none")]
    pub context_id: Option<ExecutionContextId>,
    /// Whether the result is expected to be a JSON object that should be sent by value.
    #[serde(
        rename = "returnByValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub return_by_value: Option<bool>,
    /// Whether preview should be generated for the result.
    ///
    /// **Experimental.**
    #[serde(
        rename = "generatePreview",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub generate_preview: Option<bool>,
    /// Whether execution should be treated as initiated by user in the UI.
    #[serde(
        rename = "userGesture",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub user_gesture: Option<bool>,
    /// Whether execution should `await` for resulting value and return once awaited promise is
    /// resolved.
    #[serde(
        rename = "awaitPromise",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub await_promise: Option<bool>,
    /// Whether to throw an exception if side effect cannot be ruled out during evaluation.
    /// This implies `disableBreaks` below.
    ///
    /// **Experimental.**
    #[serde(
        rename = "throwOnSideEffect",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub throw_on_side_effect: Option<bool>,
    /// Terminate execution after timing out (number of milliseconds).
    ///
    /// **Experimental.**
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeout: Option<TimeDelta>,
    /// Disable breakpoints during execution.
    ///
    /// **Experimental.**
    #[serde(
        rename = "disableBreaks",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub disable_breaks: Option<bool>,
    /// Setting this flag to true enables `let` re-declaration and top-level `await`.
    /// Note that `let` variables can only be re-declared if they originate from
    /// `replMode` themselves.
    ///
    /// **Experimental.**
    #[serde(rename = "replMode", default, skip_serializing_if = "Option::is_none")]
    pub repl_mode: Option<bool>,
    /// The Content Security Policy (CSP) for the target might block 'unsafe-eval'
    /// which includes eval(), Function(), setTimeout() and setInterval()
    /// when called with non-callable arguments. This flag bypasses CSP for this
    /// evaluation and allows unsafe-eval. Defaults to true.
    ///
    /// **Experimental.**
    #[serde(
        rename = "allowUnsafeEvalBlockedByCSP",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub allow_unsafe_eval_blocked_by_csp: Option<bool>,
    /// An alternative way to specify the execution context to evaluate in.
    /// Compared to contextId that may be reused across processes, this is guaranteed to be
    /// system-unique, so it can be used to prevent accidental evaluation of the expression
    /// in context different than intended (e.g. as a result of navigation across process
    /// boundaries).
    /// This is mutually exclusive with `contextId`.
    ///
    /// **Experimental.**
    #[serde(
        rename = "uniqueContextId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unique_context_id: Option<String>,
    /// Specifies the result serialization. If provided, overrides
    /// `generatePreview` and `returnByValue`.
    ///
    /// **Experimental.**
    #[serde(
        rename = "serializationOptions",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub serialization_options: Option<SerializationOptions>,
}

/// The answer to `Runtime.evaluate`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EvaluateReturns {
    /// Evaluation result.
    pub result: RemoteObject,
    /// Exception details.
    #[serde(
        rename = "exceptionDetails",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub exception_details: Option<ExceptionDetails>,
}

impl EvaluateParams {
    pub const METHOD: &'static str = "Runtime.evaluate";
}

impl super::Command for EvaluateParams {
    const METHOD: &'static str = "Runtime.evaluate";
    type Returns = EvaluateReturns;
}

/// Parameters of `Runtime.getIsolateId`.
///
/// Returns the isolate id.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetIsolateIdParams {}

/// The answer to `Runtime.getIsolateId`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetIsolateIdReturns {
    /// The isolate id.
    pub id: String,
}

impl GetIsolateIdParams {
    pub const METHOD: &'static str = "Runtime.getIsolateId";
}

impl super::Command for GetIsolateIdParams {
    const METHOD: &'static str = "Runtime.getIsolateId";
    type Returns = GetIsolateIdReturns;
}

/// Parameters of `Runtime.getHeapUsage`.
///
/// Returns the JavaScript heap usage.
/// It is the total usage of the corresponding isolate not scoped to a particular Runtime.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetHeapUsageParams {}

/// The answer to `Runtime.getHeapUsage`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetHeapUsageReturns {
    /// Used JavaScript heap size in bytes.
    #[serde(rename = "usedSize")]
    pub used_size: f64,
    /// Allocated JavaScript heap size in bytes.
    #[serde(rename = "totalSize")]
    pub total_size: f64,
    /// Used size in bytes in the embedder's garbage-collected heap.
    #[serde(rename = "embedderHeapUsedSize")]
    pub embedder_heap_used_size: f64,
    /// Size in bytes of backing storage for array buffers and external strings.
    #[serde(rename = "backingStorageSize")]
    pub backing_storage_size: f64,
}

impl GetHeapUsageParams {
    pub const METHOD: &'static str = "Runtime.getHeapUsage";
}

impl super::Command for GetHeapUsageParams {
    const METHOD: &'static str = "Runtime.getHeapUsage";
    type Returns = GetHeapUsageReturns;
}

/// Parameters of `Runtime.getProperties`.
///
/// Returns properties of a given object. Object group of the result is inherited from the target
/// object.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetPropertiesParams {
    /// Identifier of the object to return properties for.
    #[serde(rename = "objectId")]
    pub object_id: RemoteObjectId,
    /// If true, returns properties belonging only to the element itself, not to its prototype
    /// chain.
    #[serde(
        rename = "ownProperties",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub own_properties: Option<bool>,
    /// If true, returns accessor properties (with getter/setter) only; internal properties are not
    /// returned either.
    ///
    /// **Experimental.**
    #[serde(
        rename = "accessorPropertiesOnly",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub accessor_properties_only: Option<bool>,
    /// Whether preview should be generated for the results.
    ///
    /// **Experimental.**
    #[serde(
        rename = "generatePreview",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub generate_preview: Option<bool>,
    /// If true, returns non-indexed properties only.
    ///
    /// **Experimental.**
    #[serde(
        rename = "nonIndexedPropertiesOnly",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub non_indexed_properties_only: Option<bool>,
}

/// The answer to `Runtime.getProperties`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetPropertiesReturns {
    /// Object properties.
    pub result: Vec<PropertyDescriptor>,
    /// Internal object properties (only of the element itself).
    #[serde(
        rename = "internalProperties",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub internal_properties: Option<Vec<InternalPropertyDescriptor>>,
    /// Object private properties.
    ///
    /// **Experimental.**
    #[serde(
        rename = "privateProperties",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub private_properties: Option<Vec<PrivatePropertyDescriptor>>,
    /// Exception details.
    #[serde(
        rename = "exceptionDetails",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub exception_details: Option<ExceptionDetails>,
}

impl GetPropertiesParams {
    pub const METHOD: &'static str = "Runtime.getProperties";
}

impl super::Command for GetPropertiesParams {
    const METHOD: &'static str = "Runtime.getProperties";
    type Returns = GetPropertiesReturns;
}

/// Parameters of `Runtime.globalLexicalScopeNames`.
///
/// Returns all let, const and class variables from global scope.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GlobalLexicalScopeNamesParams {
    /// Specifies in which execution context to lookup global scope variables.
    #[serde(
        rename = "executionContextId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub execution_context_id: Option<ExecutionContextId>,
}

/// The answer to `Runtime.globalLexicalScopeNames`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GlobalLexicalScopeNamesReturns {
    pub names: Vec<String>,
}

impl GlobalLexicalScopeNamesParams {
    pub const METHOD: &'static str = "Runtime.globalLexicalScopeNames";
}

impl super::Command for GlobalLexicalScopeNamesParams {
    const METHOD: &'static str = "Runtime.globalLexicalScopeNames";
    type Returns = GlobalLexicalScopeNamesReturns;
}

/// Parameters of `Runtime.queryObjects`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct QueryObjectsParams {
    /// Identifier of the prototype to return objects for.
    #[serde(rename = "prototypeObjectId")]
    pub prototype_object_id: RemoteObjectId,
    /// Symbolic group name that can be used to release the results.
    #[serde(
        rename = "objectGroup",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub object_group: Option<String>,
}

/// The answer to `Runtime.queryObjects`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct QueryObjectsReturns {
    /// Array with objects.
    pub objects: RemoteObject,
}

impl QueryObjectsParams {
    pub const METHOD: &'static str = "Runtime.queryObjects";
}

impl super::Command for QueryObjectsParams {
    const METHOD: &'static str = "Runtime.queryObjects";
    type Returns = QueryObjectsReturns;
}

/// Parameters of `Runtime.releaseObject`.
///
/// Releases remote object with given id.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ReleaseObjectParams {
    /// Identifier of the object to release.
    #[serde(rename = "objectId")]
    pub object_id: RemoteObjectId,
}

/// The answer to `Runtime.releaseObject`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ReleaseObjectReturns {}

impl ReleaseObjectParams {
    pub const METHOD: &'static str = "Runtime.releaseObject";
}

impl super::Command for ReleaseObjectParams {
    const METHOD: &'static str = "Runtime.releaseObject";
    type Returns = ReleaseObjectReturns;
}

/// Parameters of `Runtime.releaseObjectGroup`.
///
/// Releases all remote objects that belong to a given group.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ReleaseObjectGroupParams {
    /// Symbolic object group name.
    #[serde(rename = "objectGroup")]
    pub object_group: String,
}

/// The answer to `Runtime.releaseObjectGroup`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ReleaseObjectGroupReturns {}

impl ReleaseObjectGroupParams {
    pub const METHOD: &'static str = "Runtime.releaseObjectGroup";
}

impl super::Command for ReleaseObjectGroupParams {
    const METHOD: &'static str = "Runtime.releaseObjectGroup";
    type Returns = ReleaseObjectGroupReturns;
}

/// Parameters of `Runtime.runIfWaitingForDebugger`.
///
/// Tells inspected instance to run if it was waiting for debugger to attach.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RunIfWaitingForDebuggerParams {}

/// The answer to `Runtime.runIfWaitingForDebugger`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RunIfWaitingForDebuggerReturns {}

impl RunIfWaitingForDebuggerParams {
    pub const METHOD: &'static str = "Runtime.runIfWaitingForDebugger";
}

impl super::Command for RunIfWaitingForDebuggerParams {
    const METHOD: &'static str = "Runtime.runIfWaitingForDebugger";
    type Returns = RunIfWaitingForDebuggerReturns;
}

/// Parameters of `Runtime.runScript`.
///
/// Runs script with given id in a given context.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RunScriptParams {
    /// Id of the script to run.
    #[serde(rename = "scriptId")]
    pub script_id: ScriptId,
    /// Specifies in which execution context to perform script run. If the parameter is omitted the
    /// evaluation will be performed in the context of the inspected page.
    #[serde(
        rename = "executionContextId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub execution_context_id: Option<ExecutionContextId>,
    /// Symbolic group name that can be used to release multiple objects.
    #[serde(
        rename = "objectGroup",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub object_group: Option<String>,
    /// In silent mode exceptions thrown during evaluation are not reported and do not pause
    /// execution. Overrides `setPauseOnException` state.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub silent: Option<bool>,
    /// Determines whether Command Line API should be available during the evaluation.
    #[serde(
        rename = "includeCommandLineAPI",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub include_command_line_api: Option<bool>,
    /// Whether the result is expected to be a JSON object which should be sent by value.
    #[serde(
        rename = "returnByValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub return_by_value: Option<bool>,
    /// Whether preview should be generated for the result.
    #[serde(
        rename = "generatePreview",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub generate_preview: Option<bool>,
    /// Whether execution should `await` for resulting value and return once awaited promise is
    /// resolved.
    #[serde(
        rename = "awaitPromise",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub await_promise: Option<bool>,
}

/// The answer to `Runtime.runScript`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RunScriptReturns {
    /// Run result.
    pub result: RemoteObject,
    /// Exception details.
    #[serde(
        rename = "exceptionDetails",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub exception_details: Option<ExceptionDetails>,
}

impl RunScriptParams {
    pub const METHOD: &'static str = "Runtime.runScript";
}

impl super::Command for RunScriptParams {
    const METHOD: &'static str = "Runtime.runScript";
    type Returns = RunScriptReturns;
}

/// Parameters of `Runtime.setAsyncCallStackDepth`.
///
/// Enables or disables async call stacks tracking.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetAsyncCallStackDepthParams {
    /// Maximum depth of async call stacks. Setting to `0` will effectively disable collecting async
    /// call stacks (default).
    #[serde(rename = "maxDepth")]
    pub max_depth: i64,
}

/// The answer to `Runtime.setAsyncCallStackDepth`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetAsyncCallStackDepthReturns {}

impl SetAsyncCallStackDepthParams {
    pub const METHOD: &'static str = "Runtime.setAsyncCallStackDepth";
}

impl super::Command for SetAsyncCallStackDepthParams {
    const METHOD: &'static str = "Runtime.setAsyncCallStackDepth";
    type Returns = SetAsyncCallStackDepthReturns;
}

/// Parameters of `Runtime.setCustomObjectFormatterEnabled`.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetCustomObjectFormatterEnabledParams {
    pub enabled: bool,
}

/// The answer to `Runtime.setCustomObjectFormatterEnabled`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetCustomObjectFormatterEnabledReturns {}

impl SetCustomObjectFormatterEnabledParams {
    pub const METHOD: &'static str = "Runtime.setCustomObjectFormatterEnabled";
}

impl super::Command for SetCustomObjectFormatterEnabledParams {
    const METHOD: &'static str = "Runtime.setCustomObjectFormatterEnabled";
    type Returns = SetCustomObjectFormatterEnabledReturns;
}

/// Parameters of `Runtime.setMaxCallStackSizeToCapture`.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetMaxCallStackSizeToCaptureParams {
    pub size: i64,
}

/// The answer to `Runtime.setMaxCallStackSizeToCapture`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetMaxCallStackSizeToCaptureReturns {}

impl SetMaxCallStackSizeToCaptureParams {
    pub const METHOD: &'static str = "Runtime.setMaxCallStackSizeToCapture";
}

impl super::Command for SetMaxCallStackSizeToCaptureParams {
    const METHOD: &'static str = "Runtime.setMaxCallStackSizeToCapture";
    type Returns = SetMaxCallStackSizeToCaptureReturns;
}

/// Parameters of `Runtime.terminateExecution`.
///
/// Terminate current or next JavaScript execution.
/// Will cancel the termination when the outer-most script execution ends.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct TerminateExecutionParams {}

/// The answer to `Runtime.terminateExecution`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct TerminateExecutionReturns {}

impl TerminateExecutionParams {
    pub const METHOD: &'static str = "Runtime.terminateExecution";
}

impl super::Command for TerminateExecutionParams {
    const METHOD: &'static str = "Runtime.terminateExecution";
    type Returns = TerminateExecutionReturns;
}

/// Parameters of `Runtime.addBinding`.
///
/// If executionContextId is empty, adds binding with the given name on the
/// global objects of all inspected contexts, including those created later,
/// bindings survive reloads.
/// Binding function takes exactly one argument, this argument should be string,
/// in case of any other input, function throws an exception.
/// Each binding function call produces Runtime.bindingCalled notification.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AddBindingParams {
    pub name: String,
    /// If specified, the binding would only be exposed to the specified
    /// execution context. If omitted and `executionContextName` is not set,
    /// the binding is exposed to all execution contexts of the target.
    /// This parameter is mutually exclusive with `executionContextName`.
    /// Deprecated in favor of `executionContextName` due to an unclear use case
    /// and bugs in implementation (crbug.com/1169639). `executionContextId` will be
    /// removed in the future.
    ///
    /// **Experimental.** **Deprecated.**
    #[serde(
        rename = "executionContextId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub execution_context_id: Option<ExecutionContextId>,
    /// If specified, the binding is exposed to the executionContext with
    /// matching name, even for contexts created after the binding is added.
    /// See also `ExecutionContext.name` and `worldName` parameter to
    /// `Page.addScriptToEvaluateOnNewDocument`.
    /// This parameter is mutually exclusive with `executionContextId`.
    #[serde(
        rename = "executionContextName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub execution_context_name: Option<String>,
}

/// The answer to `Runtime.addBinding`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AddBindingReturns {}

impl AddBindingParams {
    pub const METHOD: &'static str = "Runtime.addBinding";
}

impl super::Command for AddBindingParams {
    const METHOD: &'static str = "Runtime.addBinding";
    type Returns = AddBindingReturns;
}

/// Parameters of `Runtime.removeBinding`.
///
/// This method does not remove binding function from global object but
/// unsubscribes current runtime agent from Runtime.bindingCalled notifications.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RemoveBindingParams {
    pub name: String,
}

/// The answer to `Runtime.removeBinding`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RemoveBindingReturns {}

impl RemoveBindingParams {
    pub const METHOD: &'static str = "Runtime.removeBinding";
}

impl super::Command for RemoveBindingParams {
    const METHOD: &'static str = "Runtime.removeBinding";
    type Returns = RemoveBindingReturns;
}

/// Parameters of `Runtime.getExceptionDetails`.
///
/// This method tries to lookup and populate exception details for a
/// JavaScript Error object.
/// Note that the stackTrace portion of the resulting exceptionDetails will
/// only be populated if the Runtime domain was enabled at the time when the
/// Error was thrown.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetExceptionDetailsParams {
    /// The error object for which to resolve the exception details.
    #[serde(rename = "errorObjectId")]
    pub error_object_id: RemoteObjectId,
}

/// The answer to `Runtime.getExceptionDetails`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetExceptionDetailsReturns {
    #[serde(
        rename = "exceptionDetails",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub exception_details: Option<ExceptionDetails>,
}

impl GetExceptionDetailsParams {
    pub const METHOD: &'static str = "Runtime.getExceptionDetails";
}

impl super::Command for GetExceptionDetailsParams {
    const METHOD: &'static str = "Runtime.getExceptionDetails";
    type Returns = GetExceptionDetailsReturns;
}

/// The event `Runtime.bindingCalled`.
///
/// Notification is issued every time when binding is called.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct BindingCalledEvent {
    pub name: String,
    pub payload: String,
    /// Identifier of the context where the call was made.
    #[serde(rename = "executionContextId")]
    pub execution_context_id: ExecutionContextId,
}

impl BindingCalledEvent {
    pub const NAME: &'static str = "Runtime.bindingCalled";
}

impl super::Event for BindingCalledEvent {
    const NAME: &'static str = "Runtime.bindingCalled";
}

/// The event `Runtime.consoleAPICalled`.
///
/// Issued when console API was called.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ConsoleAPICalledEvent {
    /// Type of the call.
    #[serde(rename = "type")]
    pub type_: ConsoleAPICalledType,
    /// Call arguments.
    pub args: Vec<RemoteObject>,
    /// Identifier of the context where the call was made.
    #[serde(rename = "executionContextId")]
    pub execution_context_id: ExecutionContextId,
    /// Call timestamp.
    pub timestamp: Timestamp,
    /// Stack trace captured when the call was made. The async stack chain is automatically reported for
    /// the following call types: `assert`, `error`, `trace`, `warning`. For other types the async call
    /// chain can be retrieved using `Debugger.getStackTrace` and `stackTrace.parentId` field.
    #[serde(
        rename = "stackTrace",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub stack_trace: Option<StackTrace>,
    /// Console context descriptor for calls on non-default console context (not console.*):
    /// 'anonymous#unique-logger-id' for call on unnamed context, 'name#unique-logger-id' for call
    /// on named context.
    ///
    /// **Experimental.**
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub context: Option<String>,
}

/// Values of `ConsoleAPICalled`'s `type`.
///
/// Type of the call.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ConsoleAPICalledType {
    /// `log`
    Log,
    /// `debug`
    Debug,
    /// `info`
    Info,
    /// `error`
    Error,
    /// `warning`
    Warning,
    /// `dir`
    Dir,
    /// `dirxml`
    Dirxml,
    /// `table`
    Table,
    /// `trace`
    Trace,
    /// `clear`
    Clear,
    /// `startGroup`
    StartGroup,
    /// `startGroupCollapsed`
    StartGroupCollapsed,
    /// `endGroup`
    EndGroup,
    /// `assert`
    Assert,
    /// `profile`
    Profile,
    /// `profileEnd`
    ProfileEnd,
    /// `count`
    Count,
    /// `timeEnd`
    TimeEnd,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    ConsoleAPICalledType {
        Log => "log",
        Debug => "debug",
        Info => "info",
        Error => "error",
        Warning => "warning",
        Dir => "dir",
        Dirxml => "dirxml",
        Table => "table",
        Trace => "trace",
        Clear => "clear",
        StartGroup => "startGroup",
        StartGroupCollapsed => "startGroupCollapsed",
        EndGroup => "endGroup",
        Assert => "assert",
        Profile => "profile",
        ProfileEnd => "profileEnd",
        Count => "count",
        TimeEnd => "timeEnd",
    }
}

impl ConsoleAPICalledEvent {
    pub const NAME: &'static str = "Runtime.consoleAPICalled";
}

impl super::Event for ConsoleAPICalledEvent {
    const NAME: &'static str = "Runtime.consoleAPICalled";
}

/// The event `Runtime.exceptionRevoked`.
///
/// Issued when unhandled exception was revoked.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ExceptionRevokedEvent {
    /// Reason describing why exception was revoked.
    pub reason: String,
    /// The id of revoked exception, as reported in `exceptionThrown`.
    #[serde(rename = "exceptionId")]
    pub exception_id: i64,
}

impl ExceptionRevokedEvent {
    pub const NAME: &'static str = "Runtime.exceptionRevoked";
}

impl super::Event for ExceptionRevokedEvent {
    const NAME: &'static str = "Runtime.exceptionRevoked";
}

/// The event `Runtime.exceptionThrown`.
///
/// Issued when exception was thrown and unhandled.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ExceptionThrownEvent {
    /// Timestamp of the exception.
    pub timestamp: Timestamp,
    #[serde(rename = "exceptionDetails")]
    pub exception_details: ExceptionDetails,
}

impl ExceptionThrownEvent {
    pub const NAME: &'static str = "Runtime.exceptionThrown";
}

impl super::Event for ExceptionThrownEvent {
    const NAME: &'static str = "Runtime.exceptionThrown";
}

/// The event `Runtime.executionContextCreated`.
///
/// Issued when new execution context is created.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ExecutionContextCreatedEvent {
    /// A newly created execution context.
    pub context: ExecutionContextDescription,
}

impl ExecutionContextCreatedEvent {
    pub const NAME: &'static str = "Runtime.executionContextCreated";
}

impl super::Event for ExecutionContextCreatedEvent {
    const NAME: &'static str = "Runtime.executionContextCreated";
}

/// The event `Runtime.executionContextDestroyed`.
///
/// Issued when execution context is destroyed.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ExecutionContextDestroyedEvent {
    /// Id of the destroyed context
    ///
    /// **Deprecated.**
    #[serde(rename = "executionContextId")]
    pub execution_context_id: ExecutionContextId,
    /// Unique Id of the destroyed context
    ///
    /// **Experimental.**
    #[serde(rename = "executionContextUniqueId")]
    pub execution_context_unique_id: String,
}

impl ExecutionContextDestroyedEvent {
    pub const NAME: &'static str = "Runtime.executionContextDestroyed";
}

impl super::Event for ExecutionContextDestroyedEvent {
    const NAME: &'static str = "Runtime.executionContextDestroyed";
}

/// The event `Runtime.executionContextsCleared`.
///
/// Issued when all executionContexts were cleared in browser
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ExecutionContextsClearedEvent {}

impl ExecutionContextsClearedEvent {
    pub const NAME: &'static str = "Runtime.executionContextsCleared";
}

impl super::Event for ExecutionContextsClearedEvent {
    const NAME: &'static str = "Runtime.executionContextsCleared";
}

/// The event `Runtime.inspectRequested`.
///
/// Issued when object should be inspected (for example, as a result of inspect() command line API
/// call).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct InspectRequestedEvent {
    pub object: RemoteObject,
    pub hints: serde_json::Map<String, serde_json::Value>,
    /// Identifier of the context where the call was made.
    ///
    /// **Experimental.**
    #[serde(
        rename = "executionContextId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub execution_context_id: Option<ExecutionContextId>,
}

impl InspectRequestedEvent {
    pub const NAME: &'static str = "Runtime.inspectRequested";
}

impl super::Event for InspectRequestedEvent {
    const NAME: &'static str = "Runtime.inspectRequested";
}
