// Generated by eludite-cdp-generator from devtools-protocol 0.0.1709723 (protocol/cdp/PIN). Do not edit:
// change the generator or the pin and run `cargo run -p eludite-cdp-generator`.
//! The CDP domain `Storage`.
//!
//! **Experimental.**

#![allow(
    clippy::upper_case_acronyms,
    clippy::doc_lazy_continuation,
    clippy::doc_overindented_list_items,
    clippy::large_enum_variant,
    clippy::empty_docs,
    clippy::struct_excessive_bools,
    rustdoc::bare_urls,
    rustdoc::broken_intra_doc_links,
    rustdoc::invalid_html_tags,
    rustdoc::invalid_rust_codeblocks
)]

use serde::{Deserialize, Serialize};

pub type SerializedStorageKey = String;

/// Enum of possible storage types.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum StorageType {
    /// `cookies`
    Cookies,
    /// `file_systems`
    FileSystems,
    /// `indexeddb`
    Indexeddb,
    /// `local_storage`
    LocalStorage,
    /// `shader_cache`
    ShaderCache,
    /// `websql`
    Websql,
    /// `service_workers`
    ServiceWorkers,
    /// `cache_storage`
    CacheStorage,
    /// `storage_buckets`
    StorageBuckets,
    /// `all`
    All,
    /// `other`
    OtherValue,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    StorageType {
        Cookies => "cookies",
        FileSystems => "file_systems",
        Indexeddb => "indexeddb",
        LocalStorage => "local_storage",
        ShaderCache => "shader_cache",
        Websql => "websql",
        ServiceWorkers => "service_workers",
        CacheStorage => "cache_storage",
        StorageBuckets => "storage_buckets",
        All => "all",
        OtherValue => "other",
    }
}

/// Usage for a storage type.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct UsageForType {
    /// Name of storage type.
    #[serde(rename = "storageType")]
    pub storage_type: StorageType,
    /// Storage usage (bytes).
    pub usage: f64,
}

/// Pair of issuer origin and number of available (signed, but not used) Trust
/// Tokens from that issuer.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct TrustTokens {
    #[serde(rename = "issuerOrigin")]
    pub issuer_origin: String,
    pub count: f64,
}

/// Details of a stored Private Verification Token.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct PrivateVerificationToken {
    /// Unique identifier of the token in the database.
    pub id: String,
    /// Origin of the token issuer.
    #[serde(rename = "issuerOrigin")]
    pub issuer_origin: String,
    /// Public key ID used to issue the token.
    #[serde(rename = "keyId")]
    pub key_id: i64,
    /// Expiration timestamp in seconds since the epoch.
    pub expiration: super::network::TimeSinceEpoch,
    /// Token creation timestamp in seconds since the epoch.
    #[serde(rename = "creationTime")]
    pub creation_time: super::network::TimeSinceEpoch,
    /// Token protocol version.
    pub version: i64,
    /// Base64-encoded serialized token.
    pub token: String,
}

/// Configuration for a Private Verification Tokens issuer.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct PrivateVerificationTokensIssuerConfig {
    /// Origin of the token issuer.
    #[serde(rename = "issuerOrigin")]
    pub issuer_origin: String,
    /// Origins authorized to redeem tokens from this issuer.
    #[serde(rename = "redeemerOrigins")]
    pub redeemer_origins: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum StorageBucketsDurability {
    /// `relaxed`
    Relaxed,
    /// `strict`
    Strict,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    StorageBucketsDurability {
        Relaxed => "relaxed",
        Strict => "strict",
    }
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct StorageBucket {
    #[serde(rename = "storageKey")]
    pub storage_key: SerializedStorageKey,
    /// If not specified, it is the default bucket of the storageKey.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StorageBucketInfo {
    pub bucket: StorageBucket,
    pub id: String,
    pub expiration: super::network::TimeSinceEpoch,
    /// Storage quota (bytes).
    pub quota: f64,
    pub persistent: bool,
    pub durability: StorageBucketsDurability,
}

/// Parameters of `Storage.getStorageKeyForFrame`.
///
/// Returns a storage key given a frame id.
/// Deprecated. Please use Storage.getStorageKey instead.
///
/// **Deprecated.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetStorageKeyForFrameParams {
    #[serde(rename = "frameId")]
    pub frame_id: super::page::FrameId,
}

/// The answer to `Storage.getStorageKeyForFrame`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetStorageKeyForFrameReturns {
    #[serde(rename = "storageKey")]
    pub storage_key: SerializedStorageKey,
}

impl GetStorageKeyForFrameParams {
    pub const METHOD: &'static str = "Storage.getStorageKeyForFrame";
}

impl super::Command for GetStorageKeyForFrameParams {
    const METHOD: &'static str = "Storage.getStorageKeyForFrame";
    type Returns = GetStorageKeyForFrameReturns;
}

/// Parameters of `Storage.getStorageKey`.
///
/// Returns storage key for the given frame. If no frame ID is provided,
/// the storage key of the target executing this command is returned.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetStorageKeyParams {
    #[serde(rename = "frameId", default, skip_serializing_if = "Option::is_none")]
    pub frame_id: Option<super::page::FrameId>,
}

/// The answer to `Storage.getStorageKey`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetStorageKeyReturns {
    #[serde(rename = "storageKey")]
    pub storage_key: SerializedStorageKey,
}

impl GetStorageKeyParams {
    pub const METHOD: &'static str = "Storage.getStorageKey";
}

impl super::Command for GetStorageKeyParams {
    const METHOD: &'static str = "Storage.getStorageKey";
    type Returns = GetStorageKeyReturns;
}

/// Parameters of `Storage.clearDataForOrigin`.
///
/// Clears storage for origin.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearDataForOriginParams {
    /// Security origin.
    pub origin: String,
    /// Comma separated list of StorageType to clear.
    #[serde(rename = "storageTypes")]
    pub storage_types: String,
}

/// The answer to `Storage.clearDataForOrigin`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearDataForOriginReturns {}

impl ClearDataForOriginParams {
    pub const METHOD: &'static str = "Storage.clearDataForOrigin";
}

impl super::Command for ClearDataForOriginParams {
    const METHOD: &'static str = "Storage.clearDataForOrigin";
    type Returns = ClearDataForOriginReturns;
}

/// Parameters of `Storage.clearDataForStorageKey`.
///
/// Clears storage for storage key.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearDataForStorageKeyParams {
    /// Storage key.
    #[serde(rename = "storageKey")]
    pub storage_key: String,
    /// Comma separated list of StorageType to clear.
    #[serde(rename = "storageTypes")]
    pub storage_types: String,
}

/// The answer to `Storage.clearDataForStorageKey`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearDataForStorageKeyReturns {}

impl ClearDataForStorageKeyParams {
    pub const METHOD: &'static str = "Storage.clearDataForStorageKey";
}

impl super::Command for ClearDataForStorageKeyParams {
    const METHOD: &'static str = "Storage.clearDataForStorageKey";
    type Returns = ClearDataForStorageKeyReturns;
}

/// Parameters of `Storage.getCookies`.
///
/// Returns all browser cookies.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetCookiesParams {
    /// Browser context to use when called on the browser endpoint.
    #[serde(
        rename = "browserContextId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub browser_context_id: Option<super::browser::BrowserContextID>,
}

/// The answer to `Storage.getCookies`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetCookiesReturns {
    /// Array of cookie objects.
    pub cookies: Vec<super::network::Cookie>,
}

impl GetCookiesParams {
    pub const METHOD: &'static str = "Storage.getCookies";
}

impl super::Command for GetCookiesParams {
    const METHOD: &'static str = "Storage.getCookies";
    type Returns = GetCookiesReturns;
}

/// Parameters of `Storage.setCookies`.
///
/// Sets given cookies.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetCookiesParams {
    /// Cookies to be set.
    pub cookies: Vec<super::network::CookieParam>,
    /// Browser context to use when called on the browser endpoint.
    #[serde(
        rename = "browserContextId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub browser_context_id: Option<super::browser::BrowserContextID>,
}

/// The answer to `Storage.setCookies`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetCookiesReturns {}

impl SetCookiesParams {
    pub const METHOD: &'static str = "Storage.setCookies";
}

impl super::Command for SetCookiesParams {
    const METHOD: &'static str = "Storage.setCookies";
    type Returns = SetCookiesReturns;
}

/// Parameters of `Storage.clearCookies`.
///
/// Clears cookies.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearCookiesParams {
    /// Browser context to use when called on the browser endpoint.
    #[serde(
        rename = "browserContextId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub browser_context_id: Option<super::browser::BrowserContextID>,
}

/// The answer to `Storage.clearCookies`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearCookiesReturns {}

impl ClearCookiesParams {
    pub const METHOD: &'static str = "Storage.clearCookies";
}

impl super::Command for ClearCookiesParams {
    const METHOD: &'static str = "Storage.clearCookies";
    type Returns = ClearCookiesReturns;
}

/// Parameters of `Storage.getUsageAndQuota`.
///
/// Returns usage and quota in bytes.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetUsageAndQuotaParams {
    /// Security origin.
    pub origin: String,
}

/// The answer to `Storage.getUsageAndQuota`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetUsageAndQuotaReturns {
    /// Storage usage (bytes).
    pub usage: f64,
    /// Storage quota (bytes).
    pub quota: f64,
    /// Whether or not the origin has an active storage quota override
    #[serde(rename = "overrideActive")]
    pub override_active: bool,
    /// Storage usage per type (bytes).
    #[serde(rename = "usageBreakdown")]
    pub usage_breakdown: Vec<UsageForType>,
}

impl GetUsageAndQuotaParams {
    pub const METHOD: &'static str = "Storage.getUsageAndQuota";
}

impl super::Command for GetUsageAndQuotaParams {
    const METHOD: &'static str = "Storage.getUsageAndQuota";
    type Returns = GetUsageAndQuotaReturns;
}

/// Parameters of `Storage.overrideQuotaForOrigin`.
///
/// Override quota for the specified origin
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct OverrideQuotaForOriginParams {
    /// Security origin.
    pub origin: String,
    /// The quota size (in bytes) to override the original quota with.
    /// If this is called multiple times, the overridden quota will be equal to
    /// the quotaSize provided in the final call. If this is called without
    /// specifying a quotaSize, the quota will be reset to the default value for
    /// the specified origin. If this is called multiple times with different
    /// origins, the override will be maintained for each origin until it is
    /// disabled (called without a quotaSize).
    #[serde(rename = "quotaSize", default, skip_serializing_if = "Option::is_none")]
    pub quota_size: Option<f64>,
}

/// The answer to `Storage.overrideQuotaForOrigin`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct OverrideQuotaForOriginReturns {}

impl OverrideQuotaForOriginParams {
    pub const METHOD: &'static str = "Storage.overrideQuotaForOrigin";
}

impl super::Command for OverrideQuotaForOriginParams {
    const METHOD: &'static str = "Storage.overrideQuotaForOrigin";
    type Returns = OverrideQuotaForOriginReturns;
}

/// Parameters of `Storage.trackCacheStorageForOrigin`.
///
/// Registers origin to be notified when an update occurs to its cache storage list.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct TrackCacheStorageForOriginParams {
    /// Security origin.
    pub origin: String,
}

/// The answer to `Storage.trackCacheStorageForOrigin`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct TrackCacheStorageForOriginReturns {}

impl TrackCacheStorageForOriginParams {
    pub const METHOD: &'static str = "Storage.trackCacheStorageForOrigin";
}

impl super::Command for TrackCacheStorageForOriginParams {
    const METHOD: &'static str = "Storage.trackCacheStorageForOrigin";
    type Returns = TrackCacheStorageForOriginReturns;
}

/// Parameters of `Storage.trackCacheStorageForStorageKey`.
///
/// Registers storage key to be notified when an update occurs to its cache storage list.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct TrackCacheStorageForStorageKeyParams {
    /// Storage key.
    #[serde(rename = "storageKey")]
    pub storage_key: String,
}

/// The answer to `Storage.trackCacheStorageForStorageKey`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct TrackCacheStorageForStorageKeyReturns {}

impl TrackCacheStorageForStorageKeyParams {
    pub const METHOD: &'static str = "Storage.trackCacheStorageForStorageKey";
}

impl super::Command for TrackCacheStorageForStorageKeyParams {
    const METHOD: &'static str = "Storage.trackCacheStorageForStorageKey";
    type Returns = TrackCacheStorageForStorageKeyReturns;
}

/// Parameters of `Storage.trackIndexedDBForOrigin`.
///
/// Registers origin to be notified when an update occurs to its IndexedDB.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct TrackIndexedDBForOriginParams {
    /// Security origin.
    pub origin: String,
}

/// The answer to `Storage.trackIndexedDBForOrigin`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct TrackIndexedDBForOriginReturns {}

impl TrackIndexedDBForOriginParams {
    pub const METHOD: &'static str = "Storage.trackIndexedDBForOrigin";
}

impl super::Command for TrackIndexedDBForOriginParams {
    const METHOD: &'static str = "Storage.trackIndexedDBForOrigin";
    type Returns = TrackIndexedDBForOriginReturns;
}

/// Parameters of `Storage.trackIndexedDBForStorageKey`.
///
/// Registers storage key to be notified when an update occurs to its IndexedDB.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct TrackIndexedDBForStorageKeyParams {
    /// Storage key.
    #[serde(rename = "storageKey")]
    pub storage_key: String,
}

/// The answer to `Storage.trackIndexedDBForStorageKey`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct TrackIndexedDBForStorageKeyReturns {}

impl TrackIndexedDBForStorageKeyParams {
    pub const METHOD: &'static str = "Storage.trackIndexedDBForStorageKey";
}

impl super::Command for TrackIndexedDBForStorageKeyParams {
    const METHOD: &'static str = "Storage.trackIndexedDBForStorageKey";
    type Returns = TrackIndexedDBForStorageKeyReturns;
}

/// Parameters of `Storage.untrackCacheStorageForOrigin`.
///
/// Unregisters origin from receiving notifications for cache storage.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct UntrackCacheStorageForOriginParams {
    /// Security origin.
    pub origin: String,
}

/// The answer to `Storage.untrackCacheStorageForOrigin`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct UntrackCacheStorageForOriginReturns {}

impl UntrackCacheStorageForOriginParams {
    pub const METHOD: &'static str = "Storage.untrackCacheStorageForOrigin";
}

impl super::Command for UntrackCacheStorageForOriginParams {
    const METHOD: &'static str = "Storage.untrackCacheStorageForOrigin";
    type Returns = UntrackCacheStorageForOriginReturns;
}

/// Parameters of `Storage.untrackCacheStorageForStorageKey`.
///
/// Unregisters storage key from receiving notifications for cache storage.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct UntrackCacheStorageForStorageKeyParams {
    /// Storage key.
    #[serde(rename = "storageKey")]
    pub storage_key: String,
}

/// The answer to `Storage.untrackCacheStorageForStorageKey`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct UntrackCacheStorageForStorageKeyReturns {}

impl UntrackCacheStorageForStorageKeyParams {
    pub const METHOD: &'static str = "Storage.untrackCacheStorageForStorageKey";
}

impl super::Command for UntrackCacheStorageForStorageKeyParams {
    const METHOD: &'static str = "Storage.untrackCacheStorageForStorageKey";
    type Returns = UntrackCacheStorageForStorageKeyReturns;
}

/// Parameters of `Storage.untrackIndexedDBForOrigin`.
///
/// Unregisters origin from receiving notifications for IndexedDB.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct UntrackIndexedDBForOriginParams {
    /// Security origin.
    pub origin: String,
}

/// The answer to `Storage.untrackIndexedDBForOrigin`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct UntrackIndexedDBForOriginReturns {}

impl UntrackIndexedDBForOriginParams {
    pub const METHOD: &'static str = "Storage.untrackIndexedDBForOrigin";
}

impl super::Command for UntrackIndexedDBForOriginParams {
    const METHOD: &'static str = "Storage.untrackIndexedDBForOrigin";
    type Returns = UntrackIndexedDBForOriginReturns;
}

/// Parameters of `Storage.untrackIndexedDBForStorageKey`.
///
/// Unregisters storage key from receiving notifications for IndexedDB.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct UntrackIndexedDBForStorageKeyParams {
    /// Storage key.
    #[serde(rename = "storageKey")]
    pub storage_key: String,
}

/// The answer to `Storage.untrackIndexedDBForStorageKey`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct UntrackIndexedDBForStorageKeyReturns {}

impl UntrackIndexedDBForStorageKeyParams {
    pub const METHOD: &'static str = "Storage.untrackIndexedDBForStorageKey";
}

impl super::Command for UntrackIndexedDBForStorageKeyParams {
    const METHOD: &'static str = "Storage.untrackIndexedDBForStorageKey";
    type Returns = UntrackIndexedDBForStorageKeyReturns;
}

/// Parameters of `Storage.getTrustTokens`.
///
/// Returns the number of stored Trust Tokens per issuer for the
/// current browsing context.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetTrustTokensParams {}

/// The answer to `Storage.getTrustTokens`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetTrustTokensReturns {
    pub tokens: Vec<TrustTokens>,
}

impl GetTrustTokensParams {
    pub const METHOD: &'static str = "Storage.getTrustTokens";
}

impl super::Command for GetTrustTokensParams {
    const METHOD: &'static str = "Storage.getTrustTokens";
    type Returns = GetTrustTokensReturns;
}

/// Parameters of `Storage.clearTrustTokens`.
///
/// Removes all Trust Tokens issued by the provided issuerOrigin.
/// Leaves other stored data, including the issuer's Redemption Records, intact.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearTrustTokensParams {
    #[serde(rename = "issuerOrigin")]
    pub issuer_origin: String,
}

/// The answer to `Storage.clearTrustTokens`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearTrustTokensReturns {
    /// True if any tokens were deleted, false otherwise.
    #[serde(rename = "didDeleteTokens")]
    pub did_delete_tokens: bool,
}

impl ClearTrustTokensParams {
    pub const METHOD: &'static str = "Storage.clearTrustTokens";
}

impl super::Command for ClearTrustTokensParams {
    const METHOD: &'static str = "Storage.clearTrustTokens";
    type Returns = ClearTrustTokensReturns;
}

/// Parameters of `Storage.getPrivateVerificationTokens`.
///
/// Returns all stored Private Verification Tokens for the current browsing
/// context.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetPrivateVerificationTokensParams {}

/// The answer to `Storage.getPrivateVerificationTokens`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetPrivateVerificationTokensReturns {
    pub tokens: Vec<PrivateVerificationToken>,
}

impl GetPrivateVerificationTokensParams {
    pub const METHOD: &'static str = "Storage.getPrivateVerificationTokens";
}

impl super::Command for GetPrivateVerificationTokensParams {
    const METHOD: &'static str = "Storage.getPrivateVerificationTokens";
    type Returns = GetPrivateVerificationTokensReturns;
}

/// Parameters of `Storage.getPrivateVerificationTokensIssuerConfigs`.
///
/// Returns the configured Private Verification Tokens issuers and their redeemer
/// origins.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetPrivateVerificationTokensIssuerConfigsParams {}

/// The answer to `Storage.getPrivateVerificationTokensIssuerConfigs`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetPrivateVerificationTokensIssuerConfigsReturns {
    pub configs: Vec<PrivateVerificationTokensIssuerConfig>,
}

impl GetPrivateVerificationTokensIssuerConfigsParams {
    pub const METHOD: &'static str = "Storage.getPrivateVerificationTokensIssuerConfigs";
}

impl super::Command for GetPrivateVerificationTokensIssuerConfigsParams {
    const METHOD: &'static str = "Storage.getPrivateVerificationTokensIssuerConfigs";
    type Returns = GetPrivateVerificationTokensIssuerConfigsReturns;
}

/// Parameters of `Storage.clearPrivateVerificationTokens`.
///
/// Removes all Private Verification Tokens issued by the provided issuerOrigin.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearPrivateVerificationTokensParams {
    #[serde(rename = "issuerOrigin")]
    pub issuer_origin: String,
}

/// The answer to `Storage.clearPrivateVerificationTokens`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ClearPrivateVerificationTokensReturns {}

impl ClearPrivateVerificationTokensParams {
    pub const METHOD: &'static str = "Storage.clearPrivateVerificationTokens";
}

impl super::Command for ClearPrivateVerificationTokensParams {
    const METHOD: &'static str = "Storage.clearPrivateVerificationTokens";
    type Returns = ClearPrivateVerificationTokensReturns;
}

/// Parameters of `Storage.deletePrivateVerificationToken`.
///
/// Removes a specific Private Verification Token by its ID.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DeletePrivateVerificationTokenParams {
    #[serde(rename = "tokenId")]
    pub token_id: String,
}

/// The answer to `Storage.deletePrivateVerificationToken`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DeletePrivateVerificationTokenReturns {}

impl DeletePrivateVerificationTokenParams {
    pub const METHOD: &'static str = "Storage.deletePrivateVerificationToken";
}

impl super::Command for DeletePrivateVerificationTokenParams {
    const METHOD: &'static str = "Storage.deletePrivateVerificationToken";
    type Returns = DeletePrivateVerificationTokenReturns;
}

/// Parameters of `Storage.setPrivateVerificationTokensTracking`.
///
/// Set tracking for Private Verification Tokens.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetPrivateVerificationTokensTrackingParams {
    pub enable: bool,
}

/// The answer to `Storage.setPrivateVerificationTokensTracking`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetPrivateVerificationTokensTrackingReturns {}

impl SetPrivateVerificationTokensTrackingParams {
    pub const METHOD: &'static str = "Storage.setPrivateVerificationTokensTracking";
}

impl super::Command for SetPrivateVerificationTokensTrackingParams {
    const METHOD: &'static str = "Storage.setPrivateVerificationTokensTracking";
    type Returns = SetPrivateVerificationTokensTrackingReturns;
}

/// Parameters of `Storage.setStorageBucketTracking`.
///
/// Set tracking for a storage key's buckets.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetStorageBucketTrackingParams {
    #[serde(rename = "storageKey")]
    pub storage_key: String,
    pub enable: bool,
}

/// The answer to `Storage.setStorageBucketTracking`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetStorageBucketTrackingReturns {}

impl SetStorageBucketTrackingParams {
    pub const METHOD: &'static str = "Storage.setStorageBucketTracking";
}

impl super::Command for SetStorageBucketTrackingParams {
    const METHOD: &'static str = "Storage.setStorageBucketTracking";
    type Returns = SetStorageBucketTrackingReturns;
}

/// Parameters of `Storage.deleteStorageBucket`.
///
/// Deletes the Storage Bucket with the given storage key and bucket name.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DeleteStorageBucketParams {
    pub bucket: StorageBucket,
}

/// The answer to `Storage.deleteStorageBucket`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DeleteStorageBucketReturns {}

impl DeleteStorageBucketParams {
    pub const METHOD: &'static str = "Storage.deleteStorageBucket";
}

impl super::Command for DeleteStorageBucketParams {
    const METHOD: &'static str = "Storage.deleteStorageBucket";
    type Returns = DeleteStorageBucketReturns;
}

/// Parameters of `Storage.runBounceTrackingMitigations`.
///
/// Deletes state for sites identified as potential bounce trackers, immediately.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RunBounceTrackingMitigationsParams {}

/// The answer to `Storage.runBounceTrackingMitigations`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RunBounceTrackingMitigationsReturns {
    #[serde(rename = "deletedSites")]
    pub deleted_sites: Vec<String>,
}

impl RunBounceTrackingMitigationsParams {
    pub const METHOD: &'static str = "Storage.runBounceTrackingMitigations";
}

impl super::Command for RunBounceTrackingMitigationsParams {
    const METHOD: &'static str = "Storage.runBounceTrackingMitigations";
    type Returns = RunBounceTrackingMitigationsReturns;
}

/// The event `Storage.cacheStorageContentUpdated`.
///
/// A cache's contents have been modified.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CacheStorageContentUpdatedEvent {
    /// Origin to update.
    pub origin: String,
    /// Storage key to update.
    #[serde(rename = "storageKey")]
    pub storage_key: String,
    /// Storage bucket to update.
    #[serde(rename = "bucketId")]
    pub bucket_id: String,
    /// Name of cache in origin.
    #[serde(rename = "cacheName")]
    pub cache_name: String,
}

impl CacheStorageContentUpdatedEvent {
    pub const NAME: &'static str = "Storage.cacheStorageContentUpdated";
}

impl super::Event for CacheStorageContentUpdatedEvent {
    const NAME: &'static str = "Storage.cacheStorageContentUpdated";
}

/// The event `Storage.cacheStorageListUpdated`.
///
/// A cache has been added/deleted.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CacheStorageListUpdatedEvent {
    /// Origin to update.
    pub origin: String,
    /// Storage key to update.
    #[serde(rename = "storageKey")]
    pub storage_key: String,
    /// Storage bucket to update.
    #[serde(rename = "bucketId")]
    pub bucket_id: String,
}

impl CacheStorageListUpdatedEvent {
    pub const NAME: &'static str = "Storage.cacheStorageListUpdated";
}

impl super::Event for CacheStorageListUpdatedEvent {
    const NAME: &'static str = "Storage.cacheStorageListUpdated";
}

/// The event `Storage.indexedDBContentUpdated`.
///
/// The origin's IndexedDB object store has been modified.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct IndexedDBContentUpdatedEvent {
    /// Origin to update.
    pub origin: String,
    /// Storage key to update.
    #[serde(rename = "storageKey")]
    pub storage_key: String,
    /// Storage bucket to update.
    #[serde(rename = "bucketId")]
    pub bucket_id: String,
    /// Database to update.
    #[serde(rename = "databaseName")]
    pub database_name: String,
    /// ObjectStore to update.
    #[serde(rename = "objectStoreName")]
    pub object_store_name: String,
}

impl IndexedDBContentUpdatedEvent {
    pub const NAME: &'static str = "Storage.indexedDBContentUpdated";
}

impl super::Event for IndexedDBContentUpdatedEvent {
    const NAME: &'static str = "Storage.indexedDBContentUpdated";
}

/// The event `Storage.indexedDBListUpdated`.
///
/// The origin's IndexedDB database list has been modified.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct IndexedDBListUpdatedEvent {
    /// Origin to update.
    pub origin: String,
    /// Storage key to update.
    #[serde(rename = "storageKey")]
    pub storage_key: String,
    /// Storage bucket to update.
    #[serde(rename = "bucketId")]
    pub bucket_id: String,
}

impl IndexedDBListUpdatedEvent {
    pub const NAME: &'static str = "Storage.indexedDBListUpdated";
}

impl super::Event for IndexedDBListUpdatedEvent {
    const NAME: &'static str = "Storage.indexedDBListUpdated";
}

/// The event `Storage.storageBucketCreatedOrUpdated`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StorageBucketCreatedOrUpdatedEvent {
    #[serde(rename = "bucketInfo")]
    pub bucket_info: StorageBucketInfo,
}

impl StorageBucketCreatedOrUpdatedEvent {
    pub const NAME: &'static str = "Storage.storageBucketCreatedOrUpdated";
}

impl super::Event for StorageBucketCreatedOrUpdatedEvent {
    const NAME: &'static str = "Storage.storageBucketCreatedOrUpdated";
}

/// The event `Storage.storageBucketDeleted`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct StorageBucketDeletedEvent {
    #[serde(rename = "bucketId")]
    pub bucket_id: String,
}

impl StorageBucketDeletedEvent {
    pub const NAME: &'static str = "Storage.storageBucketDeleted";
}

impl super::Event for StorageBucketDeletedEvent {
    const NAME: &'static str = "Storage.storageBucketDeleted";
}

/// The event `Storage.privateVerificationTokensUpdated`.
///
/// Private Verification Tokens have been stored or deleted.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct PrivateVerificationTokensUpdatedEvent {}

impl PrivateVerificationTokensUpdatedEvent {
    pub const NAME: &'static str = "Storage.privateVerificationTokensUpdated";
}

impl super::Event for PrivateVerificationTokensUpdatedEvent {
    const NAME: &'static str = "Storage.privateVerificationTokensUpdated";
}
