// Generated by eludite-cdp-generator from devtools-protocol 0.0.1709723 (protocol/cdp/PIN). Do not edit:
// change the generator or the pin and run `cargo run -p eludite-cdp-generator`.
//! The CDP domain `Target`.
//!
//! Supports additional targets discovery and allows to attach to them.

#![allow(
    clippy::upper_case_acronyms,
    clippy::doc_lazy_continuation,
    clippy::doc_overindented_list_items,
    clippy::large_enum_variant,
    clippy::empty_docs,
    clippy::struct_excessive_bools,
    rustdoc::bare_urls,
    rustdoc::broken_intra_doc_links,
    rustdoc::invalid_html_tags,
    rustdoc::invalid_rust_codeblocks
)]

use serde::{Deserialize, Serialize};

pub type TargetID = String;

/// Unique identifier of attached debugging session.
pub type SessionID = String;

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct TargetInfo {
    #[serde(rename = "targetId")]
    pub target_id: TargetID,
    /// List of types: https://source.chromium.org/chromium/chromium/src/+/main:content/browser/devtools/devtools_agent_host_impl.cc?ss=chromium&q=f:devtools%20-f:out%20%22::kTypeTab%5B%5D%22
    #[serde(rename = "type")]
    pub type_: String,
    pub title: String,
    pub url: String,
    /// Whether the target has an attached client.
    pub attached: bool,
    /// Id of the parent target, if any. For example, "iframe" target may have a "page" parent.
    #[serde(rename = "parentId", default, skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<TargetID>,
    /// Opener target Id
    #[serde(rename = "openerId", default, skip_serializing_if = "Option::is_none")]
    pub opener_id: Option<TargetID>,
    /// Whether the target has access to the originating window.
    ///
    /// **Experimental.**
    #[serde(rename = "canAccessOpener")]
    pub can_access_opener: bool,
    /// Frame id of originating window (is only set if target has an opener).
    ///
    /// **Experimental.**
    #[serde(
        rename = "openerFrameId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub opener_frame_id: Option<super::page::FrameId>,
    /// Id of the parent frame, present for "iframe" and "worker" targets. For nested workers,
    /// this is the "ancestor" frame that created the first worker in the nested chain.
    ///
    /// **Experimental.**
    #[serde(
        rename = "parentFrameId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub parent_frame_id: Option<super::page::FrameId>,
    /// **Experimental.**
    #[serde(
        rename = "browserContextId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub browser_context_id: Option<super::browser::BrowserContextID>,
    /// Provides additional details for specific target types. For example, for
    /// the type of "page", this may be set to "prerender".
    ///
    /// **Experimental.**
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subtype: Option<String>,
    /// Embedder-specific target metadata. This is only set for targets of
    /// type "tab".
    ///
    /// **Experimental.**
    #[serde(
        rename = "embedderData",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub embedder_data: Option<serde_json::Map<String, serde_json::Value>>,
}

/// A filter used by target query/discovery/auto-attach operations.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct FilterEntry {
    /// If set, causes exclusion of matching targets from the list.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exclude: Option<bool>,
    /// If not present, matches any type.
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub type_: Option<String>,
}

/// The entries in TargetFilter are matched sequentially against targets and
/// the first entry that matches determines if the target is included or not,
/// depending on the value of `exclude` field in the entry.
/// If filter is not specified, the one assumed is
/// [{type: "browser", exclude: true}, {type: "tab", exclude: true}, {}]
/// (i.e. include everything but `browser` and `tab`).
///
/// **Experimental.**
pub type TargetFilter = Vec<FilterEntry>;

/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RemoteLocation {
    pub host: String,
    pub port: i64,
}

/// The state of the target window.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum WindowState {
    /// `normal`
    Normal,
    /// `minimized`
    Minimized,
    /// `maximized`
    Maximized,
    /// `fullscreen`
    Fullscreen,
    /// A value this version of the protocol does not list.
    Other(String),
}

string_enum! {
    WindowState {
        Normal => "normal",
        Minimized => "minimized",
        Maximized => "maximized",
        Fullscreen => "fullscreen",
    }
}

/// Parameters of `Target.activateTarget`.
///
/// Activates (focuses) the target.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ActivateTargetParams {
    #[serde(rename = "targetId")]
    pub target_id: TargetID,
}

/// The answer to `Target.activateTarget`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ActivateTargetReturns {}

impl ActivateTargetParams {
    pub const METHOD: &'static str = "Target.activateTarget";
}

impl super::Command for ActivateTargetParams {
    const METHOD: &'static str = "Target.activateTarget";
    type Returns = ActivateTargetReturns;
}

/// Parameters of `Target.attachToTarget`.
///
/// Attaches to the target with given id.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AttachToTargetParams {
    #[serde(rename = "targetId")]
    pub target_id: TargetID,
    /// Enables "flat" access to the session via specifying sessionId attribute in the commands.
    /// We plan to make this the default, deprecate non-flattened mode,
    /// and eventually retire it. See crbug.com/991325.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub flatten: Option<bool>,
}

/// The answer to `Target.attachToTarget`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AttachToTargetReturns {
    /// Id assigned to the session.
    #[serde(rename = "sessionId")]
    pub session_id: SessionID,
}

impl AttachToTargetParams {
    pub const METHOD: &'static str = "Target.attachToTarget";
}

impl super::Command for AttachToTargetParams {
    const METHOD: &'static str = "Target.attachToTarget";
    type Returns = AttachToTargetReturns;
}

/// Parameters of `Target.attachToBrowserTarget`.
///
/// Attaches to the browser target, only uses flat sessionId mode.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AttachToBrowserTargetParams {}

/// The answer to `Target.attachToBrowserTarget`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AttachToBrowserTargetReturns {
    /// Id assigned to the session.
    #[serde(rename = "sessionId")]
    pub session_id: SessionID,
}

impl AttachToBrowserTargetParams {
    pub const METHOD: &'static str = "Target.attachToBrowserTarget";
}

impl super::Command for AttachToBrowserTargetParams {
    const METHOD: &'static str = "Target.attachToBrowserTarget";
    type Returns = AttachToBrowserTargetReturns;
}

/// Parameters of `Target.closeTarget`.
///
/// Closes the target. If the target is a page that gets closed too.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CloseTargetParams {
    #[serde(rename = "targetId")]
    pub target_id: TargetID,
}

/// The answer to `Target.closeTarget`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CloseTargetReturns {
    /// Always set to true. If an error occurs, the response indicates protocol error.
    ///
    /// **Deprecated.**
    pub success: bool,
}

impl CloseTargetParams {
    pub const METHOD: &'static str = "Target.closeTarget";
}

impl super::Command for CloseTargetParams {
    const METHOD: &'static str = "Target.closeTarget";
    type Returns = CloseTargetReturns;
}

/// Parameters of `Target.exposeDevToolsProtocol`.
///
/// Inject object to the target's main frame that provides a communication
/// channel with browser target.
///
/// Injected object will be available as `window[bindingName]`.
///
/// The object has the following API:
/// - `binding.send(json)` - a method to send messages over the remote debugging protocol
/// - `binding.onmessage = json => handleMessage(json)` - a callback that will be called for the protocol notifications and command responses.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ExposeDevToolsProtocolParams {
    #[serde(rename = "targetId")]
    pub target_id: TargetID,
    /// Binding name, 'cdp' if not specified.
    #[serde(
        rename = "bindingName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub binding_name: Option<String>,
    /// If true, inherits the current root session's permissions (default: false).
    #[serde(
        rename = "inheritPermissions",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub inherit_permissions: Option<bool>,
}

/// The answer to `Target.exposeDevToolsProtocol`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ExposeDevToolsProtocolReturns {}

impl ExposeDevToolsProtocolParams {
    pub const METHOD: &'static str = "Target.exposeDevToolsProtocol";
}

impl super::Command for ExposeDevToolsProtocolParams {
    const METHOD: &'static str = "Target.exposeDevToolsProtocol";
    type Returns = ExposeDevToolsProtocolReturns;
}

/// Parameters of `Target.createBrowserContext`.
///
/// Creates a new empty BrowserContext. Similar to an incognito profile but you can have more than
/// one.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateBrowserContextParams {
    /// If specified, disposes this context when debugging session disconnects.
    ///
    /// **Experimental.**
    #[serde(
        rename = "disposeOnDetach",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub dispose_on_detach: Option<bool>,
    /// Proxy server, similar to the one passed to --proxy-server
    ///
    /// **Experimental.**
    #[serde(
        rename = "proxyServer",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub proxy_server: Option<String>,
    /// Proxy bypass list, similar to the one passed to --proxy-bypass-list
    ///
    /// **Experimental.**
    #[serde(
        rename = "proxyBypassList",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub proxy_bypass_list: Option<String>,
    /// An optional list of origins to grant unlimited cross-origin access to.
    /// Parts of the URL other than those constituting origin are ignored.
    ///
    /// **Experimental.**
    #[serde(
        rename = "originsWithUniversalNetworkAccess",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub origins_with_universal_network_access: Option<Vec<String>>,
}

/// The answer to `Target.createBrowserContext`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateBrowserContextReturns {
    /// The id of the context created.
    #[serde(rename = "browserContextId")]
    pub browser_context_id: super::browser::BrowserContextID,
}

impl CreateBrowserContextParams {
    pub const METHOD: &'static str = "Target.createBrowserContext";
}

impl super::Command for CreateBrowserContextParams {
    const METHOD: &'static str = "Target.createBrowserContext";
    type Returns = CreateBrowserContextReturns;
}

/// Parameters of `Target.getBrowserContexts`.
///
/// Returns all browser contexts created with `Target.createBrowserContext` method.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetBrowserContextsParams {}

/// The answer to `Target.getBrowserContexts`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetBrowserContextsReturns {
    /// An array of browser context ids.
    #[serde(rename = "browserContextIds")]
    pub browser_context_ids: Vec<super::browser::BrowserContextID>,
    /// The id of the default browser context if available.
    ///
    /// **Experimental.**
    #[serde(
        rename = "defaultBrowserContextId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub default_browser_context_id: Option<super::browser::BrowserContextID>,
}

impl GetBrowserContextsParams {
    pub const METHOD: &'static str = "Target.getBrowserContexts";
}

impl super::Command for GetBrowserContextsParams {
    const METHOD: &'static str = "Target.getBrowserContexts";
    type Returns = GetBrowserContextsReturns;
}

/// Parameters of `Target.createTarget`.
///
/// Creates a new page.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateTargetParams {
    /// The initial URL the page will be navigated to. An empty string indicates about:blank.
    pub url: String,
    /// Frame left origin in DIP (requires newWindow to be true or headless shell).
    ///
    /// **Experimental.**
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub left: Option<i64>,
    /// Frame top origin in DIP (requires newWindow to be true or headless shell).
    ///
    /// **Experimental.**
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub top: Option<i64>,
    /// Frame width in DIP (requires newWindow to be true or headless shell).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub width: Option<i64>,
    /// Frame height in DIP (requires newWindow to be true or headless shell).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub height: Option<i64>,
    /// Frame window state (requires newWindow to be true or headless shell).
    /// Default is normal.
    #[serde(
        rename = "windowState",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub window_state: Option<WindowState>,
    /// The browser context to create the page in.
    ///
    /// **Experimental.**
    #[serde(
        rename = "browserContextId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub browser_context_id: Option<super::browser::BrowserContextID>,
    /// Whether BeginFrames for this target will be controlled via DevTools (headless shell only,
    /// not supported on MacOS yet, false by default).
    ///
    /// **Experimental.**
    #[serde(
        rename = "enableBeginFrameControl",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub enable_begin_frame_control: Option<bool>,
    /// Whether to create a new Window or Tab (false by default, not supported by headless shell).
    #[serde(rename = "newWindow", default, skip_serializing_if = "Option::is_none")]
    pub new_window: Option<bool>,
    /// Whether to create the target in background or foreground (false by default, not supported
    /// by headless shell).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub background: Option<bool>,
    /// Whether to create the target of type "tab".
    ///
    /// **Experimental.**
    #[serde(rename = "forTab", default, skip_serializing_if = "Option::is_none")]
    pub for_tab: Option<bool>,
    /// Whether to create a hidden target. The hidden target is observable via protocol, but not
    /// present in the tab UI strip. Cannot be created with `forTab: true`, `newWindow: true` or
    /// `background: false`. The life-time of the tab is limited to the life-time of the session.
    ///
    /// **Experimental.**
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hidden: Option<bool>,
    /// If specified, determines whether the new target should be focused.
    /// By default, the focus behavior depends on the `background` parameter:
    /// - If `background` is false (default) and `focus` is omitted, the new target is focused and the browser window is brought to the foreground.
    /// - If `background` is false and `focus` is false, the target is opened but the browser window's focus remains unchanged (e.g., if the window was in the background, it stays there).
    /// - If `background` is true, setting `focus` to true is not supported and will result in an error.
    ///
    /// **Experimental.**
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub focus: Option<bool>,
}

/// The answer to `Target.createTarget`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateTargetReturns {
    /// The id of the page opened.
    #[serde(rename = "targetId")]
    pub target_id: TargetID,
}

impl CreateTargetParams {
    pub const METHOD: &'static str = "Target.createTarget";
}

impl super::Command for CreateTargetParams {
    const METHOD: &'static str = "Target.createTarget";
    type Returns = CreateTargetReturns;
}

/// Parameters of `Target.detachFromTarget`.
///
/// Detaches session with given id.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DetachFromTargetParams {
    /// Session to detach.
    #[serde(rename = "sessionId", default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<SessionID>,
    /// Deprecated.
    ///
    /// **Deprecated.**
    #[serde(rename = "targetId", default, skip_serializing_if = "Option::is_none")]
    pub target_id: Option<TargetID>,
}

/// The answer to `Target.detachFromTarget`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DetachFromTargetReturns {}

impl DetachFromTargetParams {
    pub const METHOD: &'static str = "Target.detachFromTarget";
}

impl super::Command for DetachFromTargetParams {
    const METHOD: &'static str = "Target.detachFromTarget";
    type Returns = DetachFromTargetReturns;
}

/// Parameters of `Target.disposeBrowserContext`.
///
/// Deletes a BrowserContext. All the belonging pages will be closed without calling their
/// beforeunload hooks.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DisposeBrowserContextParams {
    #[serde(rename = "browserContextId")]
    pub browser_context_id: super::browser::BrowserContextID,
}

/// The answer to `Target.disposeBrowserContext`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DisposeBrowserContextReturns {}

impl DisposeBrowserContextParams {
    pub const METHOD: &'static str = "Target.disposeBrowserContext";
}

impl super::Command for DisposeBrowserContextParams {
    const METHOD: &'static str = "Target.disposeBrowserContext";
    type Returns = DisposeBrowserContextReturns;
}

/// Parameters of `Target.getTargetInfo`.
///
/// Returns information about a target.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetTargetInfoParams {
    #[serde(rename = "targetId", default, skip_serializing_if = "Option::is_none")]
    pub target_id: Option<TargetID>,
}

/// The answer to `Target.getTargetInfo`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetTargetInfoReturns {
    #[serde(rename = "targetInfo")]
    pub target_info: TargetInfo,
}

impl GetTargetInfoParams {
    pub const METHOD: &'static str = "Target.getTargetInfo";
}

impl super::Command for GetTargetInfoParams {
    const METHOD: &'static str = "Target.getTargetInfo";
    type Returns = GetTargetInfoReturns;
}

/// Parameters of `Target.getTargets`.
///
/// Retrieves a list of available targets.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetTargetsParams {
    /// Only targets matching filter will be reported. If filter is not specified
    /// and target discovery is currently enabled, a filter used for target discovery
    /// is used for consistency.
    ///
    /// **Experimental.**
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filter: Option<TargetFilter>,
}

/// The answer to `Target.getTargets`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetTargetsReturns {
    /// The list of targets.
    #[serde(rename = "targetInfos")]
    pub target_infos: Vec<TargetInfo>,
}

impl GetTargetsParams {
    pub const METHOD: &'static str = "Target.getTargets";
}

impl super::Command for GetTargetsParams {
    const METHOD: &'static str = "Target.getTargets";
    type Returns = GetTargetsReturns;
}

/// Parameters of `Target.sendMessageToTarget`.
///
/// Sends protocol message over session with given id.
/// Consider using flat mode instead; see commands attachToTarget, setAutoAttach,
/// and crbug.com/991325.
///
/// **Deprecated.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SendMessageToTargetParams {
    pub message: String,
    /// Identifier of the session.
    #[serde(rename = "sessionId", default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<SessionID>,
    /// Deprecated.
    ///
    /// **Deprecated.**
    #[serde(rename = "targetId", default, skip_serializing_if = "Option::is_none")]
    pub target_id: Option<TargetID>,
}

/// The answer to `Target.sendMessageToTarget`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SendMessageToTargetReturns {}

impl SendMessageToTargetParams {
    pub const METHOD: &'static str = "Target.sendMessageToTarget";
}

impl super::Command for SendMessageToTargetParams {
    const METHOD: &'static str = "Target.sendMessageToTarget";
    type Returns = SendMessageToTargetReturns;
}

/// Parameters of `Target.setAutoAttach`.
///
/// Controls whether to automatically attach to new targets which are considered
/// to be directly related to this one (for example, iframes or workers).
/// When turned on, attaches to all existing related targets as well. When turned off,
/// automatically detaches from all currently attached targets.
/// This also clears all targets added by `autoAttachRelated` from the list of targets to watch
/// for creation of related targets.
/// You might want to call this recursively for auto-attached targets to attach
/// to all available targets.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetAutoAttachParams {
    /// Whether to auto-attach to related targets.
    #[serde(rename = "autoAttach")]
    pub auto_attach: bool,
    /// Whether to pause new targets when attaching to them. Use `Runtime.runIfWaitingForDebugger`
    /// to run paused targets.
    #[serde(rename = "waitForDebuggerOnStart")]
    pub wait_for_debugger_on_start: bool,
    /// Enables "flat" access to the session via specifying sessionId attribute in the commands.
    /// We plan to make this the default, deprecate non-flattened mode,
    /// and eventually retire it. See crbug.com/991325.
    ///
    /// **Experimental.**
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub flatten: Option<bool>,
    /// Only targets matching filter will be attached.
    ///
    /// **Experimental.**
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filter: Option<TargetFilter>,
}

/// The answer to `Target.setAutoAttach`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetAutoAttachReturns {}

impl SetAutoAttachParams {
    pub const METHOD: &'static str = "Target.setAutoAttach";
}

impl super::Command for SetAutoAttachParams {
    const METHOD: &'static str = "Target.setAutoAttach";
    type Returns = SetAutoAttachReturns;
}

/// Parameters of `Target.autoAttachRelated`.
///
/// Adds the specified target to the list of targets that will be monitored for any related target
/// creation (such as child frames, child workers and new versions of service worker) and reported
/// through `attachedToTarget`. The specified target is also auto-attached.
/// This cancels the effect of any previous `setAutoAttach` and is also cancelled by subsequent
/// `setAutoAttach`. Only available at the Browser target.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AutoAttachRelatedParams {
    #[serde(rename = "targetId")]
    pub target_id: TargetID,
    /// Whether to pause new targets when attaching to them. Use `Runtime.runIfWaitingForDebugger`
    /// to run paused targets.
    #[serde(rename = "waitForDebuggerOnStart")]
    pub wait_for_debugger_on_start: bool,
    /// Only targets matching filter will be attached.
    ///
    /// **Experimental.**
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filter: Option<TargetFilter>,
}

/// The answer to `Target.autoAttachRelated`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AutoAttachRelatedReturns {}

impl AutoAttachRelatedParams {
    pub const METHOD: &'static str = "Target.autoAttachRelated";
}

impl super::Command for AutoAttachRelatedParams {
    const METHOD: &'static str = "Target.autoAttachRelated";
    type Returns = AutoAttachRelatedReturns;
}

/// Parameters of `Target.setDiscoverTargets`.
///
/// Controls whether to discover available targets and notify via
/// `targetCreated/targetInfoChanged/targetDestroyed` events.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetDiscoverTargetsParams {
    /// Whether to discover available targets.
    pub discover: bool,
    /// Only targets matching filter will be attached. If `discover` is false,
    /// `filter` must be omitted or empty.
    ///
    /// **Experimental.**
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filter: Option<TargetFilter>,
}

/// The answer to `Target.setDiscoverTargets`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetDiscoverTargetsReturns {}

impl SetDiscoverTargetsParams {
    pub const METHOD: &'static str = "Target.setDiscoverTargets";
}

impl super::Command for SetDiscoverTargetsParams {
    const METHOD: &'static str = "Target.setDiscoverTargets";
    type Returns = SetDiscoverTargetsReturns;
}

/// Parameters of `Target.setRemoteLocations`.
///
/// Enables target discovery for the specified locations, when `setDiscoverTargets` was set to
/// `true`.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetRemoteLocationsParams {
    /// List of remote locations.
    pub locations: Vec<RemoteLocation>,
}

/// The answer to `Target.setRemoteLocations`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct SetRemoteLocationsReturns {}

impl SetRemoteLocationsParams {
    pub const METHOD: &'static str = "Target.setRemoteLocations";
}

impl super::Command for SetRemoteLocationsParams {
    const METHOD: &'static str = "Target.setRemoteLocations";
    type Returns = SetRemoteLocationsReturns;
}

/// Parameters of `Target.getDevToolsTarget`.
///
/// Gets the targetId of the DevTools page target opened for the given target
/// (if any).
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetDevToolsTargetParams {
    /// Page or tab target ID.
    #[serde(rename = "targetId")]
    pub target_id: TargetID,
}

/// The answer to `Target.getDevToolsTarget`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GetDevToolsTargetReturns {
    /// The targetId of DevTools page target if exists.
    #[serde(rename = "targetId", default, skip_serializing_if = "Option::is_none")]
    pub target_id: Option<TargetID>,
}

impl GetDevToolsTargetParams {
    pub const METHOD: &'static str = "Target.getDevToolsTarget";
}

impl super::Command for GetDevToolsTargetParams {
    const METHOD: &'static str = "Target.getDevToolsTarget";
    type Returns = GetDevToolsTargetReturns;
}

/// Parameters of `Target.openDevTools`.
///
/// Opens a DevTools window for the target.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct OpenDevToolsParams {
    /// This can be the page or tab target ID.
    #[serde(rename = "targetId")]
    pub target_id: TargetID,
    /// The id of the panel we want DevTools to open initially. Currently
    /// supported panels are elements, console, network, sources, resources,
    /// timeline, chrome-recorder, heap-profiler, lighthouse, and security.
    #[serde(rename = "panelId", default, skip_serializing_if = "Option::is_none")]
    pub panel_id: Option<String>,
}

/// The answer to `Target.openDevTools`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct OpenDevToolsReturns {
    /// The targetId of DevTools page target.
    #[serde(rename = "targetId")]
    pub target_id: TargetID,
}

impl OpenDevToolsParams {
    pub const METHOD: &'static str = "Target.openDevTools";
}

impl super::Command for OpenDevToolsParams {
    const METHOD: &'static str = "Target.openDevTools";
    type Returns = OpenDevToolsReturns;
}

/// The event `Target.attachedToTarget`.
///
/// Issued when attached to target because of auto-attach or `attachToTarget` command.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AttachedToTargetEvent {
    /// Identifier assigned to the session used to send/receive messages.
    #[serde(rename = "sessionId")]
    pub session_id: SessionID,
    #[serde(rename = "targetInfo")]
    pub target_info: TargetInfo,
    #[serde(rename = "waitingForDebugger")]
    pub waiting_for_debugger: bool,
}

impl AttachedToTargetEvent {
    pub const NAME: &'static str = "Target.attachedToTarget";
}

impl super::Event for AttachedToTargetEvent {
    const NAME: &'static str = "Target.attachedToTarget";
}

/// The event `Target.detachedFromTarget`.
///
/// Issued when detached from target for any reason (including `detachFromTarget` command). Can be
/// issued multiple times per target if multiple sessions have been attached to it.
///
/// **Experimental.**
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct DetachedFromTargetEvent {
    /// Detached session identifier.
    #[serde(rename = "sessionId")]
    pub session_id: SessionID,
    /// Deprecated.
    ///
    /// **Deprecated.**
    #[serde(rename = "targetId", default, skip_serializing_if = "Option::is_none")]
    pub target_id: Option<TargetID>,
}

impl DetachedFromTargetEvent {
    pub const NAME: &'static str = "Target.detachedFromTarget";
}

impl super::Event for DetachedFromTargetEvent {
    const NAME: &'static str = "Target.detachedFromTarget";
}

/// The event `Target.receivedMessageFromTarget`.
///
/// Notifies about a new protocol message received from the session (as reported in
/// `attachedToTarget` event).
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ReceivedMessageFromTargetEvent {
    /// Identifier of a session which sends a message.
    #[serde(rename = "sessionId")]
    pub session_id: SessionID,
    pub message: String,
    /// Deprecated.
    ///
    /// **Deprecated.**
    #[serde(rename = "targetId", default, skip_serializing_if = "Option::is_none")]
    pub target_id: Option<TargetID>,
}

impl ReceivedMessageFromTargetEvent {
    pub const NAME: &'static str = "Target.receivedMessageFromTarget";
}

impl super::Event for ReceivedMessageFromTargetEvent {
    const NAME: &'static str = "Target.receivedMessageFromTarget";
}

/// The event `Target.targetCreated`.
///
/// Issued when a possible inspection target is created.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct TargetCreatedEvent {
    #[serde(rename = "targetInfo")]
    pub target_info: TargetInfo,
}

impl TargetCreatedEvent {
    pub const NAME: &'static str = "Target.targetCreated";
}

impl super::Event for TargetCreatedEvent {
    const NAME: &'static str = "Target.targetCreated";
}

/// The event `Target.targetDestroyed`.
///
/// Issued when a target is destroyed.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct TargetDestroyedEvent {
    #[serde(rename = "targetId")]
    pub target_id: TargetID,
}

impl TargetDestroyedEvent {
    pub const NAME: &'static str = "Target.targetDestroyed";
}

impl super::Event for TargetDestroyedEvent {
    const NAME: &'static str = "Target.targetDestroyed";
}

/// The event `Target.targetCrashed`.
///
/// Issued when a target has crashed.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct TargetCrashedEvent {
    #[serde(rename = "targetId")]
    pub target_id: TargetID,
    /// Termination status type.
    pub status: String,
    /// Termination error code.
    #[serde(rename = "errorCode")]
    pub error_code: i64,
}

impl TargetCrashedEvent {
    pub const NAME: &'static str = "Target.targetCrashed";
}

impl super::Event for TargetCrashedEvent {
    const NAME: &'static str = "Target.targetCrashed";
}

/// The event `Target.targetInfoChanged`.
///
/// Issued when some information about a target has changed. This only happens between
/// `targetCreated` and `targetDestroyed`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct TargetInfoChangedEvent {
    #[serde(rename = "targetInfo")]
    pub target_info: TargetInfo,
}

impl TargetInfoChangedEvent {
    pub const NAME: &'static str = "Target.targetInfoChanged";
}

impl super::Event for TargetInfoChangedEvent {
    const NAME: &'static str = "Target.targetInfoChanged";
}
