<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>niello-host</AssemblyName>
    <RootNamespace>Niello.Host</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StreamJsonRpc" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Niello.Host.Tests" />
  </ItemGroup>

</Project>
