using System.Globalization;
using System.Text;

namespace Niello.Web;

/// <summary>One field of a generated designer partial class.</summary>
public sealed record DesignerField(string Name, string TypeName);

/// <summary>A designer partial class for a page, user control or master page.</summary>
/// <param name="Namespace">Namespace of the code-behind class, or null for the global namespace.</param>
/// <param name="ClassName">Code-behind class name (from <c>Inherits</c>).</param>
/// <param name="Fields">Control fields in document order.</param>
/// <param name="Unresolved">Controls whose type could not be resolved; their fields are typed <c>System.Web.UI.Control</c>.</param>
public sealed record DesignerPartial(string? Namespace, string ClassName, IReadOnlyList<DesignerField> Fields, IReadOnlyList<DesignerControl> Unresolved);

/// <summary>
/// Generates the designer partial class (the <c>.designer.cs</c> equivalent) for WebForms markup, enough for
/// IntelliSense in code-behind. Not byte-compatible with Visual Studio's output (brief 0003, out of scope).
/// </summary>
public static class DesignerPartialGenerator
{
    /// <summary>Fallback field type for controls whose type cannot be resolved.</summary>
    public const string FallbackType = "System.Web.UI.Control";

    /// <summary>
    /// Builds the partial class model for <paramref name="markup"/>. Returns null when the markup has no
    /// <c>Page</c>/<c>Control</c>/<c>Master</c> directive with an <c>Inherits</c> attribute.
    /// </summary>
    public static DesignerPartial? Build(string markup, ControlTypeResolver resolver)
    {
        ArgumentNullException.ThrowIfNull(resolver);
        var directive = AspxDirectiveParser.Parse(markup);
        if (directive?.Inherits is not { Length: > 0 } inherits)
        {
            return null;
        }

        // Inherits may be assembly-qualified ("Ns.Type, Assembly").
        var typeName = inherits.Split(',')[0].Trim();
        var dot = typeName.LastIndexOf('.');
        var ns = dot < 0 ? null : typeName[..dot];
        var cls = dot < 0 ? typeName : typeName[(dot + 1)..];

        var fields = new List<DesignerField>();
        var unresolved = new List<DesignerControl>();
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var control in DesignerControlScanner.Scan(markup))
        {
            if (!seen.Add(control.Id))
            {
                continue;
            }

            var type = resolver.Resolve(control);
            if (type is null)
            {
                unresolved.Add(control);
                type = FallbackType;
            }

            fields.Add(new DesignerField(control.Id, type));
        }

        return new DesignerPartial(ns, cls, fields, unresolved);
    }

    /// <summary>Renders <paramref name="partial"/> as C# source.</summary>
    public static string Render(DesignerPartial partial, string sourceDescription)
    {
        ArgumentNullException.ThrowIfNull(partial);
        var sb = new StringBuilder();
        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine(CultureInfo.InvariantCulture, $"//     Generated by Niello from {sourceDescription} for design-time IntelliSense.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("//------------------------------------------------------------------------------");
        var indent = string.Empty;
        if (partial.Namespace is not null)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"namespace {partial.Namespace}");
            sb.AppendLine("{");
            indent = "    ";
        }

        sb.AppendLine(CultureInfo.InvariantCulture, $"{indent}public partial class {partial.ClassName}");
        sb.AppendLine(CultureInfo.InvariantCulture, $"{indent}{{");
        foreach (var field in partial.Fields)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"{indent}    protected global::{field.TypeName} {field.Name};");
        }

        sb.AppendLine(CultureInfo.InvariantCulture, $"{indent}}}");
        if (partial.Namespace is not null)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }
}
