[package]
name = "eludite-git"
description = "Eludite git integration (libgit2)."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
git2.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
