[package]
name = "niello-dbg-netfx"
description = "DAP server for .NET Framework over ICorDebug (Windows)."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "niello-dbg-netfx"
path = "src/main.rs"

[lints]
workspace = true
