using System.Diagnostics;
using Eludite.Host.Lsp;
using Eludite.Host.Rpc;

namespace Eludite.Host.Legacy;

/// <summary>
/// Prepares legacy (non-SDK) projects before the Roslyn language server loads a solution (brief 0003 spike):
/// locates Mono's MSBuild (or falls back to the SDK's, in-process), points MSBuild at the .NET Framework
/// reference-assembly packages, and generates WebForms designer partials that Roslyn's build host picks up through
/// an injected targets file. Everything here reaches Roslyn through environment variables on its process, which
/// MSBuild reads as properties; Roslyn itself is unchanged.
/// </summary>
public sealed class LegacyDesignTime : ISolutionPreparer
{
    private readonly TextWriter _log;
    private readonly string _cacheDirectory;
    private readonly ReferenceAssemblies _referenceAssemblies;

    public LegacyDesignTime(TextWriter log, string? cacheDirectory = null, ReferenceAssemblies? referenceAssemblies = null)
    {
        _log = log;
        _cacheDirectory = cacheDirectory ?? DefaultCacheDirectory();
        _referenceAssemblies = referenceAssemblies ?? new ReferenceAssemblies();
        // ELUDITE_LEGACY_MONO=0 hides Mono, so Roslyn and the host fall back to the .NET SDK's MSBuild (brief 0003 matrix).
        Mono = Environment.GetEnvironmentVariable("ELUDITE_LEGACY_MONO") == "0" ? null : MonoInstallation.Locate();
    }

    /// <summary>The located Mono, or null (Windows, or not installed).</summary>
    public MonoInstallation? Mono { get; }

    /// <summary>Injected targets file (designer partials); exists from construction on, empty until prepared.</summary>
    public string InjectionTargetsPath => Path.Combine(_cacheDirectory, "designtime", "eludite.designer.targets");

    /// <summary>Designer partials generated by the last <see cref="PrepareAsync"/>, keyed by project.</summary>
    public IReadOnlyDictionary<string, IReadOnlyList<GeneratedDesigner>> Designers { get; private set; } =
        new Dictionary<string, IReadOnlyList<GeneratedDesigner>>();

    /// <summary>Evaluations from the last <see cref="PrepareAsync"/>.</summary>
    public IReadOnlyList<LegacyProjectEvaluation> Evaluations { get; private set; } = [];

    /// <summary>Default cache: <c>$ELUDITE_CACHE_DIR</c>, else <c>$XDG_CACHE_HOME/eludite</c>, else <c>~/.cache/eludite</c>.</summary>
    public static string DefaultCacheDirectory()
    {
        if (Environment.GetEnvironmentVariable("ELUDITE_CACHE_DIR") is { Length: > 0 } explicitDir)
        {
            return explicitDir;
        }

        var xdg = Environment.GetEnvironmentVariable("XDG_CACHE_HOME");
        return Path.Combine(
            string.IsNullOrEmpty(xdg) ? Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".cache") : xdg,
            "eludite");
    }

    /// <summary>
    /// Environment for the Roslyn language server process: Mono on <c>PATH</c> (Roslyn then loads non-SDK projects
    /// with its Mono build host), <c>TargetFrameworkRootPath</c> for the reference-assembly packages, and
    /// <c>CustomAfterMicrosoftCommonTargets</c> for designer injection.
    /// </summary>
    public IReadOnlyDictionary<string, string> RoslynEnvironment()
    {
        var env = new Dictionary<string, string>(StringComparer.Ordinal);
        if (Mono is not null)
        {
            foreach (var (k, v) in Mono.Environment)
            {
                env[k] = v;
            }
        }

        if (_referenceAssemblies.MergedRoot(_cacheDirectory) is { } root)
        {
            env["TargetFrameworkRootPath"] = root;
        }

        if (!File.Exists(InjectionTargetsPath))
        {
            WebFormsDesignerService.WriteInjectionTargets(InjectionTargetsPath, []);
        }

        env["CustomAfterMicrosoftCommonTargets"] = InjectionTargetsPath;
        return env;
    }

    /// <summary>Path-case corrections from the last <see cref="PrepareAsync"/>, keyed by project.</summary>
    public IReadOnlyDictionary<string, IReadOnlyList<PathCaseFixup>> CaseFixups { get; private set; } =
        new Dictionary<string, IReadOnlyList<PathCaseFixup>>();

    /// <summary>
    /// Evaluates the legacy projects of <paramref name="solutionOrProject"/> (one MSBuild process for all of them),
    /// writes designer partials for the WebForms ones, finds Compile items whose letter case differs from the disk
    /// (off Windows), and writes the injection targets. Never throws for project problems; they are logged as
    /// diagnostics.
    /// </summary>
    public async Task PrepareAsync(string? solutionOrProject, CancellationToken cancellationToken)
    {
        // ELUDITE_LEGACY_DESIGNERS=0 loads projects exactly as written (brief 0003 load matrix).
        if (solutionOrProject is null || !File.Exists(solutionOrProject) || Environment.GetEnvironmentVariable("ELUDITE_LEGACY_DESIGNERS") == "0")
        {
            return;
        }

        var sw = Stopwatch.StartNew();
        var legacy = SolutionProjects.Read(solutionOrProject).Where(SolutionProjects.IsLegacy).ToList();
        // On Windows only WebForms projects need work (no case or COM problems), so skip evaluating the rest.
        var projects = OperatingSystem.IsWindows() ? legacy.Where(SolutionProjects.MentionsMarkup).ToList() : legacy;
        if (projects.Count == 0)
        {
            return;
        }

        Evaluations = await EvaluateAsync(projects, cancellationToken).ConfigureAwait(false);
        var designers = new WebFormsDesignerService(Path.Combine(_cacheDirectory, "designtime", "generated"));
        var byProject = new Dictionary<string, IReadOnlyList<GeneratedDesigner>>(StringComparer.Ordinal);
        var fixups = new Dictionary<string, IReadOnlyList<PathCaseFixup>>(StringComparer.Ordinal);
        foreach (var evaluation in Evaluations)
        {
            if (!evaluation.Loaded)
            {
                await _log.WriteLineAsync($"[legacy] warning: {evaluation.ProjectPath} did not evaluate ({evaluation.FailureClass}): {evaluation.FailureReason}").ConfigureAwait(false);
                continue;
            }

            if (evaluation.MarkupItems.Count > 0)
            {
                byProject[evaluation.ProjectPath] = designers.Generate(evaluation);
            }

            if (PathCaseFixups.Find(evaluation) is { Count: > 0 } found)
            {
                fixups[evaluation.ProjectPath] = found;
                foreach (var f in found)
                {
                    await _log.WriteLineAsync($"[legacy] warning: {evaluation.ProjectPath}: Compile item '{f.Declared}' differs in case from '{f.OnDisk}'; using the file on disk").ConfigureAwait(false);
                }
            }
        }

        WebFormsDesignerService.WriteInjectionTargets(InjectionTargetsPath, byProject.Select(kv => (kv.Key, kv.Value)), fixups);
        Designers = byProject;
        CaseFixups = fixups;
        await _log.WriteLineAsync(
            $"[legacy] {Evaluations.Count} legacy project(s) evaluated with {Evaluations.FirstOrDefault()?.Evaluator}; " +
            $"{byProject.Values.Sum(d => d.Count)} designer partial(s), {fixups.Values.Sum(f => f.Count)} case fixup(s) in {sw.ElapsedMilliseconds} ms").ConfigureAwait(false);
    }

    /// <summary>
    /// The MSBuild that evaluates legacy projects, in the order <see cref="EvaluateAsync"/> tries them: Mono's, then
    /// Build Tools' (Windows), then the .NET SDK's in-process.
    /// </summary>
    public MsBuildInfo SelectedMsBuild()
    {
        if (Mono is not null)
        {
            return new MsBuildInfo("mono", Mono.MsBuildDll, Mono.Source);
        }

        if (BuildToolsInstallation.Locate() is { } tools)
        {
            return new MsBuildInfo("buildTools", tools.MsBuildExe, tools.Source);
        }

        return new MsBuildInfo("sdk", null, "Microsoft.Build.Locator");
    }

    /// <summary>
    /// <see cref="ISolutionPreparer"/>: runs <see cref="PrepareAsync"/> and reports the MSBuild used, the corrections
    /// applied and the evaluation problems for <c>eludite/solution/status</c>.
    /// </summary>
    public async Task<SolutionPreparation> PrepareSolutionAsync(string solutionPath, CancellationToken cancellationToken)
    {
        if (!SolutionProjects.Read(solutionPath).Any(SolutionProjects.IsLegacy))
        {
            return SolutionPreparation.None;
        }

        var msbuild = SelectedMsBuild();
        Evaluations = [];
        Designers = new Dictionary<string, IReadOnlyList<GeneratedDesigner>>();
        CaseFixups = new Dictionary<string, IReadOnlyList<PathCaseFixup>>();
        try
        {
            await PrepareAsync(solutionPath, cancellationToken).ConfigureAwait(false);
        }
        catch (Exception ex) when (ex is not OutOfMemoryException and not OperationCanceledException)
        {
            await _log.WriteLineAsync($"[legacy] preparation failed (projects load as written): {ex}").ConfigureAwait(false);
            return new SolutionPreparation(msbuild, [], [new HostDiagnostic("warning", "ELUDITE0004", $"Legacy project preparation failed; projects load as written: {ex.Message}")], 0);
        }

        var corrections = new List<Correction>();
        var diagnostics = new List<HostDiagnostic>();
        foreach (var (project, designers) in Designers)
        {
            corrections.Add(new Correction("designerPartials", project, designers.Count));
        }

        foreach (var (project, fixups) in CaseFixups)
        {
            corrections.Add(new Correction("caseFixups", project, fixups.Count));
            diagnostics.AddRange(fixups.Select(f => new HostDiagnostic(
                "warning", "ELUDITE0106", $"Compile item '{f.Declared}' differs in case from '{f.OnDisk}' on disk; using the file on disk.") { Project = project }));
        }

        foreach (var evaluation in Evaluations)
        {
            if (!evaluation.Loaded)
            {
                diagnostics.Add(new HostDiagnostic("warning", "ELUDITE0003", $"{Path.GetFileName(evaluation.ProjectPath)} did not evaluate: {evaluation.FailureReason}")
                {
                    Project = evaluation.ProjectPath,
                    Class = WireClass(evaluation.FailureClass),
                });
            }

            var com = evaluation.Diagnostics.Count(d => FailureClassifier.Classify(d.Code, d.Message) == FailureClassifier.Com);
            if (com > 0 && !OperatingSystem.IsWindows())
            {
                corrections.Add(new Correction("comReferencesRemoved", evaluation.ProjectPath, com));
            }
        }

        return new SolutionPreparation(msbuild, corrections, diagnostics, Evaluations.Count(e => !e.Loaded));
    }

    Task<SolutionPreparation> ISolutionPreparer.PrepareAsync(string solutionPath, CancellationToken cancellationToken) =>
        PrepareSolutionAsync(solutionPath, cancellationToken);

    /// <summary>Maps a <see cref="FailureClassifier"/> class to its wire name.</summary>
    internal static string? WireClass(string? failureClass) => failureClass switch
    {
        null => null,
        FailureClassifier.MissingTargets => "missingTargets",
        FailureClassifier.Com => "com",
        FailureClassifier.Packages => "packages",
        FailureClassifier.WebTargets => "webTargets",
        _ => "other",
    };

    /// <summary>Evaluates with Mono's MSBuild when located, else the SDK's MSBuild in-process.</summary>
    public async Task<IReadOnlyList<LegacyProjectEvaluation>> EvaluateAsync(IReadOnlyList<string> projects, CancellationToken cancellationToken)
    {
        var work = Path.Combine(_cacheDirectory, "designtime");
        if (Mono is not null)
        {
            var evaluator = new CommandLineMsBuildEvaluator(MsBuildCommand.ForMono(Mono), _referenceAssemblies, work, _log);
            return await evaluator.EvaluateAsync(projects, cancellationToken).ConfigureAwait(false);
        }

        if (BuildToolsInstallation.Locate() is { } tools)
        {
            var evaluator = new CommandLineMsBuildEvaluator(MsBuildCommand.ForBuildTools(tools), _referenceAssemblies, work, _log);
            return await evaluator.EvaluateAsync(projects, cancellationToken).ConfigureAwait(false);
        }

        return await Task.Run(() => new InProcessMsBuildEvaluator(_referenceAssemblies, work).Evaluate(projects, cancellationToken), cancellationToken).ConfigureAwait(false);
    }
}
