[package]
name = "niello-workspace"
description = "Client-side solution and project model for Niello."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
roxmltree.workspace = true
serde.workspace = true

[lints]
workspace = true
